# Generated from the frozen pre-1.0 registered-name set. Do not edit.
#
# Runs in __init__ because the registry lives in another module: state
# mutated there during precompilation would not be saved.

function __init__()
    InfrastructureCoreOpenAPIModels.register_model_type!(AverageRateCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(CostCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(DbdPnts)
    InfrastructureCoreOpenAPIModels.register_model_type!(FdbdPnts)
    InfrastructureCoreOpenAPIModels.register_model_type!(FuelCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(GenericOperationCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(HydroGenerationCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(HydroReservoirCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(HydroStorageGenerationCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(ImportExportCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(ImportExportTimeSeriesCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(IncrementalCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(IncrementalCurveFunctionData)
    InfrastructureCoreOpenAPIModels.register_model_type!(InputOutputCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(InputOutputCurveFunctionData)
    InfrastructureCoreOpenAPIModels.register_model_type!(LoadCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(MarketBidCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(MarketBidTimeSeriesCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(ProductionVariableCostCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(RenewableGenerationCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(StartUpShutDown)
    InfrastructureCoreOpenAPIModels.register_model_type!(StartUpStages)
    InfrastructureCoreOpenAPIModels.register_model_type!(StorageCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(StorageCostStartUp)
    InfrastructureCoreOpenAPIModels.register_model_type!(ThermalGenerationCost)
    InfrastructureCoreOpenAPIModels.register_model_type!(ThermalGenerationCostStartUp)
    InfrastructureCoreOpenAPIModels.register_model_type!(TimeSeriesAverageRateCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(TimeSeriesIncrementalCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(TimeSeriesInputOutputCurve)
    InfrastructureCoreOpenAPIModels.register_model_type!(TurbinePump)
    InfrastructureCoreOpenAPIModels.register_model_type!(TwoTerminalLoss)
    InfrastructureCoreOpenAPIModels.register_model_type!(ValueCurve)
    return nothing
end
