# Generated from the declared model types. Do not edit.
#
# Runs in __init__ because the registry lives in another module: state
# mutated there during precompilation would not be saved.

function __init__()
    register_model_type!(AverageRateCurve)
    register_model_type!(ComplexNumber)
    register_model_type!(CostCurve)
    register_model_type!(DbdPnts)
    register_model_type!(FdbdPnts)
    register_model_type!(FeatureValue)
    register_model_type!(FromTo)
    register_model_type!(FromToToFrom)
    register_model_type!(FuelCurve)
    register_model_type!(FuelCurveFuelCost)
    register_model_type!(FunctionData)
    register_model_type!(GenericOperationCost)
    register_model_type!(GeographicInfo)
    register_model_type!(HydroGenerationCost)
    register_model_type!(HydroReservoirCost)
    register_model_type!(HydroStorageGenerationCost)
    register_model_type!(ImportExportCost)
    register_model_type!(InOut)
    register_model_type!(IncrementalCurve)
    register_model_type!(IncrementalCurveFunctionData)
    register_model_type!(InputOutputCurve)
    register_model_type!(InputOutputCurveFunctionData)
    register_model_type!(LinearFunctionData)
    register_model_type!(LoadCost)
    register_model_type!(MarketBidCost)
    register_model_type!(MinMax)
    register_model_type!(PiecewiseLinearData)
    register_model_type!(PiecewiseStepData)
    register_model_type!(ProductionVariableCostCurve)
    register_model_type!(QuadraticFunctionData)
    register_model_type!(RenewableGenerationCost)
    register_model_type!(StartUpShutDown)
    register_model_type!(StartUpStages)
    register_model_type!(StorageCost)
    register_model_type!(StorageCostStartUp)
    register_model_type!(StorageCostStartUpOneOf)
    register_model_type!(SupplementalAttributeAssociation)
    register_model_type!(TechnologyFinancialData)
    register_model_type!(ThermalGenerationCost)
    register_model_type!(ThermalGenerationCostStartUp)
    register_model_type!(TimeSeriesAssociation)
    register_model_type!(TurbinePump)
    register_model_type!(TwoTerminalLoss)
    register_model_type!(UpDown)
    register_model_type!(ValueCurve)
    register_model_type!(XYCoords)
    return nothing
end
