repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD013]
  - repo: https://github.com/domluna/JuliaFormatter.jl
    rev: v1.0.61
    hooks:
      - id: julia-formatter
