# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FixedForcedOutage

    FixedForcedOutage(;
        id=nothing,
        outage_status=nothing,
        monitored_components=Int64[],
    )

    - id::Int64
    - outage_status::Float64
    - monitored_components::Vector{Int64} : IDs of devices whose post-contingency state should be modeled when this outage occurs. Empty by default; semantics of an empty list are decided by the downstream consumer.
"""
Base.@kwdef mutable struct FixedForcedOutage <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    outage_status::Union{Nothing, Float64} = nothing
    monitored_components::Union{Nothing, Vector{Int64}} = Int64[]

    function FixedForcedOutage(id, outage_status, monitored_components, )
        o = new(id, outage_status, monitored_components, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FixedForcedOutage

const _property_types_FixedForcedOutage = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("outage_status")=>"Float64", Symbol("monitored_components")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ FixedForcedOutage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FixedForcedOutage[name]))}

function OpenAPI.check_required(o::FixedForcedOutage)
    o.id === nothing && (return false)
    o.outage_status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::FixedForcedOutage)
    OpenAPI.validate_property(FixedForcedOutage, Symbol("id"), o.id)
    OpenAPI.validate_property(FixedForcedOutage, Symbol("outage_status"), o.outage_status)
    OpenAPI.validate_property(FixedForcedOutage, Symbol("monitored_components"), o.monitored_components)
end

function OpenAPI.validate_property(::Type{ FixedForcedOutage }, name::Symbol, val)



    if name === Symbol("monitored_components")
        OpenAPI.validate_param(name, "FixedForcedOutage", :uniqueItems, val, true)
    end
end
