# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ThreeWindingTransformer
A three-winding transformer, modeled as an equivalent star: each referenced &#x60;TransformerCircuit&#x60; connects a terminal bus to the star (hidden) bus and carries that winding&#39;s series electrical data; availability is circuit-level. The pairwise measured impedances &#x60;r_12&#x60;/&#x60;x_12&#x60;, &#x60;r_23&#x60;/&#x60;x_23&#x60;, &#x60;r_31&#x60;/&#x60;x_31&#x60; (PSS/E CZ &#x3D; 1, each in pu on the corresponding &#x60;base_power_12&#x60;/&#x60;base_power_23&#x60;/&#x60;base_power_31&#x60; and referenced to the first-index winding&#39;s base voltage) are optional and must be set together or all be absent; the star-leg impedances derived from them at parse time live on the circuits and are not synced back. Power-flow and Ybus assembly read the per-circuit star-leg impedances, not the pairwise fields. The model is described in Chapter 3.6 of J.D. Glover, M.S. Sarma and T. Overbye: Power Systems Analysis and Design.

    ThreeWindingTransformer(;
        id=nothing,
        name=nothing,
        primary_circuit=nothing,
        secondary_circuit=nothing,
        tertiary_circuit=nothing,
        star_bus=nothing,
        parameter_units="DEVICE_BASE",
        r_12=nothing,
        x_12=nothing,
        r_23=nothing,
        x_23=nothing,
        r_31=nothing,
        x_31=nothing,
        base_power_12=nothing,
        base_power_23=nothing,
        base_power_31=nothing,
        admittance_units="DEVICE_BASE",
        magnetizing_shunt=ComplexNumber(; real=0.0, imag=0.0),
        shunt_location="PRIMARY",
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - primary_circuit::Int64 : The primary &#x60;TransformerCircuit&#x60; connecting the primary bus to the star bus.
    - secondary_circuit::Int64 : The secondary &#x60;TransformerCircuit&#x60; connecting the secondary bus to the star bus.
    - tertiary_circuit::Int64 : The tertiary &#x60;TransformerCircuit&#x60; connecting the tertiary bus to the star bus.
    - star_bus::Int64 : Star (hidden) Bus that this component (equivalent model) is connected to.
    - parameter_units::String : Unit basis for the pairwise measured impedance fields (r_12, x_12, r_23, x_23, r_31, x_31). PSS/E supplies a single CZ flag for the whole three-winding transformer record, so one basis governs all three winding pairs.
    - r_12::Float64 : Measured resistance, referenced to the primary winding&#39;s base voltage, from primary to secondary windings (R1-2 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - x_12::Float64 : Measured reactance, referenced to the primary winding&#39;s base voltage, from primary to secondary windings (X1-2 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - r_23::Float64 : Measured resistance, referenced to the secondary winding&#39;s base voltage, from secondary to tertiary windings (R2-3 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - x_23::Float64 : Measured reactance, referenced to the secondary winding&#39;s base voltage, from secondary to tertiary windings (X2-3 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - r_31::Float64 : Measured resistance, referenced to the tertiary winding&#39;s base voltage, from tertiary to primary windings (R3-1 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - x_31::Float64 : Measured reactance, referenced to the tertiary winding&#39;s base voltage, from tertiary to primary windings (X3-1 in PSS/E). Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - base_power_12::Float64 : Base power for per unitization for primary-secondary windings. Units: MVA.
    - base_power_23::Float64 : Base power for per unitization for secondary-tertiary windings. Units: MVA.
    - base_power_31::Float64 : Base power for per unitization for tertiary-primary windings. Units: MVA.
    - admittance_units::String : Unit basis for the magnetizing_shunt admittance.
    - magnetizing_shunt::ComplexNumber
    - shunt_location::String : Placement of &#x60;magnetizing_shunt&#x60; in the equivalent star model.
"""
Base.@kwdef mutable struct ThreeWindingTransformer <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    primary_circuit::Union{Nothing, Int64} = nothing
    secondary_circuit::Union{Nothing, Int64} = nothing
    tertiary_circuit::Union{Nothing, Int64} = nothing
    star_bus::Union{Nothing, Int64} = nothing
    parameter_units::Union{Nothing, String} = "DEVICE_BASE"
    r_12::Union{Nothing, Float64} = nothing
    x_12::Union{Nothing, Float64} = nothing
    r_23::Union{Nothing, Float64} = nothing
    x_23::Union{Nothing, Float64} = nothing
    r_31::Union{Nothing, Float64} = nothing
    x_31::Union{Nothing, Float64} = nothing
    base_power_12::Union{Nothing, Float64} = nothing
    base_power_23::Union{Nothing, Float64} = nothing
    base_power_31::Union{Nothing, Float64} = nothing
    admittance_units::Union{Nothing, String} = "DEVICE_BASE"
    magnetizing_shunt = ComplexNumber(; real=0.0, imag=0.0) # spec type: Union{ Nothing, ComplexNumber }
    shunt_location::Union{Nothing, String} = "PRIMARY"

    function ThreeWindingTransformer(id, name, primary_circuit, secondary_circuit, tertiary_circuit, star_bus, parameter_units, r_12, x_12, r_23, x_23, r_31, x_31, base_power_12, base_power_23, base_power_31, admittance_units, magnetizing_shunt, shunt_location, )
        o = new(id, name, primary_circuit, secondary_circuit, tertiary_circuit, star_bus, parameter_units, r_12, x_12, r_23, x_23, r_31, x_31, base_power_12, base_power_23, base_power_31, admittance_units, magnetizing_shunt, shunt_location, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ThreeWindingTransformer

const _property_types_ThreeWindingTransformer = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("primary_circuit")=>"Int64", Symbol("secondary_circuit")=>"Int64", Symbol("tertiary_circuit")=>"Int64", Symbol("star_bus")=>"Int64", Symbol("parameter_units")=>"String", Symbol("r_12")=>"Float64", Symbol("x_12")=>"Float64", Symbol("r_23")=>"Float64", Symbol("x_23")=>"Float64", Symbol("r_31")=>"Float64", Symbol("x_31")=>"Float64", Symbol("base_power_12")=>"Float64", Symbol("base_power_23")=>"Float64", Symbol("base_power_31")=>"Float64", Symbol("admittance_units")=>"String", Symbol("magnetizing_shunt")=>"ComplexNumber", Symbol("shunt_location")=>"String", )
OpenAPI.property_type(::Type{ ThreeWindingTransformer }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ThreeWindingTransformer[name]))}

function OpenAPI.check_required(o::ThreeWindingTransformer)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.primary_circuit === nothing && (return false)
    o.secondary_circuit === nothing && (return false)
    o.tertiary_circuit === nothing && (return false)
    o.star_bus === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ThreeWindingTransformer)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("id"), o.id)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("name"), o.name)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("primary_circuit"), o.primary_circuit)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("secondary_circuit"), o.secondary_circuit)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("tertiary_circuit"), o.tertiary_circuit)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("star_bus"), o.star_bus)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("parameter_units"), o.parameter_units)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("r_12"), o.r_12)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("x_12"), o.x_12)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("r_23"), o.r_23)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("x_23"), o.x_23)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("r_31"), o.r_31)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("x_31"), o.x_31)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("base_power_12"), o.base_power_12)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("base_power_23"), o.base_power_23)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("base_power_31"), o.base_power_31)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("admittance_units"), o.admittance_units)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("magnetizing_shunt"), o.magnetizing_shunt)
    OpenAPI.validate_property(ThreeWindingTransformer, Symbol("shunt_location"), o.shunt_location)
end

function OpenAPI.validate_property(::Type{ ThreeWindingTransformer }, name::Symbol, val)







    if name === Symbol("parameter_units")
        OpenAPI.validate_param(name, "ThreeWindingTransformer", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end











    if name === Symbol("admittance_units")
        OpenAPI.validate_param(name, "ThreeWindingTransformer", :enum, val, ["NATURAL_UNITS", "DEVICE_MVAR", "DEVICE_BASE"])
    end



    if name === Symbol("shunt_location")
        OpenAPI.validate_param(name, "ThreeWindingTransformer", :enum, val, ["PRIMARY", "STAR"])
    end

end
