# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ComplexNumber_1
Impedance between the hybrid system and the grid interconnection. Per-unit on system base. Units: pu.

    ComplexNumber1(;
        real=nothing,
        imag=nothing,
    )

    - real::Float64
    - imag::Float64
"""
Base.@kwdef mutable struct ComplexNumber1 <: OpenAPI.APIModel
    real::Union{Nothing, Float64} = nothing
    imag::Union{Nothing, Float64} = nothing

    function ComplexNumber1(real, imag, )
        o = new(real, imag, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ComplexNumber1

const _property_types_ComplexNumber1 = Dict{Symbol,String}(Symbol("real")=>"Float64", Symbol("imag")=>"Float64", )
OpenAPI.property_type(::Type{ ComplexNumber1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ComplexNumber1[name]))}

function OpenAPI.check_required(o::ComplexNumber1)
    true
end

function OpenAPI.validate_properties(o::ComplexNumber1)
    OpenAPI.validate_property(ComplexNumber1, Symbol("real"), o.real)
    OpenAPI.validate_property(ComplexNumber1, Symbol("imag"), o.imag)
end

function OpenAPI.validate_property(::Type{ ComplexNumber1 }, name::Symbol, val)


end
