# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PlannedOutage
Supplemental attribute describing outages that are scheduled in advance, naming the time series that carries the schedule.

    PlannedOutage(;
        id=nothing,
        outage_schedule=nothing,
        monitored_components=Int64[],
    )

    - id::Int64
    - outage_schedule::String
    - monitored_components::Vector{Int64} : IDs of devices whose post-contingency state should be modeled when this outage occurs. Empty by default; semantics of an empty list are decided by the downstream consumer.
"""
Base.@kwdef mutable struct PlannedOutage <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    outage_schedule::Union{Nothing, String} = nothing
    monitored_components::Union{Nothing, Vector{Int64}} = Int64[]

    function PlannedOutage(id, outage_schedule, monitored_components, )
        o = new(id, outage_schedule, monitored_components, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PlannedOutage

const _property_types_PlannedOutage = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("outage_schedule")=>Union{Nothing, String}, Symbol("monitored_components")=>Union{Nothing, Vector{Int64}}, )
OpenAPI.property_type(::Type{ PlannedOutage }, name::Symbol) = _property_types_PlannedOutage[name]

function OpenAPI.check_required(o::PlannedOutage)
    o.id === nothing && (return false)
    o.outage_schedule === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PlannedOutage)
    OpenAPI.validate_property(PlannedOutage, Symbol("id"), o.id)
    OpenAPI.validate_property(PlannedOutage, Symbol("outage_schedule"), o.outage_schedule)
    OpenAPI.validate_property(PlannedOutage, Symbol("monitored_components"), o.monitored_components)
end

function OpenAPI.validate_property(::Type{ PlannedOutage }, name::Symbol, val)



    if name === Symbol("monitored_components")
        OpenAPI.validate_param(name, "PlannedOutage", :uniqueItems, val, true)
    end
end
