# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TwoTerminalGenericHVDCLine
A High Voltage DC line, which must be connected to an ACBus on each end. This model is appropriate for operational simulations with a linearized DC power flow approximation with losses proportional to the power flow. For modeling a DC network, see TModelHVDCLine.

    TwoTerminalGenericHVDCLine(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        arc=nothing,
        active_power_limits_from=nothing,
        active_power_limits_to=nothing,
        reactive_power_limits_from=nothing,
        reactive_power_limits_to=nothing,
        loss=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - active_power_flow::Float64 : Initial condition of active power flow on the line. Units: MW.
    - arc::Int64 : An Arc defining this line &#x60;from&#x60; a bus &#x60;to&#x60; another bus.
    - active_power_limits_from::MinMax
    - active_power_limits_to::MinMax
    - reactive_power_limits_from::MinMax
    - reactive_power_limits_to::MinMax
    - loss::TwoTerminalLoss
"""
Base.@kwdef mutable struct TwoTerminalGenericHVDCLine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    active_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    active_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    loss = nothing # spec type: Union{ Nothing, TwoTerminalLoss }

    function TwoTerminalGenericHVDCLine(id, name, available, active_power_flow, arc, active_power_limits_from, active_power_limits_to, reactive_power_limits_from, reactive_power_limits_to, loss, )
        o = new(id, name, available, active_power_flow, arc, active_power_limits_from, active_power_limits_to, reactive_power_limits_from, reactive_power_limits_to, loss, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TwoTerminalGenericHVDCLine

const _property_types_TwoTerminalGenericHVDCLine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("active_power_flow")=>"Float64", Symbol("arc")=>"Int64", Symbol("active_power_limits_from")=>"MinMax", Symbol("active_power_limits_to")=>"MinMax", Symbol("reactive_power_limits_from")=>"MinMax", Symbol("reactive_power_limits_to")=>"MinMax", Symbol("loss")=>"TwoTerminalLoss", )
OpenAPI.property_type(::Type{ TwoTerminalGenericHVDCLine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TwoTerminalGenericHVDCLine[name]))}

function OpenAPI.check_required(o::TwoTerminalGenericHVDCLine)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.active_power_limits_from === nothing && (return false)
    o.active_power_limits_to === nothing && (return false)
    o.reactive_power_limits_from === nothing && (return false)
    o.reactive_power_limits_to === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TwoTerminalGenericHVDCLine)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("id"), o.id)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("name"), o.name)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("available"), o.available)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("arc"), o.arc)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("active_power_limits_from"), o.active_power_limits_from)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("active_power_limits_to"), o.active_power_limits_to)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("reactive_power_limits_from"), o.reactive_power_limits_from)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("reactive_power_limits_to"), o.reactive_power_limits_to)
    OpenAPI.validate_property(TwoTerminalGenericHVDCLine, Symbol("loss"), o.loss)
end

function OpenAPI.validate_property(::Type{ TwoTerminalGenericHVDCLine }, name::Symbol, val)










end
