# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Source
An infinite bus with a constant voltage output.  Commonly used in dynamics simulations to represent a very large machine on a single bus or for the representation of import/exports in operational simulations.

    Source(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        active_power=0.0,
        reactive_power=0.0,
        active_power_limits=MinMax(; max=0.0, min=0.0),
        reactive_power_limits=MinMax(; max=0.0, min=0.0),
        parameter_units="DEVICE_BASE",
        R_th=0.0,
        X_th=0.0,
        internal_voltage=1.0,
        internal_angle=0.0,
        base_voltage=nothing,
        base_power=100.0,
        operation_cost=ImportExportCost(; import_offer_curves=CostCurve(; value_curve=ValueCurve(InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), variable_cost_type="COST", vom_cost=InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), export_offer_curves=CostCurve(; value_curve=ValueCurve(InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), variable_cost_type="COST", vom_cost=InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), energy_import_weekly_limit=1.0e6, energy_export_weekly_limit=1.0e6),
        dynamic_injector=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - bus::Int64 : ID of the bus that this component is connected to.
    - active_power::Float64 : Initial active power set point of the unit. For power flow, this is the steady state operating point of the system. For production cost modeling, this may or may not be used as the initial starting point for the solver, depending on the solver used. Units: MW.
    - reactive_power::Float64 : Initial reactive power set point of the unit. Units: MVAr.
    - active_power_limits::MinMax
    - reactive_power_limits::MinMax
    - parameter_units::String : Unit basis for this source&#39;s impedance fields (R_th, X_th).
    - R_th::Float64 : Source Thevenin resistance. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - X_th::Float64 : Source Thevenin reactance. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - internal_voltage::Float64 : Internal voltage. Units: pu.
    - internal_angle::Float64 : Internal angle. Units: rad.
    - base_voltage::Float64 : The base voltage. Units: kV.
    - base_power::Float64 : Base power of the unit for per unitization. Units: MVA.
    - operation_cost::ImportExportCost
    - dynamic_injector::Int64 : ID of the corresponding dynamic injection device, if any.
"""
Base.@kwdef mutable struct Source <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = 0.0
    reactive_power::Union{Nothing, Float64} = 0.0
    active_power_limits = MinMax(; max=0.0, min=0.0) # spec type: Union{ Nothing, MinMax }
    reactive_power_limits = MinMax(; max=0.0, min=0.0) # spec type: Union{ Nothing, MinMax }
    parameter_units::Union{Nothing, String} = "DEVICE_BASE"
    R_th::Union{Nothing, Float64} = 0.0
    X_th::Union{Nothing, Float64} = 0.0
    internal_voltage::Union{Nothing, Float64} = 1.0
    internal_angle::Union{Nothing, Float64} = 0.0
    base_voltage::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = 100.0
    operation_cost = ImportExportCost(; import_offer_curves=CostCurve(; value_curve=ValueCurve(InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), variable_cost_type="COST", vom_cost=InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), export_offer_curves=CostCurve(; value_curve=ValueCurve(InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), variable_cost_type="COST", vom_cost=InputOutputCurve(; curve_type="INPUT_OUTPUT", function_data=InputOutputCurveFunctionData(LinearFunctionData(; constant_term=0.0, function_type="LINEAR", proportional_term=0.0)), input_at_zero=0.0)), energy_import_weekly_limit=1.0e6, energy_export_weekly_limit=1.0e6) # spec type: Union{ Nothing, ImportExportCost }
    dynamic_injector::Union{Nothing, Int64} = nothing

    function Source(id, name, available, bus, active_power, reactive_power, active_power_limits, reactive_power_limits, parameter_units, R_th, X_th, internal_voltage, internal_angle, base_voltage, base_power, operation_cost, dynamic_injector, )
        o = new(id, name, available, bus, active_power, reactive_power, active_power_limits, reactive_power_limits, parameter_units, R_th, X_th, internal_voltage, internal_angle, base_voltage, base_power, operation_cost, dynamic_injector, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Source

const _property_types_Source = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("bus")=>"Int64", Symbol("active_power")=>"Float64", Symbol("reactive_power")=>"Float64", Symbol("active_power_limits")=>"MinMax", Symbol("reactive_power_limits")=>"MinMax", Symbol("parameter_units")=>"String", Symbol("R_th")=>"Float64", Symbol("X_th")=>"Float64", Symbol("internal_voltage")=>"Float64", Symbol("internal_angle")=>"Float64", Symbol("base_voltage")=>"Float64", Symbol("base_power")=>"Float64", Symbol("operation_cost")=>"ImportExportCost", Symbol("dynamic_injector")=>"Int64", )
OpenAPI.property_type(::Type{ Source }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Source[name]))}

function OpenAPI.check_required(o::Source)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    o.operation_cost === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Source)
    OpenAPI.validate_property(Source, Symbol("id"), o.id)
    OpenAPI.validate_property(Source, Symbol("name"), o.name)
    OpenAPI.validate_property(Source, Symbol("available"), o.available)
    OpenAPI.validate_property(Source, Symbol("bus"), o.bus)
    OpenAPI.validate_property(Source, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(Source, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(Source, Symbol("active_power_limits"), o.active_power_limits)
    OpenAPI.validate_property(Source, Symbol("reactive_power_limits"), o.reactive_power_limits)
    OpenAPI.validate_property(Source, Symbol("parameter_units"), o.parameter_units)
    OpenAPI.validate_property(Source, Symbol("R_th"), o.R_th)
    OpenAPI.validate_property(Source, Symbol("X_th"), o.X_th)
    OpenAPI.validate_property(Source, Symbol("internal_voltage"), o.internal_voltage)
    OpenAPI.validate_property(Source, Symbol("internal_angle"), o.internal_angle)
    OpenAPI.validate_property(Source, Symbol("base_voltage"), o.base_voltage)
    OpenAPI.validate_property(Source, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(Source, Symbol("operation_cost"), o.operation_cost)
    OpenAPI.validate_property(Source, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{ Source }, name::Symbol, val)









    if name === Symbol("parameter_units")
        OpenAPI.validate_param(name, "Source", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end









end
