# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ACBus
An AC bus.

    ACBus(;
        id=nothing,
        number=nothing,
        name=nothing,
        available=nothing,
        bustype=nothing,
        angle=nothing,
        magnitude=nothing,
        voltage_limits=nothing,
        base_voltage=nothing,
        area=nothing,
        load_zone=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - number::Int64 : A unique bus identification number (positive integer).
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations. This field should not be confused with the ISOLATED enum value.
    - bustype::String : Used to describe the connectivity and behavior of this bus. in psy5 a required param with an option to be nothing
    - angle::Float64 : Angle of the bus. Units: rad.
    - magnitude::Float64 : Voltage as a multiple of &#x60;base_voltage&#x60;. Units: pu.
    - voltage_limits::MinMax
    - base_voltage::Float64 : The base voltage. Units: kV.
    - area::Int64 : ID of the area containing the bus.
    - load_zone::Int64 : ID of the load zone containing the bus.
"""
Base.@kwdef mutable struct ACBus <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    number::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bustype::Union{Nothing, String} = nothing
    angle::Union{Nothing, Float64} = nothing
    magnitude::Union{Nothing, Float64} = nothing
    voltage_limits = nothing # spec type: Union{ Nothing, MinMax }
    base_voltage::Union{Nothing, Float64} = nothing
    area::Union{Nothing, Int64} = nothing
    load_zone::Union{Nothing, Int64} = nothing

    function ACBus(id, number, name, available, bustype, angle, magnitude, voltage_limits, base_voltage, area, load_zone, )
        o = new(id, number, name, available, bustype, angle, magnitude, voltage_limits, base_voltage, area, load_zone, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ACBus

const _property_types_ACBus = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("number")=>Union{Nothing, Int64}, Symbol("name")=>Union{Nothing, String}, Symbol("available")=>Union{Nothing, Bool}, Symbol("bustype")=>Union{Nothing, String}, Symbol("angle")=>Union{Nothing, Float64}, Symbol("magnitude")=>Union{Nothing, Float64}, Symbol("voltage_limits")=>Union{Nothing, MinMax}, Symbol("base_voltage")=>Union{Nothing, Float64}, Symbol("area")=>Union{Nothing, Int64}, Symbol("load_zone")=>Union{Nothing, Int64}, )
OpenAPI.property_type(::Type{ ACBus }, name::Symbol) = _property_types_ACBus[name]

function OpenAPI.check_required(o::ACBus)
    o.id === nothing && (return false)
    o.number === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ACBus)
    OpenAPI.validate_property(ACBus, Symbol("id"), o.id)
    OpenAPI.validate_property(ACBus, Symbol("number"), o.number)
    OpenAPI.validate_property(ACBus, Symbol("name"), o.name)
    OpenAPI.validate_property(ACBus, Symbol("available"), o.available)
    OpenAPI.validate_property(ACBus, Symbol("bustype"), o.bustype)
    OpenAPI.validate_property(ACBus, Symbol("angle"), o.angle)
    OpenAPI.validate_property(ACBus, Symbol("magnitude"), o.magnitude)
    OpenAPI.validate_property(ACBus, Symbol("voltage_limits"), o.voltage_limits)
    OpenAPI.validate_property(ACBus, Symbol("base_voltage"), o.base_voltage)
    OpenAPI.validate_property(ACBus, Symbol("area"), o.area)
    OpenAPI.validate_property(ACBus, Symbol("load_zone"), o.load_zone)
end

function OpenAPI.validate_property(::Type{ ACBus }, name::Symbol, val)





    if name === Symbol("bustype")
        OpenAPI.validate_param(name, "ACBus", :enum, val, ["PQ", "PV", "REF", "ISOLATED", "SLACK"])
    end







end
