# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""EnergyReservoirStorage_operation_cost
Operating cost of storage. or MarketBidCost

    EnergyReservoirStorageOperationCost(; value=nothing)
"""
mutable struct EnergyReservoirStorageOperationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ MarketBidCost, StorageCost }
    EnergyReservoirStorageOperationCost() = new()
    EnergyReservoirStorageOperationCost(value) = new(value)
end # type EnergyReservoirStorageOperationCost

function OpenAPI.property_type(::Type{ EnergyReservoirStorageOperationCost }, name::Symbol, json::Dict{String,Any})
    discriminator = json["cost_type"]
    if discriminator == "MARKET_BID"
        return (MarketBidCost)
    elseif discriminator == "STORAGE"
        return (StorageCost)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for EnergyReservoirStorageOperationCost"))
end
