# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TradingHub
A market trading hub: a named set of member buses at which hub-settled bids are priced. Membership is carried as TradingHubAssociation rows rather than a list on this record, matching the service-membership convention.

    TradingHub(;
        id=nothing,
        name=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the hub.
"""
Base.@kwdef mutable struct TradingHub <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing

    function TradingHub(id, name, )
        o = new(id, name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TradingHub

const _property_types_TradingHub = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("name")=>Union{Nothing, String}, )
OpenAPI.property_type(::Type{ TradingHub }, name::Symbol) = _property_types_TradingHub[name]

function OpenAPI.check_required(o::TradingHub)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TradingHub)
    OpenAPI.validate_property(TradingHub, Symbol("id"), o.id)
    OpenAPI.validate_property(TradingHub, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ TradingHub }, name::Symbol, val)


end
