# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OfflineReserve
A non-spinning reserve product from devices not currently synchronized with the system but able to come online quickly after an unexpected contingency. Upward only, so unlike &#x60;OnlineReserve&#x60; there is no reserve direction. The procurement requirement is static unless a &#x60;requirement&#x60; time series is attached, in which case &#x60;requirement&#x60; is the scaling factor.

    OfflineReserve(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=0.0,
        variable=nothing,
        sustained_time=60.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - time_frame::Float64 : The saturation time frame to provide reserve contribution. Units: min.
    - requirement::Float64 : The value of required reserves. Units: MW.
    - variable::CostCurve
    - sustained_time::Float64 : The time reserve contribution must be sustained at a specified level. Units: min.
    - max_output_fraction::Float64 : The maximum fraction of each device&#39;s output that can be assigned to the service.
    - max_participation_factor::Float64 : The maximum portion [0, 1.0] of the reserve that can be contributed per device.
    - deployed_fraction::Float64 : Fraction of service procurement that is assumed to be actually deployed. Most commonly, this is assumed to be either 0.0 or 1.0.
"""
Base.@kwdef mutable struct OfflineReserve <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = 0.0
    variable = nothing # spec type: Union{ Nothing, CostCurve }
    sustained_time::Union{Nothing, Float64} = 60.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0

    function OfflineReserve(id, name, available, time_frame, requirement, variable, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
        o = new(id, name, available, time_frame, requirement, variable, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type OfflineReserve

const _property_types_OfflineReserve = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("time_frame")=>"Float64", Symbol("requirement")=>"Float64", Symbol("variable")=>"CostCurve", Symbol("sustained_time")=>"Float64", Symbol("max_output_fraction")=>"Float64", Symbol("max_participation_factor")=>"Float64", Symbol("deployed_fraction")=>"Float64", )
OpenAPI.property_type(::Type{ OfflineReserve }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OfflineReserve[name]))}

function OpenAPI.check_required(o::OfflineReserve)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::OfflineReserve)
    OpenAPI.validate_property(OfflineReserve, Symbol("id"), o.id)
    OpenAPI.validate_property(OfflineReserve, Symbol("name"), o.name)
    OpenAPI.validate_property(OfflineReserve, Symbol("available"), o.available)
    OpenAPI.validate_property(OfflineReserve, Symbol("time_frame"), o.time_frame)
    OpenAPI.validate_property(OfflineReserve, Symbol("requirement"), o.requirement)
    OpenAPI.validate_property(OfflineReserve, Symbol("variable"), o.variable)
    OpenAPI.validate_property(OfflineReserve, Symbol("sustained_time"), o.sustained_time)
    OpenAPI.validate_property(OfflineReserve, Symbol("max_output_fraction"), o.max_output_fraction)
    OpenAPI.validate_property(OfflineReserve, Symbol("max_participation_factor"), o.max_participation_factor)
    OpenAPI.validate_property(OfflineReserve, Symbol("deployed_fraction"), o.deployed_fraction)
end

function OpenAPI.validate_property(::Type{ OfflineReserve }, name::Symbol, val)










end
