# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ThermalStandard
A thermal generator, such as a fossil fuel and nuclear generator.  This is a standard representation with options to include a minimum up time, minimum down time, and ramp limits. For a more detailed representation of the start-up and shut-down processes, including hot starts, see &#x60;ThermalMultiStart&#x60;.

    ThermalStandard(;
        id=nothing,
        name=nothing,
        available=nothing,
        status=nothing,
        bus=nothing,
        active_power=nothing,
        reactive_power=nothing,
        rating=nothing,
        active_power_limits=nothing,
        reactive_power_limits=nothing,
        ramp_limits=nothing,
        operation_cost=nothing,
        base_power=nothing,
        time_limits=nothing,
        must_run=false,
        prime_mover_type="OT",
        fuel="OTHER",
        time_at_status=600000.0,
        dynamic_injector=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - status::Bool : Initial commitment condition at the start of a simulation (&#x60;true&#x60; &#x3D; on or &#x60;false&#x60; &#x3D; off).
    - bus::Int64 : ID of the bus that this component is connected to.
    - active_power::Float64 : Initial active power set point of the unit. For power flow, this is the steady state operating point of the system. For production cost modeling, this may or may not be used as the initial starting point for the solver, depending on the solver used. Units: MW.
    - reactive_power::Float64 : Initial reactive power set point of the unit. Units: MVAr.
    - rating::Float64 : Maximum AC side output power rating of the unit. Not to be confused with base_power. Units: MVA.
    - active_power_limits::MinMax
    - reactive_power_limits::MinMax
    - ramp_limits::UpDown
    - operation_cost::ThermalStandardOperationCost
    - base_power::Float64 : Base power of the unit for per unitization. Must be positive; a zero base would make per-unit conversion undefined. Units: MVA.
    - time_limits::UpDown
    - must_run::Bool : Set to &#x60;true&#x60; if the unit is must run.
    - prime_mover_type::String : Prime mover technology according to EIA 923.
    - fuel::String : Prime mover fuel according to EIA 923.
    - time_at_status::Float64 : Time the generator has been on or off, as indicated by &#x60;status&#x60;. Units: min.
    - dynamic_injector::Int64 : ID of the corresponding dynamic injection device, if any.
"""
Base.@kwdef mutable struct ThermalStandard <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    status::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    reactive_power::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    active_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    ramp_limits = nothing # spec type: Union{ Nothing, UpDown }
    operation_cost = nothing # spec type: Union{ Nothing, ThermalStandardOperationCost }
    base_power::Union{Nothing, Float64} = nothing
    time_limits = nothing # spec type: Union{ Nothing, UpDown }
    must_run::Union{Nothing, Bool} = false
    prime_mover_type::Union{Nothing, String} = "OT"
    fuel::Union{Nothing, String} = "OTHER"
    time_at_status::Union{Nothing, Float64} = 600000.0
    dynamic_injector::Union{Nothing, Int64} = nothing

    function ThermalStandard(id, name, available, status, bus, active_power, reactive_power, rating, active_power_limits, reactive_power_limits, ramp_limits, operation_cost, base_power, time_limits, must_run, prime_mover_type, fuel, time_at_status, dynamic_injector, )
        o = new(id, name, available, status, bus, active_power, reactive_power, rating, active_power_limits, reactive_power_limits, ramp_limits, operation_cost, base_power, time_limits, must_run, prime_mover_type, fuel, time_at_status, dynamic_injector, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ThermalStandard

const _property_types_ThermalStandard = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("name")=>Union{Nothing, String}, Symbol("available")=>Union{Nothing, Bool}, Symbol("status")=>Union{Nothing, Bool}, Symbol("bus")=>Union{Nothing, Int64}, Symbol("active_power")=>Union{Nothing, Float64}, Symbol("reactive_power")=>Union{Nothing, Float64}, Symbol("rating")=>Union{Nothing, Float64}, Symbol("active_power_limits")=>Union{Nothing, MinMax}, Symbol("reactive_power_limits")=>Union{Nothing, MinMax}, Symbol("ramp_limits")=>Union{Nothing, UpDown}, Symbol("operation_cost")=>Union{Nothing, ThermalStandardOperationCost}, Symbol("base_power")=>Union{Nothing, Float64}, Symbol("time_limits")=>Union{Nothing, UpDown}, Symbol("must_run")=>Union{Nothing, Bool}, Symbol("prime_mover_type")=>Union{Nothing, String}, Symbol("fuel")=>Union{Nothing, String}, Symbol("time_at_status")=>Union{Nothing, Float64}, Symbol("dynamic_injector")=>Union{Nothing, Int64}, )
OpenAPI.property_type(::Type{ ThermalStandard }, name::Symbol) = _property_types_ThermalStandard[name]

function OpenAPI.check_required(o::ThermalStandard)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.status === nothing && (return false)
    o.bus === nothing && (return false)
    o.active_power === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.rating === nothing && (return false)
    o.active_power_limits === nothing && (return false)
    o.operation_cost === nothing && (return false)
    o.base_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ThermalStandard)
    OpenAPI.validate_property(ThermalStandard, Symbol("id"), o.id)
    OpenAPI.validate_property(ThermalStandard, Symbol("name"), o.name)
    OpenAPI.validate_property(ThermalStandard, Symbol("available"), o.available)
    OpenAPI.validate_property(ThermalStandard, Symbol("status"), o.status)
    OpenAPI.validate_property(ThermalStandard, Symbol("bus"), o.bus)
    OpenAPI.validate_property(ThermalStandard, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(ThermalStandard, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(ThermalStandard, Symbol("rating"), o.rating)
    OpenAPI.validate_property(ThermalStandard, Symbol("active_power_limits"), o.active_power_limits)
    OpenAPI.validate_property(ThermalStandard, Symbol("reactive_power_limits"), o.reactive_power_limits)
    OpenAPI.validate_property(ThermalStandard, Symbol("ramp_limits"), o.ramp_limits)
    OpenAPI.validate_property(ThermalStandard, Symbol("operation_cost"), o.operation_cost)
    OpenAPI.validate_property(ThermalStandard, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(ThermalStandard, Symbol("time_limits"), o.time_limits)
    OpenAPI.validate_property(ThermalStandard, Symbol("must_run"), o.must_run)
    OpenAPI.validate_property(ThermalStandard, Symbol("prime_mover_type"), o.prime_mover_type)
    OpenAPI.validate_property(ThermalStandard, Symbol("fuel"), o.fuel)
    OpenAPI.validate_property(ThermalStandard, Symbol("time_at_status"), o.time_at_status)
    OpenAPI.validate_property(ThermalStandard, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{ ThermalStandard }, name::Symbol, val)
















    if name === Symbol("prime_mover_type")
        OpenAPI.validate_param(name, "ThermalStandard", :enum, val, ["BA", "BT", "CA", "CC", "CE", "CP", "CS", "CT", "ES", "FC", "FW", "GT", "HA", "HB", "HK", "HY", "IC", "PS", "OT", "ST", "PVe", "WT", "WS"])
    end


    if name === Symbol("fuel")
        OpenAPI.validate_param(name, "ThermalStandard", :enum, val, ["ANTHRACITE_COAL", "BITUMINOUS_COAL", "LIGNITE_COAL", "SUBBITUMINOUS_COAL", "WASTE_COAL", "REFINED_COAL", "SYNTHESIS_GAS_COAL", "DISTILLATE_FUEL_OIL", "JET_FUEL", "KEROSENE", "PETROLEUM_COKE", "RESIDUAL_FUEL_OIL", "PROPANE", "SYNTHESIS_GAS_PETROLEUM_COKE", "WASTE_OIL", "BLAST_FURNACE_GAS", "NATURAL_GAS", "OTHER_GAS", "AG_BYPRODUCT", "MUNICIPAL_WASTE", "OTHER_BIOMASS_SOLIDS", "WOOD_WASTE_SOLIDS", "OTHER_BIOMASS_LIQUIDS", "SLUDGE_WASTE", "BLACK_LIQUOR", "WOOD_WASTE_LIQUIDS", "LANDFILL_GAS", "OTHER_BIOMASS_GAS", "NUCLEAR", "WASTE_HEAT", "TIRE_DERIVED_FUEL", "COAL", "GEOTHERMAL", "OTHER"])
    end



end
