# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GenericArcImpedance
A generic branch defined by a series impedance on an &#x60;Arc&#x60; between two buses.

    GenericArcImpedance(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        max_flow=nothing,
        arc=nothing,
        base_power=nothing,
        parameter_units="DEVICE_BASE",
        r=nothing,
        x=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - active_power_flow::Float64 : Initial condition of active power flow on the line. Units: MW.
    - reactive_power_flow::Float64 : Initial condition of reactive power flow on the line. Units: MVAr.
    - max_flow::Float64 : Maximum allowable flow on the generic impedance. Units: MW.
    - arc::Int64 : An &#x60;Arc&#x60; defining this line &#x60;from&#x60; a bus &#x60;to&#x60; another bus.
    - base_power::Float64 : System base power for per-unitization of this component&#39;s per-unit fields, recorded per component in lieu of a system-level table. Units: MVA.
    - parameter_units::String : Unit basis for r and x. DEVICE_BASE is per-unit on this component&#39;s base_power, which records the system base.
    - r::Float64 : Resistance. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - x::Float64 : Reactance. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
"""
Base.@kwdef mutable struct GenericArcImpedance <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    max_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    parameter_units::Union{Nothing, String} = "DEVICE_BASE"
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing

    function GenericArcImpedance(id, name, available, active_power_flow, reactive_power_flow, max_flow, arc, base_power, parameter_units, r, x, )
        o = new(id, name, available, active_power_flow, reactive_power_flow, max_flow, arc, base_power, parameter_units, r, x, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GenericArcImpedance

const _property_types_GenericArcImpedance = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("active_power_flow")=>"Float64", Symbol("reactive_power_flow")=>"Float64", Symbol("max_flow")=>"Float64", Symbol("arc")=>"Int64", Symbol("base_power")=>"Float64", Symbol("parameter_units")=>"String", Symbol("r")=>"Float64", Symbol("x")=>"Float64", )
OpenAPI.property_type(::Type{ GenericArcImpedance }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GenericArcImpedance[name]))}

function OpenAPI.check_required(o::GenericArcImpedance)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.max_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.base_power === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GenericArcImpedance)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("id"), o.id)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("name"), o.name)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("available"), o.available)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("reactive_power_flow"), o.reactive_power_flow)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("max_flow"), o.max_flow)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("arc"), o.arc)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("parameter_units"), o.parameter_units)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("r"), o.r)
    OpenAPI.validate_property(GenericArcImpedance, Symbol("x"), o.x)
end

function OpenAPI.validate_property(::Type{ GenericArcImpedance }, name::Symbol, val)









    if name === Symbol("parameter_units")
        OpenAPI.validate_param(name, "GenericArcImpedance", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end



end
