# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TwoTerminalLCCLine
A Non-Capacitor Line Commutated Converter (LCC)-HVDC transmission line. As implemented in PSS/E.

    TwoTerminalLCCLine(;
        id=nothing,
        name=nothing,
        available=nothing,
        arc=nothing,
        active_power_flow=nothing,
        parameter_units="NATURAL_UNITS",
        r=nothing,
        transfer_setpoint=nothing,
        dc_voltage_units="NATURAL_UNITS",
        scheduled_dc_voltage=nothing,
        rectifier_bridges=nothing,
        rectifier_delay_angle_limits=nothing,
        rectifier_rc=nothing,
        rectifier_xc=nothing,
        rectifier_base_voltage=nothing,
        inverter_bridges=nothing,
        inverter_extinction_angle_limits=nothing,
        inverter_rc=nothing,
        inverter_xc=nothing,
        inverter_base_voltage=nothing,
        power_mode=true,
        switch_mode_voltage=0.0,
        compounding_resistance=0.0,
        min_compounding_voltage=0.0,
        rectifier_transformer_ratio=1.0,
        rectifier_tap_setting=1.0,
        rectifier_tap_limits=nothing,
        rectifier_tap_step=0.00625,
        rectifier_delay_angle=0.0,
        rectifier_capacitor_reactance=0.0,
        inverter_transformer_ratio=1.0,
        inverter_tap_setting=1.0,
        inverter_tap_limits=nothing,
        inverter_tap_step=0.00625,
        inverter_extinction_angle=0.0,
        inverter_capacitor_reactance=0.0,
        active_power_limits_from=nothing,
        active_power_limits_to=nothing,
        reactive_power_limits_from=nothing,
        reactive_power_limits_to=nothing,
        loss=nothing,
        base_power=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - arc::Int64 : An Arc defining this line &#x60;from&#x60; a rectifier bus &#x60;to&#x60; an inverter bus. The rectifier bus must be specified in the &#x60;from&#x60; bus and inverter bus in the &#x60;to&#x60; bus.
    - active_power_flow::Float64 : Initial condition of active power flow on the line. Units: MW.
    - parameter_units::String : Unit basis for this line&#39;s impedance fields (r, rectifier/inverter rc/xc, capacitor reactances, compounding_resistance).
    - r::Float64 : Series resistance of the DC line. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - transfer_setpoint::Float64 : Desired set-point of power. If &#x60;power_mode &#x3D; true&#x60; this value is in MW units, and if &#x60;power_mode &#x3D; false&#x60; is in Amperes units. This parameter must not be specified in per-unit. A positive value represents the desired consumed power at the rectifier bus, while a negative value represents the desired power at the inverter bus (i.e. the absolute value of &#x60;transfer_setpoint&#x60; is the generated power at the inverter bus). Units: per power_mode — true: MW, false: A .
    - dc_voltage_units::String : Unit basis for the DC voltage fields (scheduled_dc_voltage, switch_mode_voltage, min_compounding_voltage).
    - scheduled_dc_voltage::Float64 : Scheduled compounded DC voltage. By default this parameter is the scheduled DC voltage in the inverter bus. This parameter must not be specified in per-unit. Units: kV. Units: per dc_voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu .
    - rectifier_bridges::Int64 : Number of bridges in series in the rectifier side.
    - rectifier_delay_angle_limits::MinMax
    - rectifier_rc::Float64 : Rectifier commutating transformer resistance per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - rectifier_xc::Float64 : Rectifier commutating transformer reactance per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - rectifier_base_voltage::Float64 : Rectifier primary base AC voltage, entered in kV. Units: kV.
    - inverter_bridges::Int64 : Number of bridges in series in the inverter side.
    - inverter_extinction_angle_limits::MinMax
    - inverter_rc::Float64 : Inverter commutating transformer resistance per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - inverter_xc::Float64 : Inverter commutating transformer reactance per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - inverter_base_voltage::Float64 : Inverter primary base AC voltage, entered in kV. Units: kV.
    - power_mode::Bool : Boolean flag to identify if the LCC line is in power mode or current mode. If &#x60;power_mode &#x3D; true&#x60;, setpoint values must be specified in MW, and if &#x60;power_mode &#x3D; false&#x60; setpoint values must be specified in Amperes.
    - switch_mode_voltage::Float64 : Mode switch DC voltage. This parameter must not be added in per-unit. If LCC line is in power mode control, and DC voltage falls below this value, the line switch to current mode control. Units: kV. Units: per dc_voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu .
    - compounding_resistance::Float64 : Compounding Resistance. This parameter is for control of the DC voltage in the rectifier or inverter end. For inverter DC voltage control, the parameter is set to zero; for rectifier DC voltage control, the parameter is set to the DC line resistance; otherwise, set to a fraction of the DC line resistance. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - min_compounding_voltage::Float64 : Minimum compounded voltage. This parameter must not be added in per-unit. Only used in constant gamma operation (gamma_min &#x3D; gamma_max), and the AC transformer is used to control the DC voltage. Units: kV. Units: per dc_voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu .
    - rectifier_transformer_ratio::Float64 : Rectifier transformer ratio between the primary and secondary side AC voltages. Units: 1.
    - rectifier_tap_setting::Float64 : Rectifier transformer tap setting. Units: 1.
    - rectifier_tap_limits::MinMax
    - rectifier_tap_step::Float64 : Rectifier transformer tap step value. Units: 1.
    - rectifier_delay_angle::Float64 : Rectifier firing delay angle (alpha). Units: rad.
    - rectifier_capacitor_reactance::Float64 : Commutating rectifier capacitor reactance magnitude per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - inverter_transformer_ratio::Float64 : Inverter transformer ratio between the primary and secondary side AC voltages. Units: 1.
    - inverter_tap_setting::Float64 : Inverter transformer tap setting. Units: 1.
    - inverter_tap_limits::MinMax
    - inverter_tap_step::Float64 : Inverter transformer tap step value. Units: 1.
    - inverter_extinction_angle::Float64 : Inverter extinction angle (gamma). Units: rad.
    - inverter_capacitor_reactance::Float64 : Commutating inverter capacitor reactance magnitude per bridge. Units: per parameter_units — NATURAL_UNITS: ohm, DEVICE_BASE: pu .
    - active_power_limits_from::MinMax
    - active_power_limits_to::MinMax
    - reactive_power_limits_from::MinMax
    - reactive_power_limits_to::MinMax
    - loss::TwoTerminalLoss
    - base_power::Float64 : System base power for per-unitization of this component&#39;s per-unit fields, recorded per component in lieu of a system-level table. Units: MVA.
"""
Base.@kwdef mutable struct TwoTerminalLCCLine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    arc::Union{Nothing, Int64} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    parameter_units::Union{Nothing, String} = "NATURAL_UNITS"
    r::Union{Nothing, Float64} = nothing
    transfer_setpoint::Union{Nothing, Float64} = nothing
    dc_voltage_units::Union{Nothing, String} = "NATURAL_UNITS"
    scheduled_dc_voltage::Union{Nothing, Float64} = nothing
    rectifier_bridges::Union{Nothing, Int64} = nothing
    rectifier_delay_angle_limits = nothing # spec type: Union{ Nothing, MinMax }
    rectifier_rc::Union{Nothing, Float64} = nothing
    rectifier_xc::Union{Nothing, Float64} = nothing
    rectifier_base_voltage::Union{Nothing, Float64} = nothing
    inverter_bridges::Union{Nothing, Int64} = nothing
    inverter_extinction_angle_limits = nothing # spec type: Union{ Nothing, MinMax }
    inverter_rc::Union{Nothing, Float64} = nothing
    inverter_xc::Union{Nothing, Float64} = nothing
    inverter_base_voltage::Union{Nothing, Float64} = nothing
    power_mode::Union{Nothing, Bool} = true
    switch_mode_voltage::Union{Nothing, Float64} = 0.0
    compounding_resistance::Union{Nothing, Float64} = 0.0
    min_compounding_voltage::Union{Nothing, Float64} = 0.0
    rectifier_transformer_ratio::Union{Nothing, Float64} = 1.0
    rectifier_tap_setting::Union{Nothing, Float64} = 1.0
    rectifier_tap_limits = nothing # spec type: Union{ Nothing, MinMax }
    rectifier_tap_step::Union{Nothing, Float64} = 0.00625
    rectifier_delay_angle::Union{Nothing, Float64} = 0.0
    rectifier_capacitor_reactance::Union{Nothing, Float64} = 0.0
    inverter_transformer_ratio::Union{Nothing, Float64} = 1.0
    inverter_tap_setting::Union{Nothing, Float64} = 1.0
    inverter_tap_limits = nothing # spec type: Union{ Nothing, MinMax }
    inverter_tap_step::Union{Nothing, Float64} = 0.00625
    inverter_extinction_angle::Union{Nothing, Float64} = 0.0
    inverter_capacitor_reactance::Union{Nothing, Float64} = 0.0
    active_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    active_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    loss = nothing # spec type: Union{ Nothing, TwoTerminalLoss }
    base_power::Union{Nothing, Float64} = nothing

    function TwoTerminalLCCLine(id, name, available, arc, active_power_flow, parameter_units, r, transfer_setpoint, dc_voltage_units, scheduled_dc_voltage, rectifier_bridges, rectifier_delay_angle_limits, rectifier_rc, rectifier_xc, rectifier_base_voltage, inverter_bridges, inverter_extinction_angle_limits, inverter_rc, inverter_xc, inverter_base_voltage, power_mode, switch_mode_voltage, compounding_resistance, min_compounding_voltage, rectifier_transformer_ratio, rectifier_tap_setting, rectifier_tap_limits, rectifier_tap_step, rectifier_delay_angle, rectifier_capacitor_reactance, inverter_transformer_ratio, inverter_tap_setting, inverter_tap_limits, inverter_tap_step, inverter_extinction_angle, inverter_capacitor_reactance, active_power_limits_from, active_power_limits_to, reactive_power_limits_from, reactive_power_limits_to, loss, base_power, )
        o = new(id, name, available, arc, active_power_flow, parameter_units, r, transfer_setpoint, dc_voltage_units, scheduled_dc_voltage, rectifier_bridges, rectifier_delay_angle_limits, rectifier_rc, rectifier_xc, rectifier_base_voltage, inverter_bridges, inverter_extinction_angle_limits, inverter_rc, inverter_xc, inverter_base_voltage, power_mode, switch_mode_voltage, compounding_resistance, min_compounding_voltage, rectifier_transformer_ratio, rectifier_tap_setting, rectifier_tap_limits, rectifier_tap_step, rectifier_delay_angle, rectifier_capacitor_reactance, inverter_transformer_ratio, inverter_tap_setting, inverter_tap_limits, inverter_tap_step, inverter_extinction_angle, inverter_capacitor_reactance, active_power_limits_from, active_power_limits_to, reactive_power_limits_from, reactive_power_limits_to, loss, base_power, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TwoTerminalLCCLine

const _property_types_TwoTerminalLCCLine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("arc")=>"Int64", Symbol("active_power_flow")=>"Float64", Symbol("parameter_units")=>"String", Symbol("r")=>"Float64", Symbol("transfer_setpoint")=>"Float64", Symbol("dc_voltage_units")=>"String", Symbol("scheduled_dc_voltage")=>"Float64", Symbol("rectifier_bridges")=>"Int64", Symbol("rectifier_delay_angle_limits")=>"MinMax", Symbol("rectifier_rc")=>"Float64", Symbol("rectifier_xc")=>"Float64", Symbol("rectifier_base_voltage")=>"Float64", Symbol("inverter_bridges")=>"Int64", Symbol("inverter_extinction_angle_limits")=>"MinMax", Symbol("inverter_rc")=>"Float64", Symbol("inverter_xc")=>"Float64", Symbol("inverter_base_voltage")=>"Float64", Symbol("power_mode")=>"Bool", Symbol("switch_mode_voltage")=>"Float64", Symbol("compounding_resistance")=>"Float64", Symbol("min_compounding_voltage")=>"Float64", Symbol("rectifier_transformer_ratio")=>"Float64", Symbol("rectifier_tap_setting")=>"Float64", Symbol("rectifier_tap_limits")=>"MinMax", Symbol("rectifier_tap_step")=>"Float64", Symbol("rectifier_delay_angle")=>"Float64", Symbol("rectifier_capacitor_reactance")=>"Float64", Symbol("inverter_transformer_ratio")=>"Float64", Symbol("inverter_tap_setting")=>"Float64", Symbol("inverter_tap_limits")=>"MinMax", Symbol("inverter_tap_step")=>"Float64", Symbol("inverter_extinction_angle")=>"Float64", Symbol("inverter_capacitor_reactance")=>"Float64", Symbol("active_power_limits_from")=>"MinMax", Symbol("active_power_limits_to")=>"MinMax", Symbol("reactive_power_limits_from")=>"MinMax", Symbol("reactive_power_limits_to")=>"MinMax", Symbol("loss")=>"TwoTerminalLoss", Symbol("base_power")=>"Float64", )
OpenAPI.property_type(::Type{ TwoTerminalLCCLine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TwoTerminalLCCLine[name]))}

function OpenAPI.check_required(o::TwoTerminalLCCLine)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.arc === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.r === nothing && (return false)
    o.transfer_setpoint === nothing && (return false)
    o.scheduled_dc_voltage === nothing && (return false)
    o.rectifier_bridges === nothing && (return false)
    o.rectifier_delay_angle_limits === nothing && (return false)
    o.rectifier_rc === nothing && (return false)
    o.rectifier_xc === nothing && (return false)
    o.rectifier_base_voltage === nothing && (return false)
    o.inverter_bridges === nothing && (return false)
    o.inverter_extinction_angle_limits === nothing && (return false)
    o.inverter_rc === nothing && (return false)
    o.inverter_xc === nothing && (return false)
    o.inverter_base_voltage === nothing && (return false)
    o.base_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TwoTerminalLCCLine)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("id"), o.id)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("name"), o.name)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("available"), o.available)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("arc"), o.arc)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("parameter_units"), o.parameter_units)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("r"), o.r)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("transfer_setpoint"), o.transfer_setpoint)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("dc_voltage_units"), o.dc_voltage_units)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("scheduled_dc_voltage"), o.scheduled_dc_voltage)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_bridges"), o.rectifier_bridges)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_delay_angle_limits"), o.rectifier_delay_angle_limits)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_rc"), o.rectifier_rc)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_xc"), o.rectifier_xc)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_base_voltage"), o.rectifier_base_voltage)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_bridges"), o.inverter_bridges)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_extinction_angle_limits"), o.inverter_extinction_angle_limits)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_rc"), o.inverter_rc)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_xc"), o.inverter_xc)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_base_voltage"), o.inverter_base_voltage)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("power_mode"), o.power_mode)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("switch_mode_voltage"), o.switch_mode_voltage)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("compounding_resistance"), o.compounding_resistance)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("min_compounding_voltage"), o.min_compounding_voltage)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_transformer_ratio"), o.rectifier_transformer_ratio)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_tap_setting"), o.rectifier_tap_setting)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_tap_limits"), o.rectifier_tap_limits)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_tap_step"), o.rectifier_tap_step)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_delay_angle"), o.rectifier_delay_angle)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("rectifier_capacitor_reactance"), o.rectifier_capacitor_reactance)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_transformer_ratio"), o.inverter_transformer_ratio)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_tap_setting"), o.inverter_tap_setting)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_tap_limits"), o.inverter_tap_limits)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_tap_step"), o.inverter_tap_step)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_extinction_angle"), o.inverter_extinction_angle)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("inverter_capacitor_reactance"), o.inverter_capacitor_reactance)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("active_power_limits_from"), o.active_power_limits_from)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("active_power_limits_to"), o.active_power_limits_to)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("reactive_power_limits_from"), o.reactive_power_limits_from)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("reactive_power_limits_to"), o.reactive_power_limits_to)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("loss"), o.loss)
    OpenAPI.validate_property(TwoTerminalLCCLine, Symbol("base_power"), o.base_power)
end

function OpenAPI.validate_property(::Type{ TwoTerminalLCCLine }, name::Symbol, val)






    if name === Symbol("parameter_units")
        OpenAPI.validate_param(name, "TwoTerminalLCCLine", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end




    if name === Symbol("dc_voltage_units")
        OpenAPI.validate_param(name, "TwoTerminalLCCLine", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end


































end
