# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TwoTerminalVSCLine
A High Voltage Voltage-Source Converter DC line, which must be connected to an ACBus on each end. This model is appropriate for operational simulations with a linearized DC power flow approximation with losses using a voltage-current model. For modeling a DC network, see TModelHVDCLine.

    TwoTerminalVSCLine(;
        id=nothing,
        name=nothing,
        available=nothing,
        arc=nothing,
        active_power_flow=nothing,
        rating=nothing,
        active_power_limits_from=nothing,
        active_power_limits_to=nothing,
        admittance_units="NATURAL_UNITS",
        g=0.0,
        dc_current=0.0,
        reactive_power_from=0.0,
        dc_control_from="DC_VOLTAGE",
        ac_control_from="AC_VOLTAGE",
        dc_setpoint_from=0.0,
        ac_setpoint_from=1.0,
        converter_loss_from=nothing,
        max_dc_current_from=100000000,
        rating_from=100000000,
        reactive_power_limits_from=nothing,
        power_factor_weighting_fraction_from=1.0,
        voltage_units="NATURAL_UNITS",
        voltage_limits_from=nothing,
        dc_voltage_droop_from=0.0,
        reactive_power_to=0.0,
        dc_control_to="DC_VOLTAGE",
        ac_control_to="AC_VOLTAGE",
        dc_setpoint_to=0.0,
        ac_setpoint_to=1.0,
        converter_loss_to=nothing,
        max_dc_current_to=100000000,
        rating_to=100000000,
        reactive_power_limits_to=nothing,
        power_factor_weighting_fraction_to=1.0,
        voltage_limits_to=nothing,
        dc_voltage_droop_to=0.0,
        rated_dc_voltage=0.0,
        remote_bus_control_from=nothing,
        remote_bus_control_to=nothing,
        rmpct_from=100.0,
        rmpct_to=100.0,
        base_power=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - arc::Int64 : An Arc defining this line &#x60;from&#x60; a bus &#x60;to&#x60; another bus.
    - active_power_flow::Float64 : Initial condition of active power flowing from the from-bus to the to-bus in DC. Units: MW.
    - rating::Float64 : Maximum output power rating of the converter. Units: MVA.
    - active_power_limits_from::MinMax
    - active_power_limits_to::MinMax
    - admittance_units::String : Unit basis for the series conductance g.
    - g::Float64 : Series conductance of the DC line. Units: per admittance_units — NATURAL_UNITS: S, DEVICE_MVAR: MW, DEVICE_BASE: pu .
    - dc_current::Float64 : DC current on the converter flowing in the DC line, from &#x60;from&#x60; bus to &#x60;to&#x60; bus. Units: A.
    - reactive_power_from::Float64 : Initial condition of reactive power flowing into the from-bus. Units: MVAr.
    - dc_control_from::String : DC-side control mode of the &#x60;from&#x60; converter.
    - ac_control_from::String : AC-side control mode of the &#x60;from&#x60; converter.
    - dc_setpoint_from::Float64 : Converter DC setpoint in the &#x60;from&#x60; bus converter. When &#x60;dc_control_from&#x60; regulates DC voltage this number is the DC voltage on the DC side of the converter; when it controls DC power this value is the power demand in MW, if positive the converter is supplying power to the AC network at the &#x60;from&#x60; bus; if negative, the converter is withdrawing power from the AC network at the &#x60;from&#x60; bus. Units: per dc_control_from — DC_POWER: MW, DC_VOLTAGE: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu), DC_VOLTAGE_DROOP: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu) .
    - ac_setpoint_from::Float64 : Converter AC setpoint in the &#x60;from&#x60; bus converter. When &#x60;ac_control_from&#x60; regulates AC voltage this number is the AC voltage on the AC side of the converter; when it controls reactive power this value is the power factor setpoint. Units: per ac_control_from — AC_REACTIVE_POWER: 1, AC_VOLTAGE: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu) .
    - converter_loss_from::InputOutputCurve
    - max_dc_current_from::Float64 : Maximum stable dc current limits. Units: A.
    - rating_from::Float64 : Converter rating in the &#x60;from&#x60; bus. Units: MVA.
    - reactive_power_limits_from::MinMax
    - power_factor_weighting_fraction_from::Float64 : Power weighting factor fraction used in reducing the active power order and either the reactive power order when the converter rating is violated. When is 0.0, only the active power is reduced; when is 1.0, only the reactive power is reduced; otherwise, a weighted reduction of both active and reactive power is applied. Units: 1.
    - voltage_units::String : Unit basis for the DC bus voltage limits.
    - voltage_limits_from::MinMax
    - dc_voltage_droop_from::Float64 : DC-voltage droop gain on the &#x60;from&#x60; converter, used when &#x60;dc_control_from&#x60; is &#x60;DC_VOLTAGE_DROOP&#x60;: &#x60;V_dc &#x3D; dc_setpoint_from - dc_voltage_droop_from * P_c&#x60;. Units: pu.
    - reactive_power_to::Float64 : Initial condition of reactive power flowing into the to-bus. Units: MVAr.
    - dc_control_to::String : DC-side control mode of the &#x60;to&#x60; converter.
    - ac_control_to::String : AC-side control mode of the &#x60;to&#x60; converter.
    - dc_setpoint_to::Float64 : Converter DC setpoint in the &#x60;to&#x60; bus converter. When &#x60;dc_control_to&#x60; regulates DC voltage this number is the DC voltage on the DC side of the converter; when it controls DC power this value is the power demand in MW, if positive the converter is supplying power to the AC network at the &#x60;to&#x60; bus; if negative, the converter is withdrawing power from the AC network at the &#x60;to&#x60; bus. Units: per dc_control_to — DC_POWER: MW, DC_VOLTAGE: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu), DC_VOLTAGE_DROOP: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu) .
    - ac_setpoint_to::Float64 : Converter AC setpoint in the &#x60;to&#x60; bus converter. When &#x60;ac_control_to&#x60; regulates AC voltage this number is the AC voltage on the AC side of the converter; when it controls reactive power this value is the power factor setpoint. Units: per ac_control_to — AC_REACTIVE_POWER: 1, AC_VOLTAGE: (per voltage_units — NATURAL_UNITS: kV, DEVICE_BASE: pu) .
    - converter_loss_to::InputOutputCurve
    - max_dc_current_to::Float64 : Maximum stable dc current limits. Units: A.
    - rating_to::Float64 : Converter rating in the &#x60;to&#x60; bus. Units: MVA.
    - reactive_power_limits_to::MinMax
    - power_factor_weighting_fraction_to::Float64 : Power weighting factor fraction used in reducing the active power order and either the reactive power order when the converter rating is violated. When is 0.0, only the active power is reduced; when is 1.0, only the reactive power is reduced; otherwise, a weighted reduction of both active and reactive power is applied. Units: 1.
    - voltage_limits_to::MinMax
    - dc_voltage_droop_to::Float64 : DC-voltage droop gain on the &#x60;to&#x60; converter, used when &#x60;dc_control_to&#x60; is &#x60;DC_VOLTAGE_DROOP&#x60;: &#x60;V_dc &#x3D; dc_setpoint_to - dc_voltage_droop_to * P_c&#x60;. Units: pu.
    - rated_dc_voltage::Float64 : Rated (base) DC voltage of the link in kV. Used as the DC voltage base for interpreting DC-voltage setpoints; 0.0 means unspecified (DC-voltage setpoints are taken as per-unit directly). Units: kV.
    - remote_bus_control_from::Int64 : Number of the AC bus whose voltage the &#x60;from&#x60; converter regulates when &#x60;ac_control_from&#x60; is &#x60;AC_VOLTAGE&#x60;; null regulates its own terminal bus.
    - remote_bus_control_to::Int64 : Number of the AC bus whose voltage the &#x60;to&#x60; converter regulates when &#x60;ac_control_to&#x60; is &#x60;AC_VOLTAGE&#x60;; null regulates its own terminal bus.
    - rmpct_from::Float64 : Percent of the total Mvar required to hold the voltage at the bus regulated by the &#x60;from&#x60; converter that is contributed by this converter. Units: 1.
    - rmpct_to::Float64 : Percent of the total Mvar required to hold the voltage at the bus regulated by the &#x60;to&#x60; converter that is contributed by this converter. Units: 1.
    - base_power::Float64 : System base power for per-unitization of this component&#39;s per-unit fields, recorded per component in lieu of a system-level table. Units: MVA.
"""
Base.@kwdef mutable struct TwoTerminalVSCLine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    arc::Union{Nothing, Int64} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    active_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    active_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    admittance_units::Union{Nothing, String} = "NATURAL_UNITS"
    g::Union{Nothing, Float64} = 0.0
    dc_current::Union{Nothing, Float64} = 0.0
    reactive_power_from::Union{Nothing, Float64} = 0.0
    dc_control_from::Union{Nothing, String} = "DC_VOLTAGE"
    ac_control_from::Union{Nothing, String} = "AC_VOLTAGE"
    dc_setpoint_from::Union{Nothing, Float64} = 0.0
    ac_setpoint_from::Union{Nothing, Float64} = 1.0
    converter_loss_from = nothing # spec type: Union{ Nothing, InputOutputCurve }
    max_dc_current_from::Union{Nothing, Float64} = 100000000
    rating_from::Union{Nothing, Float64} = 100000000
    reactive_power_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    power_factor_weighting_fraction_from::Union{Nothing, Float64} = 1.0
    voltage_units::Union{Nothing, String} = "NATURAL_UNITS"
    voltage_limits_from = nothing # spec type: Union{ Nothing, MinMax }
    dc_voltage_droop_from::Union{Nothing, Float64} = 0.0
    reactive_power_to::Union{Nothing, Float64} = 0.0
    dc_control_to::Union{Nothing, String} = "DC_VOLTAGE"
    ac_control_to::Union{Nothing, String} = "AC_VOLTAGE"
    dc_setpoint_to::Union{Nothing, Float64} = 0.0
    ac_setpoint_to::Union{Nothing, Float64} = 1.0
    converter_loss_to = nothing # spec type: Union{ Nothing, InputOutputCurve }
    max_dc_current_to::Union{Nothing, Float64} = 100000000
    rating_to::Union{Nothing, Float64} = 100000000
    reactive_power_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    power_factor_weighting_fraction_to::Union{Nothing, Float64} = 1.0
    voltage_limits_to = nothing # spec type: Union{ Nothing, MinMax }
    dc_voltage_droop_to::Union{Nothing, Float64} = 0.0
    rated_dc_voltage::Union{Nothing, Float64} = 0.0
    remote_bus_control_from::Union{Nothing, Int64} = nothing
    remote_bus_control_to::Union{Nothing, Int64} = nothing
    rmpct_from::Union{Nothing, Float64} = 100.0
    rmpct_to::Union{Nothing, Float64} = 100.0
    base_power::Union{Nothing, Float64} = nothing

    function TwoTerminalVSCLine(id, name, available, arc, active_power_flow, rating, active_power_limits_from, active_power_limits_to, admittance_units, g, dc_current, reactive_power_from, dc_control_from, ac_control_from, dc_setpoint_from, ac_setpoint_from, converter_loss_from, max_dc_current_from, rating_from, reactive_power_limits_from, power_factor_weighting_fraction_from, voltage_units, voltage_limits_from, dc_voltage_droop_from, reactive_power_to, dc_control_to, ac_control_to, dc_setpoint_to, ac_setpoint_to, converter_loss_to, max_dc_current_to, rating_to, reactive_power_limits_to, power_factor_weighting_fraction_to, voltage_limits_to, dc_voltage_droop_to, rated_dc_voltage, remote_bus_control_from, remote_bus_control_to, rmpct_from, rmpct_to, base_power, )
        o = new(id, name, available, arc, active_power_flow, rating, active_power_limits_from, active_power_limits_to, admittance_units, g, dc_current, reactive_power_from, dc_control_from, ac_control_from, dc_setpoint_from, ac_setpoint_from, converter_loss_from, max_dc_current_from, rating_from, reactive_power_limits_from, power_factor_weighting_fraction_from, voltage_units, voltage_limits_from, dc_voltage_droop_from, reactive_power_to, dc_control_to, ac_control_to, dc_setpoint_to, ac_setpoint_to, converter_loss_to, max_dc_current_to, rating_to, reactive_power_limits_to, power_factor_weighting_fraction_to, voltage_limits_to, dc_voltage_droop_to, rated_dc_voltage, remote_bus_control_from, remote_bus_control_to, rmpct_from, rmpct_to, base_power, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TwoTerminalVSCLine

const _property_types_TwoTerminalVSCLine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("arc")=>"Int64", Symbol("active_power_flow")=>"Float64", Symbol("rating")=>"Float64", Symbol("active_power_limits_from")=>"MinMax", Symbol("active_power_limits_to")=>"MinMax", Symbol("admittance_units")=>"String", Symbol("g")=>"Float64", Symbol("dc_current")=>"Float64", Symbol("reactive_power_from")=>"Float64", Symbol("dc_control_from")=>"String", Symbol("ac_control_from")=>"String", Symbol("dc_setpoint_from")=>"Float64", Symbol("ac_setpoint_from")=>"Float64", Symbol("converter_loss_from")=>"InputOutputCurve", Symbol("max_dc_current_from")=>"Float64", Symbol("rating_from")=>"Float64", Symbol("reactive_power_limits_from")=>"MinMax", Symbol("power_factor_weighting_fraction_from")=>"Float64", Symbol("voltage_units")=>"String", Symbol("voltage_limits_from")=>"MinMax", Symbol("dc_voltage_droop_from")=>"Float64", Symbol("reactive_power_to")=>"Float64", Symbol("dc_control_to")=>"String", Symbol("ac_control_to")=>"String", Symbol("dc_setpoint_to")=>"Float64", Symbol("ac_setpoint_to")=>"Float64", Symbol("converter_loss_to")=>"InputOutputCurve", Symbol("max_dc_current_to")=>"Float64", Symbol("rating_to")=>"Float64", Symbol("reactive_power_limits_to")=>"MinMax", Symbol("power_factor_weighting_fraction_to")=>"Float64", Symbol("voltage_limits_to")=>"MinMax", Symbol("dc_voltage_droop_to")=>"Float64", Symbol("rated_dc_voltage")=>"Float64", Symbol("remote_bus_control_from")=>"Int64", Symbol("remote_bus_control_to")=>"Int64", Symbol("rmpct_from")=>"Float64", Symbol("rmpct_to")=>"Float64", Symbol("base_power")=>"Float64", )
OpenAPI.property_type(::Type{ TwoTerminalVSCLine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TwoTerminalVSCLine[name]))}

function OpenAPI.check_required(o::TwoTerminalVSCLine)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.arc === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.rating === nothing && (return false)
    o.active_power_limits_from === nothing && (return false)
    o.active_power_limits_to === nothing && (return false)
    o.base_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TwoTerminalVSCLine)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("id"), o.id)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("name"), o.name)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("available"), o.available)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("arc"), o.arc)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rating"), o.rating)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("active_power_limits_from"), o.active_power_limits_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("active_power_limits_to"), o.active_power_limits_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("admittance_units"), o.admittance_units)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("g"), o.g)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_current"), o.dc_current)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("reactive_power_from"), o.reactive_power_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_control_from"), o.dc_control_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("ac_control_from"), o.ac_control_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_setpoint_from"), o.dc_setpoint_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("ac_setpoint_from"), o.ac_setpoint_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("converter_loss_from"), o.converter_loss_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("max_dc_current_from"), o.max_dc_current_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rating_from"), o.rating_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("reactive_power_limits_from"), o.reactive_power_limits_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("power_factor_weighting_fraction_from"), o.power_factor_weighting_fraction_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("voltage_units"), o.voltage_units)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("voltage_limits_from"), o.voltage_limits_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_voltage_droop_from"), o.dc_voltage_droop_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("reactive_power_to"), o.reactive_power_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_control_to"), o.dc_control_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("ac_control_to"), o.ac_control_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_setpoint_to"), o.dc_setpoint_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("ac_setpoint_to"), o.ac_setpoint_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("converter_loss_to"), o.converter_loss_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("max_dc_current_to"), o.max_dc_current_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rating_to"), o.rating_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("reactive_power_limits_to"), o.reactive_power_limits_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("power_factor_weighting_fraction_to"), o.power_factor_weighting_fraction_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("voltage_limits_to"), o.voltage_limits_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("dc_voltage_droop_to"), o.dc_voltage_droop_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rated_dc_voltage"), o.rated_dc_voltage)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("remote_bus_control_from"), o.remote_bus_control_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("remote_bus_control_to"), o.remote_bus_control_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rmpct_from"), o.rmpct_from)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("rmpct_to"), o.rmpct_to)
    OpenAPI.validate_property(TwoTerminalVSCLine, Symbol("base_power"), o.base_power)
end

function OpenAPI.validate_property(::Type{ TwoTerminalVSCLine }, name::Symbol, val)









    if name === Symbol("admittance_units")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["NATURAL_UNITS", "DEVICE_MVAR", "DEVICE_BASE"])
    end





    if name === Symbol("dc_control_from")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["DC_POWER", "DC_VOLTAGE", "DC_VOLTAGE_DROOP"])
    end


    if name === Symbol("ac_control_from")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["AC_REACTIVE_POWER", "AC_VOLTAGE"])
    end









    if name === Symbol("voltage_units")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["NATURAL_UNITS", "DEVICE_BASE"])
    end





    if name === Symbol("dc_control_to")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["DC_POWER", "DC_VOLTAGE", "DC_VOLTAGE_DROOP"])
    end


    if name === Symbol("ac_control_to")
        OpenAPI.validate_param(name, "TwoTerminalVSCLine", :enum, val, ["AC_REACTIVE_POWER", "AC_VOLTAGE"])
    end
















end
