# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EmissionsData
Supplemental attribute describing the emission of a single pollutant from a host component. Combines pollutant identity (CO2, NOx, etc.) with an emission rate expressed as a ValueCurve (supporting constant, linear, or piecewise relationships between fuel consumption / power output and emissions). One EmissionsData instance can be attached to one or many components.

    EmissionsData(;
        id=nothing,
        name=nothing,
        pollutant=nothing,
        emission_rate=nothing,
        basis=nothing,
        start_up_adder=0.0,
        mass_unit="KG",
        energy_unit=nothing,
        gwp=1.0,
        available=true,
    )

    - id::Int64
    - name::String : Identifier for this emissions attribute
    - pollutant::String : Pollutant identity (CO2, CO2E, CH4, N2O, NOX, SO2, PM25, PM10, HG, HAP, CUSTOM)
    - emission_rate::ValueCurve
    - basis::String : FUEL_INPUT (mass per unit of heat input) or POWER_OUTPUT (mass per unit of electrical output)
    - start_up_adder::Float64 : Per-start emission pulse, in mass_unit. Must be finite and non-negative. Units: per mass_unit — KG: kg, LB: lb, SHORT_TON: ston, METRIC_TON: t .
    - mass_unit::String : Mass unit of the emission rate numerator
    - energy_unit::String : Energy unit for the rate denominator. Must be MMBTU or GJ when basis is FUEL_INPUT, and MWH when basis is POWER_OUTPUT.
    - gwp::Float64 : GWP100 multiplier for CO2-equivalent reporting. Must be finite and non-negative. Units: 1.
    - available::Bool : Whether this attribute is active
"""
Base.@kwdef mutable struct EmissionsData <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    pollutant::Union{Nothing, String} = nothing
    emission_rate = nothing # spec type: Union{ Nothing, ValueCurve }
    basis::Union{Nothing, String} = nothing
    start_up_adder::Union{Nothing, Float64} = 0.0
    mass_unit::Union{Nothing, String} = "KG"
    energy_unit::Union{Nothing, String} = nothing
    gwp::Union{Nothing, Float64} = 1.0
    available::Union{Nothing, Bool} = true

    function EmissionsData(id, name, pollutant, emission_rate, basis, start_up_adder, mass_unit, energy_unit, gwp, available, )
        o = new(id, name, pollutant, emission_rate, basis, start_up_adder, mass_unit, energy_unit, gwp, available, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EmissionsData

const _property_types_EmissionsData = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("pollutant")=>"String", Symbol("emission_rate")=>"ValueCurve", Symbol("basis")=>"String", Symbol("start_up_adder")=>"Float64", Symbol("mass_unit")=>"String", Symbol("energy_unit")=>"String", Symbol("gwp")=>"Float64", Symbol("available")=>"Bool", )
OpenAPI.property_type(::Type{ EmissionsData }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EmissionsData[name]))}

function OpenAPI.check_required(o::EmissionsData)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.pollutant === nothing && (return false)
    o.emission_rate === nothing && (return false)
    o.basis === nothing && (return false)
    o.energy_unit === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EmissionsData)
    OpenAPI.validate_property(EmissionsData, Symbol("id"), o.id)
    OpenAPI.validate_property(EmissionsData, Symbol("name"), o.name)
    OpenAPI.validate_property(EmissionsData, Symbol("pollutant"), o.pollutant)
    OpenAPI.validate_property(EmissionsData, Symbol("emission_rate"), o.emission_rate)
    OpenAPI.validate_property(EmissionsData, Symbol("basis"), o.basis)
    OpenAPI.validate_property(EmissionsData, Symbol("start_up_adder"), o.start_up_adder)
    OpenAPI.validate_property(EmissionsData, Symbol("mass_unit"), o.mass_unit)
    OpenAPI.validate_property(EmissionsData, Symbol("energy_unit"), o.energy_unit)
    OpenAPI.validate_property(EmissionsData, Symbol("gwp"), o.gwp)
    OpenAPI.validate_property(EmissionsData, Symbol("available"), o.available)
end

function OpenAPI.validate_property(::Type{ EmissionsData }, name::Symbol, val)



    if name === Symbol("pollutant")
        OpenAPI.validate_param(name, "EmissionsData", :enum, val, ["CO2", "CO2E", "CH4", "N2O", "NOX", "SO2", "PM25", "PM10", "HG", "HAP", "CUSTOM"])
    end



    if name === Symbol("basis")
        OpenAPI.validate_param(name, "EmissionsData", :enum, val, ["FUEL_INPUT", "POWER_OUTPUT"])
    end



    if name === Symbol("mass_unit")
        OpenAPI.validate_param(name, "EmissionsData", :enum, val, ["KG", "LB", "SHORT_TON", "METRIC_TON"])
    end


    if name === Symbol("energy_unit")
        OpenAPI.validate_param(name, "EmissionsData", :enum, val, ["MMBTU", "GJ", "MWH"])
    end



end
