# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Line
An AC transmission line.

    Line(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        base_power=nothing,
        power_units=nothing,
        parameter_units="COMPONENT_BASE",
        b=nothing,
        rating=nothing,
        rating_b=nothing,
        rating_c=nothing,
        angle_limits=nothing,
        g=FromTo(; from=0.0, to=0.0),
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - active_power_flow::Float64 : Initial condition of active power flow on the line. Units: per power_units — NATURAL_UNITS: MW, COMPONENT_BASE: pu .
    - reactive_power_flow::Float64 : Initial condition of reactive power flow on the line. Units: per power_units — NATURAL_UNITS: MVAr, COMPONENT_BASE: pu .
    - arc::Int64 : An &#x60;Arc&#x60; defining this line &#x60;from&#x60; a bus &#x60;to&#x60; another bus.
    - r::Float64 : Resistance. Units: per parameter_units — NATURAL_UNITS: ohm, COMPONENT_BASE: pu .
    - x::Float64 : Reactance. Units: per parameter_units — NATURAL_UNITS: ohm, COMPONENT_BASE: pu .
    - base_power::Float64 : System base power for per-unitization of this component&#39;s per-unit fields, recorded per component in lieu of a system-level table. Units: MVA.
    - power_units::String : Unit basis for this component&#39;s power-family fields (active/reactive/apparent power, ratings, limits, ramp rates). COMPONENT_BASE: per unit on this component&#39;s own base_power. NATURAL_UNITS: the field&#39;s physical unit.
    - parameter_units::String : Unit basis for this line&#39;s impedance and shunt admittance fields (r, x, b, g).
    - b::FromTo
    - rating::Float64 : Thermal rating. Flow on the line must be between -&#x60;rating&#x60; and &#x60;rating&#x60;. Units: per power_units — NATURAL_UNITS: MVA, COMPONENT_BASE: pu .
    - rating_b::Float64 : Second current rating. Units: per power_units — NATURAL_UNITS: MVA, COMPONENT_BASE: pu .
    - rating_c::Float64 : Third current rating. Units: per power_units — NATURAL_UNITS: MVA, COMPONENT_BASE: pu .
    - angle_limits::MinMax
    - g::FromTo
"""
Base.@kwdef mutable struct Line <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    power_units::Union{Nothing, String} = nothing
    parameter_units::Union{Nothing, String} = "COMPONENT_BASE"
    b = nothing # spec type: Union{ Nothing, FromTo }
    rating::Union{Nothing, Float64} = nothing
    rating_b::Union{Nothing, Float64} = nothing
    rating_c::Union{Nothing, Float64} = nothing
    angle_limits = nothing # spec type: Union{ Nothing, MinMax }
    g = FromTo(; from=0.0, to=0.0) # spec type: Union{ Nothing, FromTo }

    function Line(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, base_power, power_units, parameter_units, b, rating, rating_b, rating_c, angle_limits, g, )
        o = new(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, base_power, power_units, parameter_units, b, rating, rating_b, rating_c, angle_limits, g, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Line

const _property_types_Line = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("name")=>Union{Nothing, String}, Symbol("available")=>Union{Nothing, Bool}, Symbol("active_power_flow")=>Union{Nothing, Float64}, Symbol("reactive_power_flow")=>Union{Nothing, Float64}, Symbol("arc")=>Union{Nothing, Int64}, Symbol("r")=>Union{Nothing, Float64}, Symbol("x")=>Union{Nothing, Float64}, Symbol("base_power")=>Union{Nothing, Float64}, Symbol("power_units")=>Union{Nothing, String}, Symbol("parameter_units")=>Union{Nothing, String}, Symbol("b")=>Union{Nothing, FromTo}, Symbol("rating")=>Union{Nothing, Float64}, Symbol("rating_b")=>Union{Nothing, Float64}, Symbol("rating_c")=>Union{Nothing, Float64}, Symbol("angle_limits")=>Union{Nothing, MinMax}, Symbol("g")=>Union{Nothing, FromTo}, )
OpenAPI.property_type(::Type{ Line }, name::Symbol) = _property_types_Line[name]

function OpenAPI.check_required(o::Line)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.base_power === nothing && (return false)
    o.power_units === nothing && (return false)
    o.rating === nothing && (return false)
    o.angle_limits === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Line)
    OpenAPI.validate_property(Line, Symbol("id"), o.id)
    OpenAPI.validate_property(Line, Symbol("name"), o.name)
    OpenAPI.validate_property(Line, Symbol("available"), o.available)
    OpenAPI.validate_property(Line, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(Line, Symbol("reactive_power_flow"), o.reactive_power_flow)
    OpenAPI.validate_property(Line, Symbol("arc"), o.arc)
    OpenAPI.validate_property(Line, Symbol("r"), o.r)
    OpenAPI.validate_property(Line, Symbol("x"), o.x)
    OpenAPI.validate_property(Line, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(Line, Symbol("power_units"), o.power_units)
    OpenAPI.validate_property(Line, Symbol("parameter_units"), o.parameter_units)
    OpenAPI.validate_property(Line, Symbol("b"), o.b)
    OpenAPI.validate_property(Line, Symbol("rating"), o.rating)
    OpenAPI.validate_property(Line, Symbol("rating_b"), o.rating_b)
    OpenAPI.validate_property(Line, Symbol("rating_c"), o.rating_c)
    OpenAPI.validate_property(Line, Symbol("angle_limits"), o.angle_limits)
    OpenAPI.validate_property(Line, Symbol("g"), o.g)
end

function OpenAPI.validate_property(::Type{ Line }, name::Symbol, val)










    if name === Symbol("power_units")
        OpenAPI.validate_param(name, "Line", :enum, val, ["COMPONENT_BASE", "NATURAL_UNITS"])
    end


    if name === Symbol("parameter_units")
        OpenAPI.validate_param(name, "Line", :enum, val, ["NATURAL_UNITS", "COMPONENT_BASE"])
    end







end
