# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DCBus
A DC bus.

    DCBus(;
        area=nothing,
        available=nothing,
        base_voltage=nothing,
        id=nothing,
        load_zone=nothing,
        magnitude=nothing,
        name=nothing,
        number=nothing,
        voltage_limits=nothing,
    )

    - area::Int64 : ID of the area containing the DC bus.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - base_voltage::Float64 : The base voltage. in psy5 a required param with an option to be nothing Units: kV.
    - id::Int64 : Unique integer identifier for this component.
    - load_zone::Int64 : ID of the load zone containing the DC bus.
    - magnitude::Float64 : Voltage as a multiple of &#x60;base_voltage&#x60;. in psy5 a required param with an option to be nothing Units: pu.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - number::Float64 : A unique bus identification number (positive integer).
    - voltage_limits::MinMax
"""
Base.@kwdef mutable struct DCBus <: OpenAPI.APIModel
    area::Union{Nothing, Int64} = nothing
    available::Union{Nothing, Bool} = nothing
    base_voltage::Union{Nothing, Float64} = nothing
    id::Union{Nothing, Int64} = nothing
    load_zone::Union{Nothing, Int64} = nothing
    magnitude::Union{Nothing, Float64} = nothing
    name::Union{Nothing, String} = nothing
    number::Union{Nothing, Float64} = nothing
    voltage_limits = nothing # spec type: Union{ Nothing, MinMax }

    function DCBus(area, available, base_voltage, id, load_zone, magnitude, name, number, voltage_limits, )
        o = new(area, available, base_voltage, id, load_zone, magnitude, name, number, voltage_limits, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DCBus

const _property_types_DCBus = Dict{Symbol,String}(Symbol("area")=>"Int64", Symbol("available")=>"Bool", Symbol("base_voltage")=>"Float64", Symbol("id")=>"Int64", Symbol("load_zone")=>"Int64", Symbol("magnitude")=>"Float64", Symbol("name")=>"String", Symbol("number")=>"Float64", Symbol("voltage_limits")=>"MinMax", )
OpenAPI.property_type(::Type{ DCBus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DCBus[name]))}

function OpenAPI.check_required(o::DCBus)
    o.available === nothing && (return false)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.number === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DCBus)
    OpenAPI.validate_property(DCBus, Symbol("area"), o.area)
    OpenAPI.validate_property(DCBus, Symbol("available"), o.available)
    OpenAPI.validate_property(DCBus, Symbol("base_voltage"), o.base_voltage)
    OpenAPI.validate_property(DCBus, Symbol("id"), o.id)
    OpenAPI.validate_property(DCBus, Symbol("load_zone"), o.load_zone)
    OpenAPI.validate_property(DCBus, Symbol("magnitude"), o.magnitude)
    OpenAPI.validate_property(DCBus, Symbol("name"), o.name)
    OpenAPI.validate_property(DCBus, Symbol("number"), o.number)
    OpenAPI.validate_property(DCBus, Symbol("voltage_limits"), o.voltage_limits)
end

function OpenAPI.validate_property(::Type{ DCBus }, name::Symbol, val)









end
