# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExponentialLoad
A voltage-dependent ZIP load, most commonly used for dynamics modeling.  An &#x60;ExponentialLoad&#x60; models active power as P &#x3D; P0 * V^α and reactive power as Q &#x3D; Q0 * V^β, where the exponents α and β select govern the voltage dependency. For an alternative three-part formulation of the ZIP model, see &#x60;StandardLoad&#x60;. For a simpler load model with no voltage dependency, see &#x60;PowerLoad&#x60;.

    ExponentialLoad(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        active_power=nothing,
        reactive_power=nothing,
        alpha=nothing,
        beta=nothing,
        base_power=nothing,
        max_active_power=nothing,
        max_reactive_power=nothing,
        conformity="UNDEFINED",
        dynamic_injector=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - bus::Int64 : ID of the bus that this component is connected to.
    - active_power::Float64 : Active power coefficient, P0. Units: MW.
    - reactive_power::Float64 : Reactive power coefficient, Q0. Units: MVAr.
    - alpha::Float64 : Exponent relating voltage dependency for active power. 0 &#x3D; constant power only, 1 &#x3D; constant current only, and 2 &#x3D; constant impedance only.
    - beta::Float64 : Exponent relating voltage dependency for reactive power. 0 &#x3D; constant power only, 1 &#x3D; constant current only, and 2 &#x3D; constant impedance only.
    - base_power::Float64 : Base power of the unit for per unitization. Units: MVA.
    - max_active_power::Float64 : Maximum active power that this load can demand. Units: MW.
    - max_reactive_power::Float64 : Maximum reactive power that this load can demand. Units: MVAr.
    - conformity::String : Indicates whether the specified load is conforming or non-conforming.
    - dynamic_injector::Int64 : ID of the corresponding dynamic injection device, if any.
"""
Base.@kwdef mutable struct ExponentialLoad <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    reactive_power::Union{Nothing, Float64} = nothing
    alpha::Union{Nothing, Float64} = nothing
    beta::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    max_active_power::Union{Nothing, Float64} = nothing
    max_reactive_power::Union{Nothing, Float64} = nothing
    conformity::Union{Nothing, String} = "UNDEFINED"
    dynamic_injector::Union{Nothing, Int64} = nothing

    function ExponentialLoad(id, name, available, bus, active_power, reactive_power, alpha, beta, base_power, max_active_power, max_reactive_power, conformity, dynamic_injector, )
        o = new(id, name, available, bus, active_power, reactive_power, alpha, beta, base_power, max_active_power, max_reactive_power, conformity, dynamic_injector, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ExponentialLoad

const _property_types_ExponentialLoad = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("name")=>Union{Nothing, String}, Symbol("available")=>Union{Nothing, Bool}, Symbol("bus")=>Union{Nothing, Int64}, Symbol("active_power")=>Union{Nothing, Float64}, Symbol("reactive_power")=>Union{Nothing, Float64}, Symbol("alpha")=>Union{Nothing, Float64}, Symbol("beta")=>Union{Nothing, Float64}, Symbol("base_power")=>Union{Nothing, Float64}, Symbol("max_active_power")=>Union{Nothing, Float64}, Symbol("max_reactive_power")=>Union{Nothing, Float64}, Symbol("conformity")=>Union{Nothing, String}, Symbol("dynamic_injector")=>Union{Nothing, Int64}, )
OpenAPI.property_type(::Type{ ExponentialLoad }, name::Symbol) = _property_types_ExponentialLoad[name]

function OpenAPI.check_required(o::ExponentialLoad)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    o.active_power === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.alpha === nothing && (return false)
    o.beta === nothing && (return false)
    o.base_power === nothing && (return false)
    o.max_active_power === nothing && (return false)
    o.max_reactive_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ExponentialLoad)
    OpenAPI.validate_property(ExponentialLoad, Symbol("id"), o.id)
    OpenAPI.validate_property(ExponentialLoad, Symbol("name"), o.name)
    OpenAPI.validate_property(ExponentialLoad, Symbol("available"), o.available)
    OpenAPI.validate_property(ExponentialLoad, Symbol("bus"), o.bus)
    OpenAPI.validate_property(ExponentialLoad, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(ExponentialLoad, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(ExponentialLoad, Symbol("alpha"), o.alpha)
    OpenAPI.validate_property(ExponentialLoad, Symbol("beta"), o.beta)
    OpenAPI.validate_property(ExponentialLoad, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(ExponentialLoad, Symbol("max_active_power"), o.max_active_power)
    OpenAPI.validate_property(ExponentialLoad, Symbol("max_reactive_power"), o.max_reactive_power)
    OpenAPI.validate_property(ExponentialLoad, Symbol("conformity"), o.conformity)
    OpenAPI.validate_property(ExponentialLoad, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{ ExponentialLoad }, name::Symbol, val)












    if name === Symbol("conformity")
        OpenAPI.validate_param(name, "ExponentialLoad", :enum, val, ["NON_CONFORMING", "CONFORMING", "UNDEFINED"])
    end


end
