# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FromTo_1
Shunt conductance, specified both on the &#x60;from&#x60; and &#x60;to&#x60; ends of the line. These are commonly modeled with the same value. Per-unit on system base. Units: pu.

    FromTo1(;
        from=nothing,
        to=nothing,
    )

    - from::Float64
    - to::Float64
"""
Base.@kwdef mutable struct FromTo1 <: OpenAPI.APIModel
    from::Union{Nothing, Float64} = nothing
    to::Union{Nothing, Float64} = nothing

    function FromTo1(from, to, )
        o = new(from, to, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FromTo1

const _property_types_FromTo1 = Dict{Symbol,String}(Symbol("from")=>"Float64", Symbol("to")=>"Float64", )
OpenAPI.property_type(::Type{ FromTo1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FromTo1[name]))}

function OpenAPI.check_required(o::FromTo1)
    true
end

function OpenAPI.validate_properties(o::FromTo1)
    OpenAPI.validate_property(FromTo1, Symbol("from"), o.from)
    OpenAPI.validate_property(FromTo1, Symbol("to"), o.to)
end

function OpenAPI.validate_property(::Type{ FromTo1 }, name::Symbol, val)


end
