# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MonitoredLine
An AC transmission line with additional power flow constraints specified by the system operator, more restrictive than the line&#39;s thermal limits.  For example, monitored lines can be used to restrict line flow following a contingency elsewhere in the network. See the &#x60;flow_limits&#x60; parameter. If monitoring is not needed, see &#x60;Line&#x60;.

    MonitoredLine(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        base_power=nothing,
        b=nothing,
        flow_limits=nothing,
        rating=nothing,
        rating_b=nothing,
        rating_c=nothing,
        angle_limits=nothing,
        g=FromTo(; from=0.0, to=0.0),
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - active_power_flow::Float64 : Initial condition of active power flow on the line. Units: MW.
    - reactive_power_flow::Float64 : Initial condition of reactive power flow on the line. Units: MVAr.
    - arc::Int64 : An &#x60;Arc&#x60; defining this line &#x60;from&#x60; a bus &#x60;to&#x60; another bus.
    - r::Float64 : Resistance. Per-unit on &#x60;base_power&#x60;, which records the system base. Units: pu.
    - x::Float64 : Reactance. Per-unit on &#x60;base_power&#x60;, which records the system base. Units: pu.
    - base_power::Float64 : System base power for per-unitization of this component&#39;s per-unit fields, recorded per component in lieu of a system-level table. Units: MVA.
    - b::FromTo
    - flow_limits::FromToToFrom
    - rating::Float64 : Thermal rating. Flow through the transformer must be between -&#x60;rating&#x60; and &#x60;rating&#x60;. Units: MVA.
    - rating_b::Float64 : Second current rating. Units: MVA.
    - rating_c::Float64 : Third current rating. Units: MVA.
    - angle_limits::MinMax
    - g::FromTo
"""
Base.@kwdef mutable struct MonitoredLine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    b = nothing # spec type: Union{ Nothing, FromTo }
    flow_limits = nothing # spec type: Union{ Nothing, FromToToFrom }
    rating::Union{Nothing, Float64} = nothing
    rating_b::Union{Nothing, Float64} = nothing
    rating_c::Union{Nothing, Float64} = nothing
    angle_limits = nothing # spec type: Union{ Nothing, MinMax }
    g = FromTo(; from=0.0, to=0.0) # spec type: Union{ Nothing, FromTo }

    function MonitoredLine(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, base_power, b, flow_limits, rating, rating_b, rating_c, angle_limits, g, )
        o = new(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, base_power, b, flow_limits, rating, rating_b, rating_c, angle_limits, g, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type MonitoredLine

const _property_types_MonitoredLine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("active_power_flow")=>"Float64", Symbol("reactive_power_flow")=>"Float64", Symbol("arc")=>"Int64", Symbol("r")=>"Float64", Symbol("x")=>"Float64", Symbol("base_power")=>"Float64", Symbol("b")=>"FromTo", Symbol("flow_limits")=>"FromToToFrom", Symbol("rating")=>"Float64", Symbol("rating_b")=>"Float64", Symbol("rating_c")=>"Float64", Symbol("angle_limits")=>"MinMax", Symbol("g")=>"FromTo", )
OpenAPI.property_type(::Type{ MonitoredLine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MonitoredLine[name]))}

function OpenAPI.check_required(o::MonitoredLine)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.base_power === nothing && (return false)
    o.b === nothing && (return false)
    o.flow_limits === nothing && (return false)
    o.rating === nothing && (return false)
    o.angle_limits === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::MonitoredLine)
    OpenAPI.validate_property(MonitoredLine, Symbol("id"), o.id)
    OpenAPI.validate_property(MonitoredLine, Symbol("name"), o.name)
    OpenAPI.validate_property(MonitoredLine, Symbol("available"), o.available)
    OpenAPI.validate_property(MonitoredLine, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(MonitoredLine, Symbol("reactive_power_flow"), o.reactive_power_flow)
    OpenAPI.validate_property(MonitoredLine, Symbol("arc"), o.arc)
    OpenAPI.validate_property(MonitoredLine, Symbol("r"), o.r)
    OpenAPI.validate_property(MonitoredLine, Symbol("x"), o.x)
    OpenAPI.validate_property(MonitoredLine, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(MonitoredLine, Symbol("b"), o.b)
    OpenAPI.validate_property(MonitoredLine, Symbol("flow_limits"), o.flow_limits)
    OpenAPI.validate_property(MonitoredLine, Symbol("rating"), o.rating)
    OpenAPI.validate_property(MonitoredLine, Symbol("rating_b"), o.rating_b)
    OpenAPI.validate_property(MonitoredLine, Symbol("rating_c"), o.rating_c)
    OpenAPI.validate_property(MonitoredLine, Symbol("angle_limits"), o.angle_limits)
    OpenAPI.validate_property(MonitoredLine, Symbol("g"), o.g)
end

function OpenAPI.validate_property(::Type{ MonitoredLine }, name::Symbol, val)
















end
