# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VariableReserveNonSpinning
A non-spinning reserve product with a time-varying procurement requirement, such as a higher requirement during hours with an expected high load or high ramp. This reserve product includes back-up generators that might not be currently synchronized with the power system, but can come online quickly after an unexpected contingency, such as a transmission line or generator outage. To model the time varying requirement, a \&quot;&#x60;requirement&#x60;\&quot; time series should be added to this reserve. This is only an upwards reserve. For faster-responding upwards or downwards reserves from components already synchronized with the system, see &#x60;VariableReserve&#x60;.

    VariableReserveNonSpinning(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=nothing,
        sustained_time=14400.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - time_frame::Float64 : The saturation time frame to provide reserve contribution. Units: min.
    - requirement::Float64 : The required quantity of the product, which should be scaled by a time series. Units: MW.
    - sustained_time::Float64 : The time reserve contribution must be sustained at a specified level. Units: s.
    - max_output_fraction::Float64 : The maximum fraction of each device&#39;s output that can be assigned to the service.
    - max_participation_factor::Float64 : The maximum portion [0, 1.0] of the reserve that can be contributed per device.
    - deployed_fraction::Float64 : Fraction of service procurement that is assumed to be actually deployed. Most commonly, this is assumed to be either 0.0 or 1.0.
"""
Base.@kwdef mutable struct VariableReserveNonSpinning <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = nothing
    sustained_time::Union{Nothing, Float64} = 14400.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0

    function VariableReserveNonSpinning(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
        o = new(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VariableReserveNonSpinning

const _property_types_VariableReserveNonSpinning = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("time_frame")=>"Float64", Symbol("requirement")=>"Float64", Symbol("sustained_time")=>"Float64", Symbol("max_output_fraction")=>"Float64", Symbol("max_participation_factor")=>"Float64", Symbol("deployed_fraction")=>"Float64", )
OpenAPI.property_type(::Type{ VariableReserveNonSpinning }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VariableReserveNonSpinning[name]))}

function OpenAPI.check_required(o::VariableReserveNonSpinning)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    o.requirement === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::VariableReserveNonSpinning)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("id"), o.id)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("name"), o.name)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("available"), o.available)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("time_frame"), o.time_frame)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("requirement"), o.requirement)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("sustained_time"), o.sustained_time)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("max_output_fraction"), o.max_output_fraction)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("max_participation_factor"), o.max_participation_factor)
    OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("deployed_fraction"), o.deployed_fraction)
end

function OpenAPI.validate_property(::Type{ VariableReserveNonSpinning }, name::Symbol, val)









end
