# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EnergyReservoirStorage
An energy storage device, modeled as a generic energy reservoir.  This is suitable for modeling storage charging and discharging with average efficiency losses, ignoring the physical dynamics of the storage unit. A variety of energy storage types and chemistries can be modeled with this approach. For pumped hydro storage, alternatively see &#x60;HydroPumpTurbine&#x60; and &#x60;HydroReservoir&#x60;.

    EnergyReservoirStorage(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        prime_mover_type=nothing,
        storage_technology_type=nothing,
        storage_capacity=nothing,
        energy_units="MWH",
        storage_level_limits=nothing,
        initial_storage_capacity_level=nothing,
        rating=nothing,
        active_power=nothing,
        input_active_power_limits=nothing,
        output_active_power_limits=nothing,
        efficiency=nothing,
        reactive_power=nothing,
        reactive_power_limits=nothing,
        base_power=nothing,
        operation_cost=nothing,
        conversion_factor=1.0,
        storage_target=0.0,
        cycle_limits=10000,
        ramp_limits=nothing,
        self_discharge=0.0,
        standing_loss=0.0,
        dynamic_injector=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - bus::Int64 : ID of the bus that this component is connected to.
    - prime_mover_type::String : Prime mover technology according to EIA 923.
    - storage_technology_type::String : Storage Technology Complementary to EIA 923.
    - storage_capacity::Float64 : Maximum storage capacity (can be in units of, e.g., MWh for batteries or liters for hydrogen). Divided by base_power this gives an approximate duration, assuming unity power factor: in hours under MWH, in minutes under MWMIN. Units: per energy_units — MWH: MWh, MWMIN: MWmin .
    - energy_units::String : Unit basis for &#x60;storage_capacity&#x60;. MWH is the default interchange form; MWMIN records the same energy on the minutes basis used by operational durations.
    - storage_level_limits::MinMax
    - initial_storage_capacity_level::Float64 : Initial storage capacity level as a ratio [0, 1.0] of &#x60;storage_capacity&#x60;. Units: 1.
    - rating::Float64 : Maximum AC side output power rating of the unit. Not to be confused with base_power. Units: MVA.
    - active_power::Float64 : Initial active power set point of the unit. For power flow, this is the steady state operating point of the system. For production cost modeling, this may or may not be used as the initial starting point for the solver, depending on the solver used. Units: MW.
    - input_active_power_limits::MinMax
    - output_active_power_limits::MinMax
    - efficiency::InOut
    - reactive_power::Float64 : Initial reactive power set point of the unit. Units: MVAr.
    - reactive_power_limits::MinMax
    - base_power::Float64 : Base power of the unit for per unitization. Units: MVA.
    - operation_cost::EnergyReservoirStorageOperationCost
    - conversion_factor::Float64 : Conversion factor of &#x60;storage_capacity&#x60; to MWh, if different than 1.0. For example, X MWh/liter hydrogen. Units: 1.
    - storage_target::Float64 : Storage target at the end of simulation as ratio of storage capacity. Units: 1.
    - cycle_limits::Int64 : Storage Maximum number of cycles per year. Units: 1.
    - ramp_limits::UpDown
    - self_discharge::Float64 : Self-discharge (leakage loss) as a fraction of the stored energy lost per minute (pu/min of storage_capacity), modeled as E[t] &#x3D; (1 - self_discharge * dt) * E[t-1]; dt must be on the same minutes basis. Units: 1/min.
    - standing_loss::Float64 : Constant standing-loss power drawn by the storage system. Reduces the effective charging power (p_in - standing_loss) and increases the power drawn from the storage when discharging (p_out + standing_loss). Units: MW.
    - dynamic_injector::Int64 : ID of the corresponding dynamic injection device, if any.
"""
Base.@kwdef mutable struct EnergyReservoirStorage <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    prime_mover_type::Union{Nothing, String} = nothing
    storage_technology_type::Union{Nothing, String} = nothing
    storage_capacity::Union{Nothing, Float64} = nothing
    energy_units::Union{Nothing, String} = "MWH"
    storage_level_limits = nothing # spec type: Union{ Nothing, MinMax }
    initial_storage_capacity_level::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    input_active_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    output_active_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    efficiency = nothing # spec type: Union{ Nothing, InOut }
    reactive_power::Union{Nothing, Float64} = nothing
    reactive_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    base_power::Union{Nothing, Float64} = nothing
    operation_cost = nothing # spec type: Union{ Nothing, EnergyReservoirStorageOperationCost }
    conversion_factor::Union{Nothing, Float64} = 1.0
    storage_target::Union{Nothing, Float64} = 0.0
    cycle_limits::Union{Nothing, Int64} = 10000
    ramp_limits = nothing # spec type: Union{ Nothing, UpDown }
    self_discharge::Union{Nothing, Float64} = 0.0
    standing_loss::Union{Nothing, Float64} = 0.0
    dynamic_injector::Union{Nothing, Int64} = nothing

    function EnergyReservoirStorage(id, name, available, bus, prime_mover_type, storage_technology_type, storage_capacity, energy_units, storage_level_limits, initial_storage_capacity_level, rating, active_power, input_active_power_limits, output_active_power_limits, efficiency, reactive_power, reactive_power_limits, base_power, operation_cost, conversion_factor, storage_target, cycle_limits, ramp_limits, self_discharge, standing_loss, dynamic_injector, )
        o = new(id, name, available, bus, prime_mover_type, storage_technology_type, storage_capacity, energy_units, storage_level_limits, initial_storage_capacity_level, rating, active_power, input_active_power_limits, output_active_power_limits, efficiency, reactive_power, reactive_power_limits, base_power, operation_cost, conversion_factor, storage_target, cycle_limits, ramp_limits, self_discharge, standing_loss, dynamic_injector, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EnergyReservoirStorage

const _property_types_EnergyReservoirStorage = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("bus")=>"Int64", Symbol("prime_mover_type")=>"String", Symbol("storage_technology_type")=>"String", Symbol("storage_capacity")=>"Float64", Symbol("energy_units")=>"String", Symbol("storage_level_limits")=>"MinMax", Symbol("initial_storage_capacity_level")=>"Float64", Symbol("rating")=>"Float64", Symbol("active_power")=>"Float64", Symbol("input_active_power_limits")=>"MinMax", Symbol("output_active_power_limits")=>"MinMax", Symbol("efficiency")=>"InOut", Symbol("reactive_power")=>"Float64", Symbol("reactive_power_limits")=>"MinMax", Symbol("base_power")=>"Float64", Symbol("operation_cost")=>"EnergyReservoirStorageOperationCost", Symbol("conversion_factor")=>"Float64", Symbol("storage_target")=>"Float64", Symbol("cycle_limits")=>"Int64", Symbol("ramp_limits")=>"UpDown", Symbol("self_discharge")=>"Float64", Symbol("standing_loss")=>"Float64", Symbol("dynamic_injector")=>"Int64", )
OpenAPI.property_type(::Type{ EnergyReservoirStorage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EnergyReservoirStorage[name]))}

function OpenAPI.check_required(o::EnergyReservoirStorage)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    o.prime_mover_type === nothing && (return false)
    o.storage_technology_type === nothing && (return false)
    o.storage_capacity === nothing && (return false)
    o.storage_level_limits === nothing && (return false)
    o.initial_storage_capacity_level === nothing && (return false)
    o.rating === nothing && (return false)
    o.active_power === nothing && (return false)
    o.input_active_power_limits === nothing && (return false)
    o.output_active_power_limits === nothing && (return false)
    o.efficiency === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.base_power === nothing && (return false)
    o.operation_cost === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EnergyReservoirStorage)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("id"), o.id)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("name"), o.name)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("available"), o.available)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("bus"), o.bus)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("prime_mover_type"), o.prime_mover_type)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("storage_technology_type"), o.storage_technology_type)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("storage_capacity"), o.storage_capacity)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("energy_units"), o.energy_units)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("storage_level_limits"), o.storage_level_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("initial_storage_capacity_level"), o.initial_storage_capacity_level)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("rating"), o.rating)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("input_active_power_limits"), o.input_active_power_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("output_active_power_limits"), o.output_active_power_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("efficiency"), o.efficiency)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("reactive_power_limits"), o.reactive_power_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("operation_cost"), o.operation_cost)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("conversion_factor"), o.conversion_factor)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("storage_target"), o.storage_target)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("cycle_limits"), o.cycle_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("ramp_limits"), o.ramp_limits)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("self_discharge"), o.self_discharge)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("standing_loss"), o.standing_loss)
    OpenAPI.validate_property(EnergyReservoirStorage, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{ EnergyReservoirStorage }, name::Symbol, val)





    if name === Symbol("prime_mover_type")
        OpenAPI.validate_param(name, "EnergyReservoirStorage", :enum, val, ["BA", "BT", "CA", "CC", "CE", "CP", "CS", "CT", "ES", "FC", "FW", "GT", "HA", "HB", "HK", "HY", "IC", "PS", "OT", "ST", "PVe", "WT", "WS"])
    end


    if name === Symbol("storage_technology_type")
        OpenAPI.validate_param(name, "EnergyReservoirStorage", :enum, val, ["PTES", "LIB", "LAB", "FLWB", "SIB", "ZIB", "HGS", "LAES", "OTHER_CHEM", "OTHER_MECH", "OTHER_THERM"])
    end



    if name === Symbol("energy_units")
        OpenAPI.validate_param(name, "EnergyReservoirStorage", :enum, val, ["MWH", "MWMIN"])
    end



















end
