# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OnlineReserve
A reserve product provided by devices already synchronized with the system. The procurement requirement is static unless a &#x60;requirement&#x60; time series is attached, in which case &#x60;requirement&#x60; is the scaling factor. Attach an Operating Reserve Demand Curve through &#x60;variable&#x60; to price the requirement rather than enforce it; omit &#x60;variable&#x60; when the reserve has no demand curve.

    OnlineReserve(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=0.0,
        variable=nothing,
        sustained_time=60.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
        reserve_direction=nothing,
    )

    - id::Int64 : Unique integer identifier for this component.
    - name::String : Name of the component. Components of the same type (e.g., &#x60;PowerLoad&#x60;) must have unique names, but components of different types (e.g., &#x60;PowerLoad&#x60; and &#x60;ACBus&#x60;) can have the same name.
    - available::Bool : Indicator of whether the component is connected and online (&#x60;true&#x60;) or disconnected, offline, or down (&#x60;false&#x60;). Unavailable components are excluded during simulations.
    - time_frame::Float64 : The saturation time frame to provide reserve contribution. Units: min.
    - requirement::Float64 : The value of required reserves. Units: MW.
    - variable::CostCurve
    - sustained_time::Float64 : The time reserve contribution must be sustained at a specified level. Units: min.
    - max_output_fraction::Float64 : The maximum fraction of each device&#39;s output that can be assigned to the service.
    - max_participation_factor::Float64 : The maximum portion [0, 1.0] of the reserve that can be contributed per device.
    - deployed_fraction::Float64 : Fraction of service procurement that is assumed to be actually deployed. Most commonly, this is assumed to be either 0.0 or 1.0.
    - reserve_direction::String : Whether the reserve is an upward, downward, or symmetric reserve product.
"""
Base.@kwdef mutable struct OnlineReserve <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = 0.0
    variable = nothing # spec type: Union{ Nothing, CostCurve }
    sustained_time::Union{Nothing, Float64} = 60.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0
    reserve_direction::Union{Nothing, String} = nothing

    function OnlineReserve(id, name, available, time_frame, requirement, variable, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, reserve_direction, )
        o = new(id, name, available, time_frame, requirement, variable, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, reserve_direction, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type OnlineReserve

const _property_types_OnlineReserve = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("time_frame")=>"Float64", Symbol("requirement")=>"Float64", Symbol("variable")=>"CostCurve", Symbol("sustained_time")=>"Float64", Symbol("max_output_fraction")=>"Float64", Symbol("max_participation_factor")=>"Float64", Symbol("deployed_fraction")=>"Float64", Symbol("reserve_direction")=>"String", )
OpenAPI.property_type(::Type{ OnlineReserve }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OnlineReserve[name]))}

function OpenAPI.check_required(o::OnlineReserve)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    o.reserve_direction === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::OnlineReserve)
    OpenAPI.validate_property(OnlineReserve, Symbol("id"), o.id)
    OpenAPI.validate_property(OnlineReserve, Symbol("name"), o.name)
    OpenAPI.validate_property(OnlineReserve, Symbol("available"), o.available)
    OpenAPI.validate_property(OnlineReserve, Symbol("time_frame"), o.time_frame)
    OpenAPI.validate_property(OnlineReserve, Symbol("requirement"), o.requirement)
    OpenAPI.validate_property(OnlineReserve, Symbol("variable"), o.variable)
    OpenAPI.validate_property(OnlineReserve, Symbol("sustained_time"), o.sustained_time)
    OpenAPI.validate_property(OnlineReserve, Symbol("max_output_fraction"), o.max_output_fraction)
    OpenAPI.validate_property(OnlineReserve, Symbol("max_participation_factor"), o.max_participation_factor)
    OpenAPI.validate_property(OnlineReserve, Symbol("deployed_fraction"), o.deployed_fraction)
    OpenAPI.validate_property(OnlineReserve, Symbol("reserve_direction"), o.reserve_direction)
end

function OpenAPI.validate_property(::Type{ OnlineReserve }, name::Symbol, val)











    if name === Symbol("reserve_direction")
        OpenAPI.validate_param(name, "OnlineReserve", :enum, val, ["UP", "DOWN", "SYMMETRIC"])
    end

end
