# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""PointToPointBid_spread_bid
Willingness-to-pay curve on the to-minus-from price spread, as an offer-curve operating cost (incremental side only).

    PointToPointBidSpreadBid(; value=nothing)
"""
mutable struct PointToPointBidSpreadBid <: OpenAPI.OneOfAPIModel
    value::Any # Union{ MarketBidCost, MarketBidTimeSeriesCost }
    PointToPointBidSpreadBid() = new()
    PointToPointBidSpreadBid(value) = new(value)
end # type PointToPointBidSpreadBid

function OpenAPI.property_type(::Type{ PointToPointBidSpreadBid }, name::Symbol, json::Dict{String,Any})
    discriminator = json["cost_type"]
    if discriminator == "MARKET_BID"
        return (MarketBidCost)
    elseif discriminator == "MARKET_BID_TIME_SERIES"
        return (MarketBidTimeSeriesCost)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for PointToPointBidSpreadBid"))
end
