# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""VirtualParticipant_operation_cost
Bid curves as an offer-curve operating cost.

    VirtualParticipantOperationCost(; value=nothing)
"""
mutable struct VirtualParticipantOperationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ MarketBidCost, MarketBidTimeSeriesCost }
    VirtualParticipantOperationCost() = new()
    VirtualParticipantOperationCost(value) = new(value)
end # type VirtualParticipantOperationCost

function OpenAPI.property_type(::Type{ VirtualParticipantOperationCost }, name::Symbol, json::Dict{String,Any})
    discriminator = json["cost_type"]
    if discriminator == "MARKET_BID"
        return (MarketBidCost)
    elseif discriminator == "MARKET_BID_TIME_SERIES"
        return (MarketBidTimeSeriesCost)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for VirtualParticipantOperationCost"))
end
