# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""FunctionData_3
Only TIME_SERIES_LINEAR, TIME_SERIES_QUADRATIC, or TIME_SERIES_PIECEWISE_LINEAR is admissible here; the static variants and TIME_SERIES_PIECEWISE_STEP are invalid and rejected by the consuming constructor.

    FunctionData3(; value=nothing)
"""
mutable struct FunctionData3 <: OpenAPI.OneOfAPIModel
    value::Any # Union{ LinearFunctionData, PiecewiseLinearData, PiecewiseStepData, QuadraticFunctionData, TimeSeriesLinearFunctionData1, TimeSeriesPiecewiseLinearData1, TimeSeriesPiecewiseStepData1, TimeSeriesQuadraticFunctionData1 }
    FunctionData3() = new()
    FunctionData3(value) = new(value)
end # type FunctionData3

function OpenAPI.property_type(::Type{ FunctionData3 }, name::Symbol, json::Dict{String,Any})
    discriminator = json["function_type"]
    if discriminator == "LINEAR"
        return (LinearFunctionData)
    elseif discriminator == "PIECEWISE_LINEAR"
        return (PiecewiseLinearData)
    elseif discriminator == "PIECEWISE_STEP"
        return (PiecewiseStepData)
    elseif discriminator == "QUADRATIC"
        return (QuadraticFunctionData)
    elseif discriminator == "TIME_SERIES_LINEAR"
        return (TimeSeriesLinearFunctionData)
    elseif discriminator == "TIME_SERIES_PIECEWISE_LINEAR"
        return (TimeSeriesPiecewiseLinearData)
    elseif discriminator == "TIME_SERIES_PIECEWISE_STEP"
        return (TimeSeriesPiecewiseStepData)
    elseif discriminator == "TIME_SERIES_QUADRATIC"
        return (TimeSeriesQuadraticFunctionData)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for FunctionData3"))
end
