# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""HydroDispatch_operation_cost
Operating cost of generation. or MarketBidCost; default PSY.HydroGenerationCost(nothing)

    HydroDispatchOperationCost(; value=nothing)
"""
mutable struct HydroDispatchOperationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ HydroGenerationCost, MarketBidCost }
    HydroDispatchOperationCost() = new()
    HydroDispatchOperationCost(value) = new(value)
end # type HydroDispatchOperationCost

function OpenAPI.property_type(::Type{ HydroDispatchOperationCost }, name::Symbol, json::Dict{String,Any})
    discriminator = json["cost_type"]
    if discriminator == "HYDRO_GEN"
        return (HydroGenerationCost)
    elseif discriminator == "MARKET_BID"
        return (MarketBidCost)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for HydroDispatchOperationCost"))
end
