# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FuelCurve
Variable operation cost of a device expressed in fuel consumed — MBTU, liters, m^3 — together with the price that converts fuel to currency. Wraps a &#x60;ValueCurve&#x60; in input-output, incremental, or average-rate form; exactly one of &#x60;fuel_cost&#x60; and &#x60;fuel_cost_time_series&#x60; supplies the price.

    FuelCurve(;
        fuel_cost=nothing,
        fuel_cost_time_series=nothing,
        power_units=nothing,
        startup_fuel_offtake=nothing,
        value_curve=nothing,
        variable_cost_type="FUEL",
        vom_cost=nothing,
    )

    - fuel_cost::Float64 : Fixed fuel cost per unit of fuel, or null when fuel_cost_time_series names a time-varying one. Exactly one of the two is set; producers and consumers enforce it.
    - fuel_cost_time_series::Int64 : Store-minted id of the fuel-cost time series association, or null when fuel_cost carries a fixed value. Exactly one of the two is set.
    - power_units::String : Unit basis a stored value is expressed in. COMPONENT_BASE: per-unit against a base the component records itself. NATURAL_UNITS: the quantity&#39;s own physical unit. No system-wide option: a value per-unitized against a shared base records that base on the component and rides as COMPONENT_BASE. Used in three scopes, each read against its own record rather than a document-wide table: a component&#39;s own &#x60;power_units&#x60; (against that component&#39;s &#x60;base_power&#x60;), a cost payload&#39;s own &#x60;power_units&#x60; (e.g. &#x60;CostCurve&#x60;, against the owning component&#39;s &#x60;base_power&#x60;), and a time series association&#39;s own &#x60;unit_system&#x60; (governing only that one series).
    - startup_fuel_offtake::InputOutputCurve
    - value_curve::ValueCurve
    - variable_cost_type::String
    - vom_cost::InputOutputCurve
"""
Base.@kwdef mutable struct FuelCurve <: OpenAPI.APIModel
    fuel_cost::Union{Nothing, Float64} = nothing
    fuel_cost_time_series::Union{Nothing, Int64} = nothing
    power_units::Union{Nothing, String} = nothing
    startup_fuel_offtake = nothing # spec type: Union{ Nothing, InputOutputCurve }
    value_curve = nothing # spec type: Union{ Nothing, ValueCurve }
    variable_cost_type::Union{Nothing, String} = "FUEL"
    vom_cost = nothing # spec type: Union{ Nothing, InputOutputCurve }

    function FuelCurve(fuel_cost, fuel_cost_time_series, power_units, startup_fuel_offtake, value_curve, variable_cost_type, vom_cost, )
        o = new(fuel_cost, fuel_cost_time_series, power_units, startup_fuel_offtake, value_curve, variable_cost_type, vom_cost, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FuelCurve

const _property_types_FuelCurve = Dict{Symbol,Type}(Symbol("fuel_cost")=>Union{Nothing, Float64}, Symbol("fuel_cost_time_series")=>Union{Nothing, Int64}, Symbol("power_units")=>Union{Nothing, String}, Symbol("startup_fuel_offtake")=>Union{Nothing, InputOutputCurve}, Symbol("value_curve")=>Union{Nothing, ValueCurve}, Symbol("variable_cost_type")=>Union{Nothing, String}, Symbol("vom_cost")=>Union{Nothing, InputOutputCurve}, )
OpenAPI.property_type(::Type{ FuelCurve }, name::Symbol) = _property_types_FuelCurve[name]

function OpenAPI.check_required(o::FuelCurve)
    o.power_units === nothing && (return false)
    o.value_curve === nothing && (return false)
    o.variable_cost_type === nothing && (return false)
    o.vom_cost === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::FuelCurve)
    OpenAPI.validate_property(FuelCurve, Symbol("fuel_cost"), o.fuel_cost)
    OpenAPI.validate_property(FuelCurve, Symbol("fuel_cost_time_series"), o.fuel_cost_time_series)
    OpenAPI.validate_property(FuelCurve, Symbol("power_units"), o.power_units)
    OpenAPI.validate_property(FuelCurve, Symbol("startup_fuel_offtake"), o.startup_fuel_offtake)
    OpenAPI.validate_property(FuelCurve, Symbol("value_curve"), o.value_curve)
    OpenAPI.validate_property(FuelCurve, Symbol("variable_cost_type"), o.variable_cost_type)
    OpenAPI.validate_property(FuelCurve, Symbol("vom_cost"), o.vom_cost)
end

function OpenAPI.validate_property(::Type{ FuelCurve }, name::Symbol, val)



    if name === Symbol("power_units")
        OpenAPI.validate_param(name, "FuelCurve", :enum, val, ["COMPONENT_BASE", "NATURAL_UNITS"])
    end




    if name === Symbol("variable_cost_type")
        OpenAPI.validate_param(name, "FuelCurve", :enum, val, ["FUEL"])
    end


end
