# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeSeriesLinearFunctionData_1

    TimeSeriesLinearFunctionData1(;
        function_type="TIME_SERIES_LINEAR",
        association_id=nothing,
    )

    - function_type::String
    - association_id::Int64 : Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.
"""
Base.@kwdef mutable struct TimeSeriesLinearFunctionData1 <: OpenAPI.APIModel
    function_type::Union{Nothing, String} = "TIME_SERIES_LINEAR"
    association_id::Union{Nothing, Int64} = nothing

    function TimeSeriesLinearFunctionData1(function_type, association_id, )
        o = new(function_type, association_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TimeSeriesLinearFunctionData1

const _property_types_TimeSeriesLinearFunctionData1 = Dict{Symbol,Type}(Symbol("function_type")=>Union{Nothing, String}, Symbol("association_id")=>Union{Nothing, Int64}, )
OpenAPI.property_type(::Type{ TimeSeriesLinearFunctionData1 }, name::Symbol) = _property_types_TimeSeriesLinearFunctionData1[name]

function OpenAPI.check_required(o::TimeSeriesLinearFunctionData1)
    o.function_type === nothing && (return false)
    o.association_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TimeSeriesLinearFunctionData1)
    OpenAPI.validate_property(TimeSeriesLinearFunctionData1, Symbol("function_type"), o.function_type)
    OpenAPI.validate_property(TimeSeriesLinearFunctionData1, Symbol("association_id"), o.association_id)
end

function OpenAPI.validate_property(::Type{ TimeSeriesLinearFunctionData1 }, name::Symbol, val)

    if name === Symbol("function_type")
        OpenAPI.validate_param(name, "TimeSeriesLinearFunctionData1", :enum, val, ["TIME_SERIES_LINEAR"])
    end


end
