# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeographicInfo

    GeographicInfo(;
        id=nothing,
        geo_json=nothing,
    )

    - id::Int64
    - geo_json::Dict{String, Any}
"""
Base.@kwdef mutable struct GeographicInfo <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    geo_json::Union{Nothing, Dict{String, Any}} = nothing

    function GeographicInfo(id, geo_json, )
        o = new(id, geo_json, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GeographicInfo

const _property_types_GeographicInfo = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("geo_json")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ GeographicInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeographicInfo[name]))}

function OpenAPI.check_required(o::GeographicInfo)
    o.id === nothing && (return false)
    o.geo_json === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GeographicInfo)
    OpenAPI.validate_property(GeographicInfo, Symbol("id"), o.id)
    OpenAPI.validate_property(GeographicInfo, Symbol("geo_json"), o.geo_json)
end

function OpenAPI.validate_property(::Type{ GeographicInfo }, name::Symbol, val)


end
