# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SupplementalAttributeAssociation
Links a supplemental attribute, or a service acting as one, to the entity it describes or the member it contains. The type of either side is resolved through the entity registry rather than duplicated here, matching GridDB&#39;s &#x60;supplemental_attributes_association&#x60; table. Unlike &#x60;components&#x60;, &#x60;supplemental_attributes&#x60; is a flat, untyped array, so &#x60;attribute_type&#x60; is this record&#39;s type discriminator: it says what the row means and which optional fields apply. A plain supplemental attribute (e.g. EmissionsData, GeographicInfo) or a service membership uses neither &#x60;group_index&#x60; nor &#x60;role&#x60;. A ThermalPowerPlant, HydroPowerPlant, or RenewablePowerPlant row uses &#x60;group_index&#x60; for the shaft, penstock, or PCC number; a CombinedCycleBlock row uses &#x60;group_index&#x60; for the HRSG index and &#x60;role&#x60; for CT/CA; an exclusion-group row uses &#x60;group_index&#x60; for the exclusion group number. This one table replaces the four that used to express these relations separately (ServiceAssociation, PlantAssociation, CombinedCycleAssociation): a service association or a plant/combined-cycle association is a supplemental attribute association with the type-specific fields filled in, not a distinct kind of table. Lives in Core because either side may be a Core or an Operations type.

    SupplementalAttributeAssociation(;
        attribute_id=nothing,
        entity_id=nothing,
        attribute_type=nothing,
        group_index=nothing,
        role=nothing,
    )

    - attribute_id::Int64 : ID of the supplemental attribute, or of the service, for a membership row.
    - entity_id::Int64 : ID of the component, or other entity, that the attribute describes or the service contains.
    - attribute_type::String : Schema title of the referenced supplemental attribute or service (e.g. \&quot;EmissionsData\&quot;, \&quot;GeographicInfo\&quot;, \&quot;ThermalPowerPlant\&quot;, \&quot;CombinedCycleBlock\&quot;, \&quot;OnlineReserve\&quot;). A free-form string, not an enum: new attribute and service types are added elsewhere in this repo continuously, and a closed enum here would go stale.
    - group_index::Int64 : Optional group number within the parent named by attribute_id: the shaft/penstock/PCC number for a ThermalPowerPlant, HydroPowerPlant, or RenewablePowerPlant row, the HRSG index for a CombinedCycleBlock row, or the exclusion group number for an exclusion grouping. Omitted for a plain supplemental attribute or a service membership, neither of which has a group to index.
    - role::String : Optional role of entity_id within the parent named by attribute_id. Meaningful only for a CombinedCycleBlock row, where it is CT (combustion turbine) or CA (combustion-augmented steam); omitted for every other attribute_type.
"""
Base.@kwdef mutable struct SupplementalAttributeAssociation <: OpenAPI.APIModel
    attribute_id::Union{Nothing, Int64} = nothing
    entity_id::Union{Nothing, Int64} = nothing
    attribute_type::Union{Nothing, String} = nothing
    group_index::Union{Nothing, Int64} = nothing
    role::Union{Nothing, String} = nothing

    function SupplementalAttributeAssociation(attribute_id, entity_id, attribute_type, group_index, role, )
        o = new(attribute_id, entity_id, attribute_type, group_index, role, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SupplementalAttributeAssociation

const _property_types_SupplementalAttributeAssociation = Dict{Symbol,String}(Symbol("attribute_id")=>"Int64", Symbol("entity_id")=>"Int64", Symbol("attribute_type")=>"String", Symbol("group_index")=>"Int64", Symbol("role")=>"String", )
OpenAPI.property_type(::Type{ SupplementalAttributeAssociation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SupplementalAttributeAssociation[name]))}

function OpenAPI.check_required(o::SupplementalAttributeAssociation)
    o.attribute_id === nothing && (return false)
    o.entity_id === nothing && (return false)
    o.attribute_type === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SupplementalAttributeAssociation)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("attribute_id"), o.attribute_id)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("entity_id"), o.entity_id)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("attribute_type"), o.attribute_type)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("group_index"), o.group_index)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("role"), o.role)
end

function OpenAPI.validate_property(::Type{ SupplementalAttributeAssociation }, name::Symbol, val)





    if name === Symbol("role")
        OpenAPI.validate_param(name, "SupplementalAttributeAssociation", :enum, val, ["CT", "CA"])
    end

end
