# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

if !isdefined(@__MODULE__, :ImpedanceCorrectionTransformerControlMode)
    const ImpedanceCorrectionTransformerControlMode = String
else
    @warn("Skipping redefinition of ImpedanceCorrectionTransformerControlMode to String")
end
