# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

if !isdefined(@__MODULE__, :PrimeMovers)
    const PrimeMovers = String
else
    @warn("Skipping redefinition of PrimeMovers to String")
end
