# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""TwoTerminalLoss
Loss model of a two-terminal HVDC line as a function of flow, selected by &#x60;curve_type&#x60;. It accepts a linear model with a constant loss and a proportional loss rate (MW of loss per MW of flow), or a piecewise model giving different proportional losses on different flow segments.

    TwoTerminalLoss(; value=nothing)
"""
mutable struct TwoTerminalLoss <: OpenAPI.OneOfAPIModel
    value::Any # Union{ IncrementalCurve, InputOutputCurve }
    TwoTerminalLoss() = new()
    TwoTerminalLoss(value) = new(value)
end # type TwoTerminalLoss

function OpenAPI.property_type(::Type{ TwoTerminalLoss }, name::Symbol, json::Dict{String,Any})
    discriminator = json["curve_type"]
    if discriminator == "INCREMENTAL"
        return (IncrementalCurve)
    elseif discriminator == "INPUT_OUTPUT"
        return (InputOutputCurve)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for TwoTerminalLoss"))
end
