# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""HydroStorageGenerationCost
Operating cost of hydro generation with storage, selected by &#x60;cost_type&#x60; between the hydro generation (&#x60;HYDRO_GEN&#x60;) and storage (&#x60;STORAGE&#x60;) cost representations.

    HydroStorageGenerationCost(; value=nothing)
"""
mutable struct HydroStorageGenerationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ HydroGenerationCost, StorageCost }
    HydroStorageGenerationCost() = new()
    HydroStorageGenerationCost(value) = new(value)
end # type HydroStorageGenerationCost

function OpenAPI.property_type(::Type{ HydroStorageGenerationCost }, name::Symbol, json::Dict{String,Any})
    discriminator = json["cost_type"]
    if discriminator == "HYDRO_GEN"
        return (HydroGenerationCost)
    elseif discriminator == "STORAGE"
        return (StorageCost)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for HydroStorageGenerationCost"))
end
