# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StorageCapitalCost
Investment cost for candidate generation and transmission technologies which includes overnight capital costs and last-mile interconnection costs.

    StorageCapitalCost(;
        charge_capital_cost=nothing,
        discharge_capital_cost=nothing,
        energy_capital_cost=nothing,
        interconnection_cost=0.0,
    )

    - charge_capital_cost::ValueCurve
    - discharge_capital_cost::ValueCurve
    - energy_capital_cost::ValueCurve
    - interconnection_cost::Float64
"""
Base.@kwdef mutable struct StorageCapitalCost <: OpenAPI.APIModel
    charge_capital_cost = nothing # spec type: Union{ Nothing, ValueCurve }
    discharge_capital_cost = nothing # spec type: Union{ Nothing, ValueCurve }
    energy_capital_cost = nothing # spec type: Union{ Nothing, ValueCurve }
    interconnection_cost::Union{Nothing, Float64} = 0.0

    function StorageCapitalCost(charge_capital_cost, discharge_capital_cost, energy_capital_cost, interconnection_cost, )
        o = new(charge_capital_cost, discharge_capital_cost, energy_capital_cost, interconnection_cost, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type StorageCapitalCost

const _property_types_StorageCapitalCost = Dict{Symbol,Type}(Symbol("charge_capital_cost")=>Union{Nothing, ValueCurve}, Symbol("discharge_capital_cost")=>Union{Nothing, ValueCurve}, Symbol("energy_capital_cost")=>Union{Nothing, ValueCurve}, Symbol("interconnection_cost")=>Union{Nothing, Float64}, )
OpenAPI.property_type(::Type{ StorageCapitalCost }, name::Symbol) = _property_types_StorageCapitalCost[name]

function OpenAPI.check_required(o::StorageCapitalCost)
    o.charge_capital_cost === nothing && (return false)
    o.discharge_capital_cost === nothing && (return false)
    o.energy_capital_cost === nothing && (return false)
    o.interconnection_cost === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::StorageCapitalCost)
    OpenAPI.validate_property(StorageCapitalCost, Symbol("charge_capital_cost"), o.charge_capital_cost)
    OpenAPI.validate_property(StorageCapitalCost, Symbol("discharge_capital_cost"), o.discharge_capital_cost)
    OpenAPI.validate_property(StorageCapitalCost, Symbol("energy_capital_cost"), o.energy_capital_cost)
    OpenAPI.validate_property(StorageCapitalCost, Symbol("interconnection_cost"), o.interconnection_cost)
end

function OpenAPI.validate_property(::Type{ StorageCapitalCost }, name::Symbol, val)




end
