# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeSeriesAssociation
Metadata linking a time series dataset to a component.

    TimeSeriesAssociation(;
        id=nothing,
        time_series_uuid=nothing,
        time_series_type=nothing,
        initial_timestamp=nothing,
        resolution=nothing,
        horizon=nothing,
        interval=nothing,
        window_count=nothing,
        length=nothing,
        name=nothing,
        owner_id=nothing,
        owner_type=nothing,
        owner_category=nothing,
        features=nothing,
        scaling_factor_multiplier=nothing,
        metadata_uuid=nothing,
        units=nothing,
    )

    - id::Int64
    - time_series_uuid::String : UUID of the time series data. May reference inline data or an external store (e.g., HDF5).
    - time_series_type::String
    - initial_timestamp::ZonedDateTime
    - resolution::String : ISO 8601 duration (e.g., PT1H, PT5M).
    - horizon::String : ISO 8601 duration for forecast horizon.
    - interval::String : ISO 8601 duration for forecast interval.
    - window_count::Int64
    - length::Int64
    - name::String : Time series name (e.g., max_active_power).
    - owner_id::Int64 : ID of the owning component.
    - owner_type::String : Type name of the owning component.
    - owner_category::String : Whether the owner is component or supplemental attribute
    - features::Vector{Dict{String, FeatureValue}}
    - scaling_factor_multiplier::String : Dot-encoded function name like PowerSystems.get_max_active_power.
    - metadata_uuid::String : Usually unique for each association, but not necessarily
    - units::String
"""
Base.@kwdef mutable struct TimeSeriesAssociation <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    time_series_uuid::Union{Nothing, String} = nothing
    time_series_type::Union{Nothing, String} = nothing
    initial_timestamp::Union{Nothing, ZonedDateTime} = nothing
    resolution::Union{Nothing, String} = nothing
    horizon::Union{Nothing, String} = nothing
    interval::Union{Nothing, String} = nothing
    window_count::Union{Nothing, Int64} = nothing
    length::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    owner_id::Union{Nothing, Int64} = nothing
    owner_type::Union{Nothing, String} = nothing
    owner_category::Union{Nothing, String} = nothing
    features::Union{Nothing, Vector{Dict{String, FeatureValue}}} = nothing
    scaling_factor_multiplier::Union{Nothing, String} = nothing
    metadata_uuid::Union{Nothing, String} = nothing
    units::Union{Nothing, String} = nothing

    function TimeSeriesAssociation(id, time_series_uuid, time_series_type, initial_timestamp, resolution, horizon, interval, window_count, length, name, owner_id, owner_type, owner_category, features, scaling_factor_multiplier, metadata_uuid, units, )
        o = new(id, time_series_uuid, time_series_type, initial_timestamp, resolution, horizon, interval, window_count, length, name, owner_id, owner_type, owner_category, features, scaling_factor_multiplier, metadata_uuid, units, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TimeSeriesAssociation

const _property_types_TimeSeriesAssociation = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("time_series_uuid")=>"String", Symbol("time_series_type")=>"String", Symbol("initial_timestamp")=>"ZonedDateTime", Symbol("resolution")=>"String", Symbol("horizon")=>"String", Symbol("interval")=>"String", Symbol("window_count")=>"Int64", Symbol("length")=>"Int64", Symbol("name")=>"String", Symbol("owner_id")=>"Int64", Symbol("owner_type")=>"String", Symbol("owner_category")=>"String", Symbol("features")=>"Vector{Dict{String, FeatureValue}}", Symbol("scaling_factor_multiplier")=>"String", Symbol("metadata_uuid")=>"String", Symbol("units")=>"String", )
OpenAPI.property_type(::Type{ TimeSeriesAssociation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeSeriesAssociation[name]))}

function OpenAPI.check_required(o::TimeSeriesAssociation)
    o.id === nothing && (return false)
    o.time_series_uuid === nothing && (return false)
    o.time_series_type === nothing && (return false)
    o.initial_timestamp === nothing && (return false)
    o.resolution === nothing && (return false)
    o.name === nothing && (return false)
    o.owner_id === nothing && (return false)
    o.owner_type === nothing && (return false)
    o.owner_category === nothing && (return false)
    o.features === nothing && (return false)
    o.metadata_uuid === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TimeSeriesAssociation)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("id"), o.id)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("time_series_uuid"), o.time_series_uuid)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("time_series_type"), o.time_series_type)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("initial_timestamp"), o.initial_timestamp)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("resolution"), o.resolution)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("horizon"), o.horizon)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("interval"), o.interval)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("window_count"), o.window_count)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("length"), o.length)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("name"), o.name)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("owner_id"), o.owner_id)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("owner_type"), o.owner_type)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("owner_category"), o.owner_category)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("features"), o.features)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("scaling_factor_multiplier"), o.scaling_factor_multiplier)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("metadata_uuid"), o.metadata_uuid)
    OpenAPI.validate_property(TimeSeriesAssociation, Symbol("units"), o.units)
end

function OpenAPI.validate_property(::Type{ TimeSeriesAssociation }, name::Symbol, val)


    if name === Symbol("time_series_uuid")
        OpenAPI.validate_param(name, "TimeSeriesAssociation", :format, val, "uuid")
    end


    if name === Symbol("initial_timestamp")
        OpenAPI.validate_param(name, "TimeSeriesAssociation", :format, val, "date-time")
    end









    if name === Symbol("owner_category")
        OpenAPI.validate_param(name, "TimeSeriesAssociation", :enum, val, ["Component", "SupplementalAttribute"])
    end




    if name === Symbol("metadata_uuid")
        OpenAPI.validate_param(name, "TimeSeriesAssociation", :format, val, "uuid")
    end

end
