# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""FunctionData_2
Only TIME_SERIES_LINEAR or TIME_SERIES_PIECEWISE_STEP is admissible here; all other FunctionData variants, static or time-series-backed, are rejected by the consuming constructor.

    FunctionData2(; value=nothing)
"""
mutable struct FunctionData2 <: OpenAPI.OneOfAPIModel
    value::Any # Union{ LinearFunctionData, PiecewiseLinearData, PiecewiseStepData, QuadraticFunctionData, TimeSeriesLinearFunctionData1, TimeSeriesPiecewiseLinearData1, TimeSeriesPiecewiseStepData1, TimeSeriesQuadraticFunctionData1 }
    FunctionData2() = new()
    FunctionData2(value) = new(value)
end # type FunctionData2

function OpenAPI.property_type(::Type{ FunctionData2 }, name::Symbol, json::Dict{String,Any})
    discriminator = json["function_type"]
    if discriminator == "LINEAR"
        return (LinearFunctionData)
    elseif discriminator == "PIECEWISE_LINEAR"
        return (PiecewiseLinearData)
    elseif discriminator == "PIECEWISE_STEP"
        return (PiecewiseStepData)
    elseif discriminator == "QUADRATIC"
        return (QuadraticFunctionData)
    elseif discriminator == "TIME_SERIES_LINEAR"
        return (TimeSeriesLinearFunctionData)
    elseif discriminator == "TIME_SERIES_PIECEWISE_LINEAR"
        return (TimeSeriesPiecewiseLinearData)
    elseif discriminator == "TIME_SERIES_PIECEWISE_STEP"
        return (TimeSeriesPiecewiseStepData)
    elseif discriminator == "TIME_SERIES_QUADRATIC"
        return (TimeSeriesQuadraticFunctionData)
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for FunctionData2"))
end
