# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IncrementalCurve
A curve whose y values are the marginal rate &#x60;f&#39;(x)&#x60; at production level &#x60;x&#x60; — the native form for market bid stacks and incremental heat rate data. &#x60;initial_input&#x60; records the total input at the minimum production point, anchoring the absolute level and enabling conversion to an &#x60;InputOutputCurve&#x60;. Use &#x60;InputOutputCurve&#x60; when the data gives total cost at each output level.

    IncrementalCurve(;
        curve_type="INCREMENTAL",
        function_data=nothing,
        initial_input=nothing,
        input_at_zero=nothing,
    )

    - curve_type::String
    - function_data::IncrementalCurveFunctionData
    - initial_input::Float64
    - input_at_zero::Float64
"""
Base.@kwdef mutable struct IncrementalCurve <: OpenAPI.APIModel
    curve_type::Union{Nothing, String} = "INCREMENTAL"
    function_data = nothing # spec type: Union{ Nothing, IncrementalCurveFunctionData }
    initial_input::Union{Nothing, Float64} = nothing
    input_at_zero::Union{Nothing, Float64} = nothing

    function IncrementalCurve(curve_type, function_data, initial_input, input_at_zero, )
        o = new(curve_type, function_data, initial_input, input_at_zero, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type IncrementalCurve

const _property_types_IncrementalCurve = Dict{Symbol,Type}(Symbol("curve_type")=>Union{Nothing, String}, Symbol("function_data")=>Union{Nothing, IncrementalCurveFunctionData}, Symbol("initial_input")=>Union{Nothing, Float64}, Symbol("input_at_zero")=>Union{Nothing, Float64}, )
OpenAPI.property_type(::Type{ IncrementalCurve }, name::Symbol) = _property_types_IncrementalCurve[name]

function OpenAPI.check_required(o::IncrementalCurve)
    o.curve_type === nothing && (return false)
    o.function_data === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::IncrementalCurve)
    OpenAPI.validate_property(IncrementalCurve, Symbol("curve_type"), o.curve_type)
    OpenAPI.validate_property(IncrementalCurve, Symbol("function_data"), o.function_data)
    OpenAPI.validate_property(IncrementalCurve, Symbol("initial_input"), o.initial_input)
    OpenAPI.validate_property(IncrementalCurve, Symbol("input_at_zero"), o.input_at_zero)
end

function OpenAPI.validate_property(::Type{ IncrementalCurve }, name::Symbol, val)

    if name === Symbol("curve_type")
        OpenAPI.validate_param(name, "IncrementalCurve", :enum, val, ["INCREMENTAL"])
    end




end
