# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :AdmittanceUnitBasis)
    const AdmittanceUnitBasis = String
else
    @warn("Skipping redefinition of AdmittanceUnitBasis to String")
end
