# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CapitalCost
Investment cost for candidate generation and transmission technologies which includes overnight capital costs and last-mile interconnection costs.

    CapitalCost(;
        capital_cost=nothing,
        interconnection_cost=0.0,
    )

    - capital_cost::ValueCurve
    - interconnection_cost::Float64
"""
Base.@kwdef mutable struct CapitalCost <: OpenAPI.APIModel
    capital_cost = nothing # spec type: Union{ Nothing, ValueCurve }
    interconnection_cost::Union{Nothing, Float64} = 0.0

    function CapitalCost(capital_cost, interconnection_cost, )
        o = new(capital_cost, interconnection_cost, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CapitalCost

const _property_types_CapitalCost = Dict{Symbol,Type}(Symbol("capital_cost")=>Union{Nothing, ValueCurve}, Symbol("interconnection_cost")=>Union{Nothing, Float64}, )
OpenAPI.property_type(::Type{ CapitalCost }, name::Symbol) = _property_types_CapitalCost[name]

function OpenAPI.check_required(o::CapitalCost)
    o.capital_cost === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::CapitalCost)
    OpenAPI.validate_property(CapitalCost, Symbol("capital_cost"), o.capital_cost)
    OpenAPI.validate_property(CapitalCost, Symbol("interconnection_cost"), o.interconnection_cost)
end

function OpenAPI.validate_property(::Type{ CapitalCost }, name::Symbol, val)


end
