# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SupplementalAttributeAssociation
Links a supplemental attribute to the entity it describes. The type of either side is resolved through the entity registry rather than duplicated here, matching GridDB&#39;s &#x60;supplemental_attributes_association&#x60; table. Lives in Core because either side may be a Core or an Operations type. Unlike &#x60;components&#x60;, &#x60;supplemental_attributes&#x60; is a flat, untyped array, so &#x60;attribute_type&#x60; is this record&#39;s only per-row type discriminator.

    SupplementalAttributeAssociation(;
        attribute_id=nothing,
        entity_id=nothing,
        attribute_type=nothing,
    )

    - attribute_id::Int64 : ID of the supplemental attribute.
    - entity_id::Int64 : ID of the component the attribute describes.
    - attribute_type::String : Schema title of the referenced supplemental attribute (e.g. \&quot;EmissionsData\&quot;, \&quot;GeographicInfo\&quot;). A free-form string, not an enum: new attribute types are added elsewhere in this repo continuously, and a closed enum here would go stale.
"""
Base.@kwdef mutable struct SupplementalAttributeAssociation <: OpenAPI.APIModel
    attribute_id::Union{Nothing, Int64} = nothing
    entity_id::Union{Nothing, Int64} = nothing
    attribute_type::Union{Nothing, String} = nothing

    function SupplementalAttributeAssociation(attribute_id, entity_id, attribute_type, )
        o = new(attribute_id, entity_id, attribute_type, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SupplementalAttributeAssociation

const _property_types_SupplementalAttributeAssociation = Dict{Symbol,String}(Symbol("attribute_id")=>"Int64", Symbol("entity_id")=>"Int64", Symbol("attribute_type")=>"String", )
OpenAPI.property_type(::Type{ SupplementalAttributeAssociation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SupplementalAttributeAssociation[name]))}

function OpenAPI.check_required(o::SupplementalAttributeAssociation)
    o.attribute_id === nothing && (return false)
    o.entity_id === nothing && (return false)
    o.attribute_type === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SupplementalAttributeAssociation)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("attribute_id"), o.attribute_id)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("entity_id"), o.entity_id)
    OpenAPI.validate_property(SupplementalAttributeAssociation, Symbol("attribute_type"), o.attribute_type)
end

function OpenAPI.validate_property(::Type{ SupplementalAttributeAssociation }, name::Symbol, val)



end
