# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeSeriesPiecewiseStepData

    TimeSeriesPiecewiseStepData(;
        function_type="TIME_SERIES_PIECEWISE_STEP",
        association_id=nothing,
    )

    - function_type::String
    - association_id::Int64 : Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.
"""
Base.@kwdef mutable struct TimeSeriesPiecewiseStepData <: OpenAPI.APIModel
    function_type::Union{Nothing, String} = "TIME_SERIES_PIECEWISE_STEP"
    association_id::Union{Nothing, Int64} = nothing

    function TimeSeriesPiecewiseStepData(function_type, association_id, )
        o = new(function_type, association_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TimeSeriesPiecewiseStepData

const _property_types_TimeSeriesPiecewiseStepData = Dict{Symbol,Type}(Symbol("function_type")=>Union{Nothing, String}, Symbol("association_id")=>Union{Nothing, Int64}, )
OpenAPI.property_type(::Type{ TimeSeriesPiecewiseStepData }, name::Symbol) = _property_types_TimeSeriesPiecewiseStepData[name]

function OpenAPI.check_required(o::TimeSeriesPiecewiseStepData)
    o.function_type === nothing && (return false)
    o.association_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TimeSeriesPiecewiseStepData)
    OpenAPI.validate_property(TimeSeriesPiecewiseStepData, Symbol("function_type"), o.function_type)
    OpenAPI.validate_property(TimeSeriesPiecewiseStepData, Symbol("association_id"), o.association_id)
end

function OpenAPI.validate_property(::Type{ TimeSeriesPiecewiseStepData }, name::Symbol, val)

    if name === Symbol("function_type")
        OpenAPI.validate_param(name, "TimeSeriesPiecewiseStepData", :enum, val, ["TIME_SERIES_PIECEWISE_STEP"])
    end


end
