# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""StorageTechnology_capacity_limits_discharge
Allowable installed power capacity for discharging of a storage technology, given either as a single bound applied to all capacity or as a mapping from a float key (stringified) to the bound that applies at that key. Units: MW.

    StorageTechnologyCapacityLimitsDischarge(; value=nothing)
"""
mutable struct StorageTechnologyCapacityLimitsDischarge <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Dict{String, MinMax}, MinMax }
    StorageTechnologyCapacityLimitsDischarge() = new()
    StorageTechnologyCapacityLimitsDischarge(value) = new(value)
end # type StorageTechnologyCapacityLimitsDischarge

function OpenAPI.property_type(::Type{ StorageTechnologyCapacityLimitsDischarge }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(StorageTechnologyCapacityLimitsDischarge, name)
end
