# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TechnologyFinancialData
Struct containing relevant financial information for a technology.

    TechnologyFinancialData(;
        capital_recovery_period=nothing,
        technology_base_year=nothing,
        debt_fraction=nothing,
        debt_rate=nothing,
        return_on_equity=nothing,
        tax_rate=nothing,
    )

    - capital_recovery_period::Int64 : Period over which capital costs are recovered for net present value calculations. Units: yr.
    - technology_base_year::Int64 : Base year for technology cost data used in NPV calculations.
    - debt_fraction::Float64 : Fraction of capital costs financed through debt. Units: 1.
    - debt_rate::Float64 : Interest rate on debt financing. Units: 1.
    - return_on_equity::Float64 : Required rate of return on equity financing. Units: 1.
    - tax_rate::Float64 : Tax rate applied to equity returns. Units: 1.
"""
Base.@kwdef mutable struct TechnologyFinancialData <: OpenAPI.APIModel
    capital_recovery_period::Union{Nothing, Int64} = nothing
    technology_base_year::Union{Nothing, Int64} = nothing
    debt_fraction::Union{Nothing, Float64} = nothing
    debt_rate::Union{Nothing, Float64} = nothing
    return_on_equity::Union{Nothing, Float64} = nothing
    tax_rate::Union{Nothing, Float64} = nothing

    function TechnologyFinancialData(capital_recovery_period, technology_base_year, debt_fraction, debt_rate, return_on_equity, tax_rate, )
        o = new(capital_recovery_period, technology_base_year, debt_fraction, debt_rate, return_on_equity, tax_rate, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TechnologyFinancialData

const _property_types_TechnologyFinancialData = Dict{Symbol,Type}(Symbol("capital_recovery_period")=>Union{Nothing, Int64}, Symbol("technology_base_year")=>Union{Nothing, Int64}, Symbol("debt_fraction")=>Union{Nothing, Float64}, Symbol("debt_rate")=>Union{Nothing, Float64}, Symbol("return_on_equity")=>Union{Nothing, Float64}, Symbol("tax_rate")=>Union{Nothing, Float64}, )
OpenAPI.property_type(::Type{ TechnologyFinancialData }, name::Symbol) = _property_types_TechnologyFinancialData[name]

function OpenAPI.check_required(o::TechnologyFinancialData)
    o.capital_recovery_period === nothing && (return false)
    o.technology_base_year === nothing && (return false)
    o.debt_fraction === nothing && (return false)
    o.debt_rate === nothing && (return false)
    o.return_on_equity === nothing && (return false)
    o.tax_rate === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TechnologyFinancialData)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("capital_recovery_period"), o.capital_recovery_period)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("technology_base_year"), o.technology_base_year)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("debt_fraction"), o.debt_fraction)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("debt_rate"), o.debt_rate)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("return_on_equity"), o.return_on_equity)
    OpenAPI.validate_property(TechnologyFinancialData, Symbol("tax_rate"), o.tax_rate)
end

function OpenAPI.validate_property(::Type{ TechnologyFinancialData }, name::Symbol, val)






end
