# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExistingDevices
Supplemental attribute mapping a technology in the portfolio to the existing system — for example, the list of existing generators that correspond to one supply technology.

    ExistingDevices(;
        id=nothing,
        existing_devices=nothing,
    )

    - id::Int64 : ID for individual component.
    - existing_devices::Vector{String} : List of individual existing devices to map to a specific technology in the portfolio.
"""
Base.@kwdef mutable struct ExistingDevices <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    existing_devices::Union{Nothing, Vector{String}} = nothing

    function ExistingDevices(id, existing_devices, )
        o = new(id, existing_devices, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ExistingDevices

const _property_types_ExistingDevices = Dict{Symbol,Type}(Symbol("id")=>Union{Nothing, Int64}, Symbol("existing_devices")=>Union{Nothing, Vector{String}}, )
OpenAPI.property_type(::Type{ ExistingDevices }, name::Symbol) = _property_types_ExistingDevices[name]

function OpenAPI.check_required(o::ExistingDevices)
    o.id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ExistingDevices)
    OpenAPI.validate_property(ExistingDevices, Symbol("id"), o.id)
    OpenAPI.validate_property(ExistingDevices, Symbol("existing_devices"), o.existing_devices)
end

function OpenAPI.validate_property(::Type{ ExistingDevices }, name::Symbol, val)


end
