# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Scenarios
A scenarios forecast: per-scenario, per-window horizon arrays. Adds a scenario axis in front of the deterministic layout.

    Scenarios(;
        id=nothing,
        owner_id=nothing,
        owner_type=nothing,
        owner_category=nothing,
        time_series_type="Scenarios",
        name=nothing,
        features=nothing,
        address=nothing,
        element_type=nothing,
        element_shape=nothing,
        units=nothing,
        quantity_kind=nothing,
        unit_system=nothing,
        component_field=nothing,
        application_data=nothing,
        initial_timestamp=nothing,
        resolution=nothing,
        horizon=nothing,
        interval=nothing,
        count=nothing,
        scenario_count=nothing,
    )

    - id::Int64 : Surrogate primary key of the association row (&#x60;id INTEGER PRIMARY KEY&#x60; in infrastore&#39;s catalog). Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).
    - owner_id::Int64 : ID of the owning component or supplemental attribute. Component and supplemental-attribute id streams are independent, so &#x60;owner_category&#x60; is what disambiguates an &#x60;owner_id&#x60; reused across the two.
    - owner_type::String : Type name of the owning entity. Descriptive, not part of the series&#39; identity.
    - owner_category::String : Whether the owner is a component or a supplemental attribute.
    - time_series_type::String : Discriminator. Fixed to Scenarios for this schema, pinned with &#x60;const&#x60; to match this repo&#39;s existing discriminators (Core/common.json&#39;s &#x60;curve_type&#x60;), which generate a plain string literal in both toolchains.
    - name::String : Time series name (e.g. max_active_power). Part of the series&#39; identity, and often carrying a disambiguating suffix; &#x60;component_field&#x60; records what the values are for.
    - features::Dict{String, TimeSeriesFeatureValue} : User-defined key/value tags that are part of the series&#39; identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.
    - address::String : Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; in Sienna, infrastore resolves it. This layer records where the values are, never the values.
    - element_type::String : What one timestep&#39;s values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike &#x60;units&#x60; and &#x60;quantity_kind&#x60; this is not a user-facing label — the writing package derives it from the array.
    - element_shape::Vector{Int64} : Per-step element shape: the trailing dims after time. An empty array means a scalar element.
    - units::String : Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series&#39; identity, so two series differing only in this label are duplicates. Meaningless on its own when &#x60;unit_system&#x60; is a per-unit basis, where the values are dimensionless.
    - quantity_kind::String : Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than &#x60;units&#x60; but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when &#x60;unit_system&#x60; is a per-unit basis.
    - unit_system::String : Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component&#39;s base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.
    - component_field::String : The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer&#39;s own object model. Records what the values are for, where &#x60;name&#x60; only says which series they are.
    - application_data::String : Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is &#x60;element_type&#x60;.
    - initial_timestamp::ZonedDateTime : Start of the first forecast window.
    - resolution::String : Cadence within a forecast window. Always present for a forecast, and part of the series&#39; identity.
    - horizon::String : Length of one forecast window. Descriptive, not part of the series&#39; identity.
    - interval::String : Step between the start of consecutive forecast windows. Part of the series&#39; identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. &#x60;PT0S&#x60; is the canonical interval of a single-window forecast, which has no second window to step to.
    - count::Int64 : Number of forecast windows. Descriptive, not part of the series&#39; identity.
    - scenario_count::Int64 : Number of scenarios, one per leading axis entry of the stored array. infrastore&#39;s catalog has no column for this and reads it off the array&#39;s shape; it is recorded explicitly here because this layer carries no array.
"""
Base.@kwdef mutable struct Scenarios <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    owner_id::Union{Nothing, Int64} = nothing
    owner_type::Union{Nothing, String} = nothing
    owner_category::Union{Nothing, String} = nothing
    time_series_type::Union{Nothing, String} = "Scenarios"
    name::Union{Nothing, String} = nothing
    features::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, TimeSeriesFeatureValue} }
    address::Union{Nothing, String} = nothing
    element_type::Union{Nothing, String} = nothing
    element_shape::Union{Nothing, Vector{Int64}} = nothing
    units::Union{Nothing, String} = nothing
    quantity_kind::Union{Nothing, String} = nothing
    unit_system::Union{Nothing, String} = nothing
    component_field::Union{Nothing, String} = nothing
    application_data::Union{Nothing, String} = nothing
    initial_timestamp::Union{Nothing, ZonedDateTime} = nothing
    resolution::Union{Nothing, String} = nothing
    horizon::Union{Nothing, String} = nothing
    interval::Union{Nothing, String} = nothing
    count::Union{Nothing, Int64} = nothing
    scenario_count::Union{Nothing, Int64} = nothing

    function Scenarios(id, owner_id, owner_type, owner_category, time_series_type, name, features, address, element_type, element_shape, units, quantity_kind, unit_system, component_field, application_data, initial_timestamp, resolution, horizon, interval, count, scenario_count, )
        o = new(id, owner_id, owner_type, owner_category, time_series_type, name, features, address, element_type, element_shape, units, quantity_kind, unit_system, component_field, application_data, initial_timestamp, resolution, horizon, interval, count, scenario_count, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Scenarios

const _property_types_Scenarios = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("owner_id")=>"Int64", Symbol("owner_type")=>"String", Symbol("owner_category")=>"String", Symbol("time_series_type")=>"String", Symbol("name")=>"String", Symbol("features")=>"Dict{String, TimeSeriesFeatureValue}", Symbol("address")=>"String", Symbol("element_type")=>"String", Symbol("element_shape")=>"Vector{Int64}", Symbol("units")=>"String", Symbol("quantity_kind")=>"String", Symbol("unit_system")=>"String", Symbol("component_field")=>"String", Symbol("application_data")=>"String", Symbol("initial_timestamp")=>"ZonedDateTime", Symbol("resolution")=>"String", Symbol("horizon")=>"String", Symbol("interval")=>"String", Symbol("count")=>"Int64", Symbol("scenario_count")=>"Int64", )
OpenAPI.property_type(::Type{ Scenarios }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Scenarios[name]))}

function OpenAPI.check_required(o::Scenarios)
    o.id === nothing && (return false)
    o.owner_id === nothing && (return false)
    o.owner_type === nothing && (return false)
    o.owner_category === nothing && (return false)
    o.time_series_type === nothing && (return false)
    o.name === nothing && (return false)
    o.features === nothing && (return false)
    o.address === nothing && (return false)
    o.element_type === nothing && (return false)
    o.element_shape === nothing && (return false)
    o.initial_timestamp === nothing && (return false)
    o.resolution === nothing && (return false)
    o.horizon === nothing && (return false)
    o.interval === nothing && (return false)
    o.count === nothing && (return false)
    o.scenario_count === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Scenarios)
    OpenAPI.validate_property(Scenarios, Symbol("id"), o.id)
    OpenAPI.validate_property(Scenarios, Symbol("owner_id"), o.owner_id)
    OpenAPI.validate_property(Scenarios, Symbol("owner_type"), o.owner_type)
    OpenAPI.validate_property(Scenarios, Symbol("owner_category"), o.owner_category)
    OpenAPI.validate_property(Scenarios, Symbol("time_series_type"), o.time_series_type)
    OpenAPI.validate_property(Scenarios, Symbol("name"), o.name)
    OpenAPI.validate_property(Scenarios, Symbol("features"), o.features)
    OpenAPI.validate_property(Scenarios, Symbol("address"), o.address)
    OpenAPI.validate_property(Scenarios, Symbol("element_type"), o.element_type)
    OpenAPI.validate_property(Scenarios, Symbol("element_shape"), o.element_shape)
    OpenAPI.validate_property(Scenarios, Symbol("units"), o.units)
    OpenAPI.validate_property(Scenarios, Symbol("quantity_kind"), o.quantity_kind)
    OpenAPI.validate_property(Scenarios, Symbol("unit_system"), o.unit_system)
    OpenAPI.validate_property(Scenarios, Symbol("component_field"), o.component_field)
    OpenAPI.validate_property(Scenarios, Symbol("application_data"), o.application_data)
    OpenAPI.validate_property(Scenarios, Symbol("initial_timestamp"), o.initial_timestamp)
    OpenAPI.validate_property(Scenarios, Symbol("resolution"), o.resolution)
    OpenAPI.validate_property(Scenarios, Symbol("horizon"), o.horizon)
    OpenAPI.validate_property(Scenarios, Symbol("interval"), o.interval)
    OpenAPI.validate_property(Scenarios, Symbol("count"), o.count)
    OpenAPI.validate_property(Scenarios, Symbol("scenario_count"), o.scenario_count)
end

function OpenAPI.validate_property(::Type{ Scenarios }, name::Symbol, val)




    if name === Symbol("owner_category")
        OpenAPI.validate_param(name, "Scenarios", :enum, val, ["Component", "SupplementalAttribute"])
    end


    if name === Symbol("time_series_type")
        OpenAPI.validate_param(name, "Scenarios", :enum, val, ["Scenarios"])
    end









    if name === Symbol("unit_system")
        OpenAPI.validate_param(name, "Scenarios", :enum, val, ["COMPONENT_BASE", "NATURAL_UNITS"])
    end




    if name === Symbol("initial_timestamp")
        OpenAPI.validate_param(name, "Scenarios", :format, val, "date-time")
    end




    if name === Symbol("count")
        OpenAPI.validate_param(name, "Scenarios", :minimum, val, 0, false)
    end

    if name === Symbol("scenario_count")
        OpenAPI.validate_param(name, "Scenarios", :minimum, val, 1, false)
    end
end
