# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Probabilistic
A probabilistic forecast: per-percentile, per-window horizon arrays. Adds a percentile axis in front of the deterministic layout.

    Probabilistic(;
        id=nothing,
        owner_id=nothing,
        owner_type=nothing,
        owner_category=nothing,
        time_series_type="Probabilistic",
        name=nothing,
        features=nothing,
        uri=nothing,
        data_hash=nothing,
        element_type=nothing,
        element_shape=nothing,
        units=nothing,
        quantity_kind=nothing,
        unit_system=nothing,
        component_field=nothing,
        application_data=nothing,
        initial_timestamp=nothing,
        resolution=nothing,
        horizon=nothing,
        interval=nothing,
        count=nothing,
        percentiles=nothing,
    )

    - id::Int64 : Surrogate primary key of the association row, the store&#39;s catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).
    - owner_id::Int64 : ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an &#x60;owner_id&#x60; never collides across the two categories; &#x60;owner_category&#x60; remains required because the store&#39;s catalog contract still supports independent streams from other producers, and it is still the store&#39;s disambiguator.
    - owner_type::String : Type name of the owning entity. Descriptive, not part of the series&#39; identity.
    - owner_category::String : Whether the owner is a component or a supplemental attribute.
    - time_series_type::String : Discriminator. Fixed to Probabilistic for this schema, pinned with &#x60;const&#x60; to match this repo&#39;s existing discriminators (Core/common.json&#39;s &#x60;curve_type&#x60;), which generate a plain string literal in both toolchains.
    - name::String : Time series name (e.g. max_active_power). Part of the series&#39; identity, and often carrying a disambiguating suffix; &#x60;component_field&#x60; records what the values are for.
    - features::Dict{String, TimeSeriesFeatureValue} : User-defined key/value tags that are part of the series&#39; identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.
    - uri::String : Locator for the dense data, unique within one store. No required format — typically a file path or an HDF5 dataset path; the backing store decides what it means and resolves it (infrastore uses its content hash as this value). Never parsed or interpreted here. This layer records where the values are, never the values.
    - data_hash::String : Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.
    - element_type::String : What one timestep&#39;s values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike &#x60;units&#x60; and &#x60;quantity_kind&#x60; this is not a user-facing label — the writing package derives it from the array.
    - element_shape::Vector{Int64} : Per-step element shape: the trailing dims after time. An empty array means a scalar element.
    - units::String : Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series&#39; identity, so two series differing only in this label are duplicates. Meaningless on its own when &#x60;unit_system&#x60; is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.
    - quantity_kind::String : Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than &#x60;units&#x60; but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when &#x60;unit_system&#x60; is a per-unit basis.
    - unit_system::String : Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component&#39;s base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.
    - component_field::String : The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer&#39;s own object model. Records what the values are for, where &#x60;name&#x60; only says which series they are.
    - application_data::String : Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is &#x60;element_type&#x60;.
    - initial_timestamp::ZonedDateTime : Start of the first forecast window.
    - resolution::String : Cadence within a forecast window. Always present for a forecast, and part of the series&#39; identity.
    - horizon::String : Length of one forecast window. Descriptive, not part of the series&#39; identity.
    - interval::String : Step between the start of consecutive forecast windows. Part of the series&#39; identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. &#x60;PT0S&#x60; is the canonical interval of a single-window forecast, which has no second window to step to.
    - count::Int64 : Number of forecast windows. Descriptive, not part of the series&#39; identity.
    - percentiles::Vector{Float64} : The percentiles this forecast carries, one per leading axis entry of the stored array.
"""
Base.@kwdef mutable struct Probabilistic <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    owner_id::Union{Nothing, Int64} = nothing
    owner_type::Union{Nothing, String} = nothing
    owner_category::Union{Nothing, String} = nothing
    time_series_type::Union{Nothing, String} = "Probabilistic"
    name::Union{Nothing, String} = nothing
    features::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, TimeSeriesFeatureValue} }
    uri::Union{Nothing, String} = nothing
    data_hash::Union{Nothing, String} = nothing
    element_type::Union{Nothing, String} = nothing
    element_shape::Union{Nothing, Vector{Int64}} = nothing
    units::Union{Nothing, String} = nothing
    quantity_kind::Union{Nothing, String} = nothing
    unit_system::Union{Nothing, String} = nothing
    component_field::Union{Nothing, String} = nothing
    application_data::Union{Nothing, String} = nothing
    initial_timestamp::Union{Nothing, ZonedDateTime} = nothing
    resolution::Union{Nothing, String} = nothing
    horizon::Union{Nothing, String} = nothing
    interval::Union{Nothing, String} = nothing
    count::Union{Nothing, Int64} = nothing
    percentiles::Union{Nothing, Vector{Float64}} = nothing

    function Probabilistic(id, owner_id, owner_type, owner_category, time_series_type, name, features, uri, data_hash, element_type, element_shape, units, quantity_kind, unit_system, component_field, application_data, initial_timestamp, resolution, horizon, interval, count, percentiles, )
        o = new(id, owner_id, owner_type, owner_category, time_series_type, name, features, uri, data_hash, element_type, element_shape, units, quantity_kind, unit_system, component_field, application_data, initial_timestamp, resolution, horizon, interval, count, percentiles, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Probabilistic

const _property_types_Probabilistic = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("owner_id")=>"Int64", Symbol("owner_type")=>"String", Symbol("owner_category")=>"String", Symbol("time_series_type")=>"String", Symbol("name")=>"String", Symbol("features")=>"Dict{String, TimeSeriesFeatureValue}", Symbol("uri")=>"String", Symbol("data_hash")=>"String", Symbol("element_type")=>"String", Symbol("element_shape")=>"Vector{Int64}", Symbol("units")=>"String", Symbol("quantity_kind")=>"String", Symbol("unit_system")=>"String", Symbol("component_field")=>"String", Symbol("application_data")=>"String", Symbol("initial_timestamp")=>"ZonedDateTime", Symbol("resolution")=>"String", Symbol("horizon")=>"String", Symbol("interval")=>"String", Symbol("count")=>"Int64", Symbol("percentiles")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ Probabilistic }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Probabilistic[name]))}

function OpenAPI.check_required(o::Probabilistic)
    o.id === nothing && (return false)
    o.owner_id === nothing && (return false)
    o.owner_type === nothing && (return false)
    o.owner_category === nothing && (return false)
    o.time_series_type === nothing && (return false)
    o.name === nothing && (return false)
    o.features === nothing && (return false)
    o.uri === nothing && (return false)
    o.element_type === nothing && (return false)
    o.element_shape === nothing && (return false)
    o.initial_timestamp === nothing && (return false)
    o.resolution === nothing && (return false)
    o.horizon === nothing && (return false)
    o.interval === nothing && (return false)
    o.count === nothing && (return false)
    o.percentiles === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Probabilistic)
    OpenAPI.validate_property(Probabilistic, Symbol("id"), o.id)
    OpenAPI.validate_property(Probabilistic, Symbol("owner_id"), o.owner_id)
    OpenAPI.validate_property(Probabilistic, Symbol("owner_type"), o.owner_type)
    OpenAPI.validate_property(Probabilistic, Symbol("owner_category"), o.owner_category)
    OpenAPI.validate_property(Probabilistic, Symbol("time_series_type"), o.time_series_type)
    OpenAPI.validate_property(Probabilistic, Symbol("name"), o.name)
    OpenAPI.validate_property(Probabilistic, Symbol("features"), o.features)
    OpenAPI.validate_property(Probabilistic, Symbol("uri"), o.uri)
    OpenAPI.validate_property(Probabilistic, Symbol("data_hash"), o.data_hash)
    OpenAPI.validate_property(Probabilistic, Symbol("element_type"), o.element_type)
    OpenAPI.validate_property(Probabilistic, Symbol("element_shape"), o.element_shape)
    OpenAPI.validate_property(Probabilistic, Symbol("units"), o.units)
    OpenAPI.validate_property(Probabilistic, Symbol("quantity_kind"), o.quantity_kind)
    OpenAPI.validate_property(Probabilistic, Symbol("unit_system"), o.unit_system)
    OpenAPI.validate_property(Probabilistic, Symbol("component_field"), o.component_field)
    OpenAPI.validate_property(Probabilistic, Symbol("application_data"), o.application_data)
    OpenAPI.validate_property(Probabilistic, Symbol("initial_timestamp"), o.initial_timestamp)
    OpenAPI.validate_property(Probabilistic, Symbol("resolution"), o.resolution)
    OpenAPI.validate_property(Probabilistic, Symbol("horizon"), o.horizon)
    OpenAPI.validate_property(Probabilistic, Symbol("interval"), o.interval)
    OpenAPI.validate_property(Probabilistic, Symbol("count"), o.count)
    OpenAPI.validate_property(Probabilistic, Symbol("percentiles"), o.percentiles)
end

function OpenAPI.validate_property(::Type{ Probabilistic }, name::Symbol, val)




    if name === Symbol("owner_category")
        OpenAPI.validate_param(name, "Probabilistic", :enum, val, ["Component", "SupplementalAttribute"])
    end


    if name === Symbol("time_series_type")
        OpenAPI.validate_param(name, "Probabilistic", :enum, val, ["Probabilistic"])
    end










    if name === Symbol("unit_system")
        OpenAPI.validate_param(name, "Probabilistic", :enum, val, ["COMPONENT_BASE", "NATURAL_UNITS"])
    end




    if name === Symbol("initial_timestamp")
        OpenAPI.validate_param(name, "Probabilistic", :format, val, "date-time")
    end




    if name === Symbol("count")
        OpenAPI.validate_param(name, "Probabilistic", :minimum, val, 0, false)
    end

    if name === Symbol("percentiles")
        OpenAPI.validate_param(name, "Probabilistic", :minItems, val, 1)
    end
end
