# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RoundRotorExponential
4-states round-rotor synchronous machine with exponential saturation: IEEE Std 1110 §5.3.2 (Model 2.2). GENROE model in PSSE and PSLF

    RoundRotorExponential(;
        id=nothing,
        base_machine=nothing,
        saturation_coeffs=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - base_machine::Int64 : Round Rotor machine parameters
    - saturation_coeffs::Vector{Float64} : Derived saturation coefficients for the exponential saturation model, computed from the Se input
"""
Base.@kwdef mutable struct RoundRotorExponential <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    base_machine::Union{Nothing, Int64} = nothing
    saturation_coeffs::Union{Nothing, Vector{Float64}} = nothing

    function RoundRotorExponential(id, base_machine, saturation_coeffs, )
        o = new(id, base_machine, saturation_coeffs, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RoundRotorExponential

const _property_types_RoundRotorExponential = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("base_machine")=>"Int64", Symbol("saturation_coeffs")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ RoundRotorExponential }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RoundRotorExponential[name]))}

function OpenAPI.check_required(o::RoundRotorExponential)
    o.id === nothing && (return false)
    o.base_machine === nothing && (return false)
    o.saturation_coeffs === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RoundRotorExponential)
    OpenAPI.validate_property(RoundRotorExponential, Symbol("id"), o.id)
    OpenAPI.validate_property(RoundRotorExponential, Symbol("base_machine"), o.base_machine)
    OpenAPI.validate_property(RoundRotorExponential, Symbol("saturation_coeffs"), o.saturation_coeffs)
end

function OpenAPI.validate_property(::Type{ RoundRotorExponential }, name::Symbol, val)



    if name === Symbol("saturation_coeffs")
        OpenAPI.validate_param(name, "RoundRotorExponential", :maxItems, val, 2)
        OpenAPI.validate_param(name, "RoundRotorExponential", :minItems, val, 2)
    end
end
