# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EXST1
IEEE Type ST1 Excitation System (PTI version)

    EXST1(;
        id=nothing,
        Tr=nothing,
        Vi_lim=nothing,
        Tc=nothing,
        Tb=nothing,
        Ka=nothing,
        Ta=nothing,
        Vr_lim=nothing,
        Kc=nothing,
        Kf=nothing,
        Tf=nothing,
        V_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - Tr::Float64 : Voltage measurement time constant
    - Vi_lim::MinMax
    - Tc::Float64 : Numerator lead-lag (lead) time constant
    - Tb::Float64 : Denominator lead-lag (lag) time constant
    - Ka::Float64 : Amplifier gain
    - Ta::Float64 : Amplifier time constant
    - Vr_lim::MinMax
    - Kc::Float64 : Current field constant limiter multiplier
    - Kf::Float64 : Excitation control system stabilizer gain
    - Tf::Float64 : Excitation control system stabilizer time constant
    - V_ref::Float64 : Reference voltage set-point
"""
Base.@kwdef mutable struct EXST1 <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    Tr::Union{Nothing, Float64} = nothing
    Vi_lim = nothing # spec type: Union{ Nothing, MinMax }
    Tc::Union{Nothing, Float64} = nothing
    Tb::Union{Nothing, Float64} = nothing
    Ka::Union{Nothing, Float64} = nothing
    Ta::Union{Nothing, Float64} = nothing
    Vr_lim = nothing # spec type: Union{ Nothing, MinMax }
    Kc::Union{Nothing, Float64} = nothing
    Kf::Union{Nothing, Float64} = nothing
    Tf::Union{Nothing, Float64} = nothing
    V_ref::Union{Nothing, Float64} = 1.0

    function EXST1(id, Tr, Vi_lim, Tc, Tb, Ka, Ta, Vr_lim, Kc, Kf, Tf, V_ref, )
        o = new(id, Tr, Vi_lim, Tc, Tb, Ka, Ta, Vr_lim, Kc, Kf, Tf, V_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EXST1

const _property_types_EXST1 = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("Tr")=>"Float64", Symbol("Vi_lim")=>"MinMax", Symbol("Tc")=>"Float64", Symbol("Tb")=>"Float64", Symbol("Ka")=>"Float64", Symbol("Ta")=>"Float64", Symbol("Vr_lim")=>"MinMax", Symbol("Kc")=>"Float64", Symbol("Kf")=>"Float64", Symbol("Tf")=>"Float64", Symbol("V_ref")=>"Float64", )
OpenAPI.property_type(::Type{ EXST1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EXST1[name]))}

function OpenAPI.check_required(o::EXST1)
    o.id === nothing && (return false)
    o.Tr === nothing && (return false)
    o.Vi_lim === nothing && (return false)
    o.Tc === nothing && (return false)
    o.Tb === nothing && (return false)
    o.Ka === nothing && (return false)
    o.Ta === nothing && (return false)
    o.Vr_lim === nothing && (return false)
    o.Kc === nothing && (return false)
    o.Kf === nothing && (return false)
    o.Tf === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EXST1)
    OpenAPI.validate_property(EXST1, Symbol("id"), o.id)
    OpenAPI.validate_property(EXST1, Symbol("Tr"), o.Tr)
    OpenAPI.validate_property(EXST1, Symbol("Vi_lim"), o.Vi_lim)
    OpenAPI.validate_property(EXST1, Symbol("Tc"), o.Tc)
    OpenAPI.validate_property(EXST1, Symbol("Tb"), o.Tb)
    OpenAPI.validate_property(EXST1, Symbol("Ka"), o.Ka)
    OpenAPI.validate_property(EXST1, Symbol("Ta"), o.Ta)
    OpenAPI.validate_property(EXST1, Symbol("Vr_lim"), o.Vr_lim)
    OpenAPI.validate_property(EXST1, Symbol("Kc"), o.Kc)
    OpenAPI.validate_property(EXST1, Symbol("Kf"), o.Kf)
    OpenAPI.validate_property(EXST1, Symbol("Tf"), o.Tf)
    OpenAPI.validate_property(EXST1, Symbol("V_ref"), o.V_ref)
end

function OpenAPI.validate_property(::Type{ EXST1 }, name::Symbol, val)












end
