# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DbdPnts_1
Voltage or Q-power error dead band thresholds &#x60;(dbd1, dbd2)&#x60;.

    DbdPnts1(;
        dbd1=nothing,
        dbd2=nothing,
    )

    - dbd1::Float64
    - dbd2::Float64
"""
Base.@kwdef mutable struct DbdPnts1 <: OpenAPI.APIModel
    dbd1::Union{Nothing, Float64} = nothing
    dbd2::Union{Nothing, Float64} = nothing

    function DbdPnts1(dbd1, dbd2, )
        o = new(dbd1, dbd2, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DbdPnts1

const _property_types_DbdPnts1 = Dict{Symbol,String}(Symbol("dbd1")=>"Float64", Symbol("dbd2")=>"Float64", )
OpenAPI.property_type(::Type{ DbdPnts1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DbdPnts1[name]))}

function OpenAPI.check_required(o::DbdPnts1)
    true
end

function OpenAPI.validate_properties(o::DbdPnts1)
    OpenAPI.validate_property(DbdPnts1, Symbol("dbd1"), o.dbd1)
    OpenAPI.validate_property(DbdPnts1, Symbol("dbd2"), o.dbd2)
end

function OpenAPI.validate_property(::Type{ DbdPnts1 }, name::Symbol, val)


end
