# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EXAC1
Modified ESAC1A. This excitation systems consists of an alternator main exciter feeding its output via non-controlled rectifiers. The exciter does not employ self-excitation, and the voltage regulator power is taken from a source that is not affected by external transients. Parameters of IEEE Std 421.5 Type AC1A. EXAC1 in PSSE and PSLF

    EXAC1(;
        id=nothing,
        Tr=nothing,
        Tb=nothing,
        Tc=nothing,
        Ka=nothing,
        Ta=nothing,
        Vr_lim=nothing,
        Te=nothing,
        Kf=nothing,
        Tf=nothing,
        Kc=nothing,
        Kd=nothing,
        Ke=nothing,
        E_sat=nothing,
        Se=nothing,
        V_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - Tr::Float64 : Regulator input filter time constant
    - Tb::Float64 : Regulator denominator (lag) time constant
    - Tc::Float64 : Regulator numerator (lead) time constant
    - Ka::Float64 : Regulator output gain
    - Ta::Float64 : Regulator output time constant
    - Vr_lim::MinMax
    - Te::Float64 : Exciter field time constant
    - Kf::Float64 : Rate feedback excitation system stabilizer gain
    - Tf::Float64 : Rate feedback time constant
    - Kc::Float64 : Rectifier loading factor proportional to commutating reactance
    - Kd::Float64 : Demagnetizing factor, function of exciter alternator reactances
    - Ke::Float64 : Exciter field proportional constant
    - E_sat::Vector{Float64} : Exciter output voltage for saturation factor
    - Se::Vector{Float64} : Exciter saturation factor at exciter output voltage
    - V_ref::Float64 : Reference voltage set-point
"""
Base.@kwdef mutable struct EXAC1 <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    Tr::Union{Nothing, Float64} = nothing
    Tb::Union{Nothing, Float64} = nothing
    Tc::Union{Nothing, Float64} = nothing
    Ka::Union{Nothing, Float64} = nothing
    Ta::Union{Nothing, Float64} = nothing
    Vr_lim = nothing # spec type: Union{ Nothing, MinMax }
    Te::Union{Nothing, Float64} = nothing
    Kf::Union{Nothing, Float64} = nothing
    Tf::Union{Nothing, Float64} = nothing
    Kc::Union{Nothing, Float64} = nothing
    Kd::Union{Nothing, Float64} = nothing
    Ke::Union{Nothing, Float64} = nothing
    E_sat::Union{Nothing, Vector{Float64}} = nothing
    Se::Union{Nothing, Vector{Float64}} = nothing
    V_ref::Union{Nothing, Float64} = 1.0

    function EXAC1(id, Tr, Tb, Tc, Ka, Ta, Vr_lim, Te, Kf, Tf, Kc, Kd, Ke, E_sat, Se, V_ref, )
        o = new(id, Tr, Tb, Tc, Ka, Ta, Vr_lim, Te, Kf, Tf, Kc, Kd, Ke, E_sat, Se, V_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EXAC1

const _property_types_EXAC1 = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("Tr")=>"Float64", Symbol("Tb")=>"Float64", Symbol("Tc")=>"Float64", Symbol("Ka")=>"Float64", Symbol("Ta")=>"Float64", Symbol("Vr_lim")=>"MinMax", Symbol("Te")=>"Float64", Symbol("Kf")=>"Float64", Symbol("Tf")=>"Float64", Symbol("Kc")=>"Float64", Symbol("Kd")=>"Float64", Symbol("Ke")=>"Float64", Symbol("E_sat")=>"Vector{Float64}", Symbol("Se")=>"Vector{Float64}", Symbol("V_ref")=>"Float64", )
OpenAPI.property_type(::Type{ EXAC1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EXAC1[name]))}

function OpenAPI.check_required(o::EXAC1)
    o.id === nothing && (return false)
    o.Tr === nothing && (return false)
    o.Tb === nothing && (return false)
    o.Tc === nothing && (return false)
    o.Ka === nothing && (return false)
    o.Ta === nothing && (return false)
    o.Vr_lim === nothing && (return false)
    o.Te === nothing && (return false)
    o.Kf === nothing && (return false)
    o.Tf === nothing && (return false)
    o.Kc === nothing && (return false)
    o.Kd === nothing && (return false)
    o.Ke === nothing && (return false)
    o.E_sat === nothing && (return false)
    o.Se === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EXAC1)
    OpenAPI.validate_property(EXAC1, Symbol("id"), o.id)
    OpenAPI.validate_property(EXAC1, Symbol("Tr"), o.Tr)
    OpenAPI.validate_property(EXAC1, Symbol("Tb"), o.Tb)
    OpenAPI.validate_property(EXAC1, Symbol("Tc"), o.Tc)
    OpenAPI.validate_property(EXAC1, Symbol("Ka"), o.Ka)
    OpenAPI.validate_property(EXAC1, Symbol("Ta"), o.Ta)
    OpenAPI.validate_property(EXAC1, Symbol("Vr_lim"), o.Vr_lim)
    OpenAPI.validate_property(EXAC1, Symbol("Te"), o.Te)
    OpenAPI.validate_property(EXAC1, Symbol("Kf"), o.Kf)
    OpenAPI.validate_property(EXAC1, Symbol("Tf"), o.Tf)
    OpenAPI.validate_property(EXAC1, Symbol("Kc"), o.Kc)
    OpenAPI.validate_property(EXAC1, Symbol("Kd"), o.Kd)
    OpenAPI.validate_property(EXAC1, Symbol("Ke"), o.Ke)
    OpenAPI.validate_property(EXAC1, Symbol("E_sat"), o.E_sat)
    OpenAPI.validate_property(EXAC1, Symbol("Se"), o.Se)
    OpenAPI.validate_property(EXAC1, Symbol("V_ref"), o.V_ref)
end

function OpenAPI.validate_property(::Type{ EXAC1 }, name::Symbol, val)














    if name === Symbol("E_sat")
        OpenAPI.validate_param(name, "EXAC1", :maxItems, val, 2)
        OpenAPI.validate_param(name, "EXAC1", :minItems, val, 2)
    end

    if name === Symbol("Se")
        OpenAPI.validate_param(name, "EXAC1", :maxItems, val, 2)
        OpenAPI.validate_param(name, "EXAC1", :minItems, val, 2)
    end

end
