# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TGSimple
Parameters of a Simple one-state Turbine Governor

    TGSimple(;
        id=nothing,
        d_t=nothing,
        Tm=nothing,
        P_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - d_t::Float64 : Inverse droop parameter
    - Tm::Float64 : Turbine governor low-pass time constant
    - P_ref::Float64 : Reference power set-point
"""
Base.@kwdef mutable struct TGSimple <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    d_t::Union{Nothing, Float64} = nothing
    Tm::Union{Nothing, Float64} = nothing
    P_ref::Union{Nothing, Float64} = 1.0

    function TGSimple(id, d_t, Tm, P_ref, )
        o = new(id, d_t, Tm, P_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TGSimple

const _property_types_TGSimple = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("d_t")=>"Float64", Symbol("Tm")=>"Float64", Symbol("P_ref")=>"Float64", )
OpenAPI.property_type(::Type{ TGSimple }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TGSimple[name]))}

function OpenAPI.check_required(o::TGSimple)
    o.id === nothing && (return false)
    o.d_t === nothing && (return false)
    o.Tm === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TGSimple)
    OpenAPI.validate_property(TGSimple, Symbol("id"), o.id)
    OpenAPI.validate_property(TGSimple, Symbol("d_t"), o.d_t)
    OpenAPI.validate_property(TGSimple, Symbol("Tm"), o.Tm)
    OpenAPI.validate_property(TGSimple, Symbol("P_ref"), o.P_ref)
end

function OpenAPI.validate_property(::Type{ TGSimple }, name::Symbol, val)




end
