# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GasTG
Parameters of Gas Turbine-Governor. GAST in PSSE and GAST_PTI in PowerWorld

    GasTG(;
        id=nothing,
        R=nothing,
        T1=nothing,
        T2=nothing,
        T3=nothing,
        AT=nothing,
        Kt=nothing,
        V_lim=nothing,
        D_turb=nothing,
        P_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - R::Float64 : Speed droop parameter
    - T1::Float64 : Governor time constant
    - T2::Float64 : Combustion chamber time constant
    - T3::Float64 : Load limit time constant (exhaust gas measurement time)
    - AT::Float64 : Ambient temperature load limit
    - Kt::Float64 : Load limit feedback gain
    - V_lim::Vector{Float64} : Operational control limits on fuel valve opening (Vmin, Vmax)
    - D_turb::Float64 : Speed damping coefficient of gas turbine rotor
    - P_ref::Float64 : Reference load set-point
"""
Base.@kwdef mutable struct GasTG <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    T1::Union{Nothing, Float64} = nothing
    T2::Union{Nothing, Float64} = nothing
    T3::Union{Nothing, Float64} = nothing
    AT::Union{Nothing, Float64} = nothing
    Kt::Union{Nothing, Float64} = nothing
    V_lim::Union{Nothing, Vector{Float64}} = nothing
    D_turb::Union{Nothing, Float64} = nothing
    P_ref::Union{Nothing, Float64} = 1.0

    function GasTG(id, R, T1, T2, T3, AT, Kt, V_lim, D_turb, P_ref, )
        o = new(id, R, T1, T2, T3, AT, Kt, V_lim, D_turb, P_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GasTG

const _property_types_GasTG = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("T1")=>"Float64", Symbol("T2")=>"Float64", Symbol("T3")=>"Float64", Symbol("AT")=>"Float64", Symbol("Kt")=>"Float64", Symbol("V_lim")=>"Vector{Float64}", Symbol("D_turb")=>"Float64", Symbol("P_ref")=>"Float64", )
OpenAPI.property_type(::Type{ GasTG }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GasTG[name]))}

function OpenAPI.check_required(o::GasTG)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.T1 === nothing && (return false)
    o.T2 === nothing && (return false)
    o.T3 === nothing && (return false)
    o.AT === nothing && (return false)
    o.Kt === nothing && (return false)
    o.V_lim === nothing && (return false)
    o.D_turb === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GasTG)
    OpenAPI.validate_property(GasTG, Symbol("id"), o.id)
    OpenAPI.validate_property(GasTG, Symbol("R"), o.R)
    OpenAPI.validate_property(GasTG, Symbol("T1"), o.T1)
    OpenAPI.validate_property(GasTG, Symbol("T2"), o.T2)
    OpenAPI.validate_property(GasTG, Symbol("T3"), o.T3)
    OpenAPI.validate_property(GasTG, Symbol("AT"), o.AT)
    OpenAPI.validate_property(GasTG, Symbol("Kt"), o.Kt)
    OpenAPI.validate_property(GasTG, Symbol("V_lim"), o.V_lim)
    OpenAPI.validate_property(GasTG, Symbol("D_turb"), o.D_turb)
    OpenAPI.validate_property(GasTG, Symbol("P_ref"), o.P_ref)
end

function OpenAPI.validate_property(::Type{ GasTG }, name::Symbol, val)








    if name === Symbol("V_lim")
        OpenAPI.validate_param(name, "GasTG", :maxItems, val, 2)
        OpenAPI.validate_param(name, "GasTG", :minItems, val, 2)
    end


end
