# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PSSSimple
Parameters of a PSS that returns a proportional droop voltage to add to the reference for the AVR

    PSSSimple(;
        id=nothing,
        K_omega=nothing,
        K_p=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - K_omega::Float64 : Proportional gain for frequency
    - K_p::Float64 : Proportional gain for active power
"""
Base.@kwdef mutable struct PSSSimple <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    K_omega::Union{Nothing, Float64} = nothing
    K_p::Union{Nothing, Float64} = nothing

    function PSSSimple(id, K_omega, K_p, )
        o = new(id, K_omega, K_p, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PSSSimple

const _property_types_PSSSimple = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("K_omega")=>"Float64", Symbol("K_p")=>"Float64", )
OpenAPI.property_type(::Type{ PSSSimple }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PSSSimple[name]))}

function OpenAPI.check_required(o::PSSSimple)
    o.id === nothing && (return false)
    o.K_omega === nothing && (return false)
    o.K_p === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PSSSimple)
    OpenAPI.validate_property(PSSSimple, Symbol("id"), o.id)
    OpenAPI.validate_property(PSSSimple, Symbol("K_omega"), o.K_omega)
    OpenAPI.validate_property(PSSSimple, Symbol("K_p"), o.K_p)
end

function OpenAPI.validate_property(::Type{ PSSSimple }, name::Symbol, val)



end
