# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SalientPoleMachine
Parameters of 3-states salient-pole synchronous machine with quadratic/exponential saturation: IEEE Std 1110 §5.3.1 (Model 2.1). GENSAL or GENSAE model in PSSE and PSLF

    SalientPoleMachine(;
        id=nothing,
        R=nothing,
        Td0_p=nothing,
        Td0_pp=nothing,
        Tq0_pp=nothing,
        Xd=nothing,
        Xq=nothing,
        Xd_p=nothing,
        Xd_pp=nothing,
        Xl=nothing,
        Se=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - R::Float64 : Armature resistance
    - Td0_p::Float64 : Time constant of transient d-axis voltage
    - Td0_pp::Float64 : Time constant of sub-transient d-axis voltage
    - Tq0_pp::Float64 : Time constant of sub-transient q-axis voltage
    - Xd::Float64 : Reactance after EMF in d-axis
    - Xq::Float64 : Reactance after EMF in q-axis
    - Xd_p::Float64 : Transient reactance after EMF in d-axis
    - Xd_pp::Float64 : Sub-Transient reactance after EMF in d-axis. Note: Xd_pp &#x3D; Xq_pp
    - Xl::Float64 : Stator leakage reactance
    - Se::Vector{Float64} : Saturation factor at 1 and 1.2 pu flux: Se(eqp) &#x3D; B(eqp-A)^2
"""
Base.@kwdef mutable struct SalientPoleMachine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    Td0_p::Union{Nothing, Float64} = nothing
    Td0_pp::Union{Nothing, Float64} = nothing
    Tq0_pp::Union{Nothing, Float64} = nothing
    Xd::Union{Nothing, Float64} = nothing
    Xq::Union{Nothing, Float64} = nothing
    Xd_p::Union{Nothing, Float64} = nothing
    Xd_pp::Union{Nothing, Float64} = nothing
    Xl::Union{Nothing, Float64} = nothing
    Se::Union{Nothing, Vector{Float64}} = nothing

    function SalientPoleMachine(id, R, Td0_p, Td0_pp, Tq0_pp, Xd, Xq, Xd_p, Xd_pp, Xl, Se, )
        o = new(id, R, Td0_p, Td0_pp, Tq0_pp, Xd, Xq, Xd_p, Xd_pp, Xl, Se, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SalientPoleMachine

const _property_types_SalientPoleMachine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("Td0_p")=>"Float64", Symbol("Td0_pp")=>"Float64", Symbol("Tq0_pp")=>"Float64", Symbol("Xd")=>"Float64", Symbol("Xq")=>"Float64", Symbol("Xd_p")=>"Float64", Symbol("Xd_pp")=>"Float64", Symbol("Xl")=>"Float64", Symbol("Se")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ SalientPoleMachine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SalientPoleMachine[name]))}

function OpenAPI.check_required(o::SalientPoleMachine)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.Td0_p === nothing && (return false)
    o.Td0_pp === nothing && (return false)
    o.Tq0_pp === nothing && (return false)
    o.Xd === nothing && (return false)
    o.Xq === nothing && (return false)
    o.Xd_p === nothing && (return false)
    o.Xd_pp === nothing && (return false)
    o.Xl === nothing && (return false)
    o.Se === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SalientPoleMachine)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("id"), o.id)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("R"), o.R)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Td0_p"), o.Td0_p)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Td0_pp"), o.Td0_pp)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Tq0_pp"), o.Tq0_pp)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Xd"), o.Xd)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Xq"), o.Xq)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Xd_p"), o.Xd_p)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Xd_pp"), o.Xd_pp)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Xl"), o.Xl)
    OpenAPI.validate_property(SalientPoleMachine, Symbol("Se"), o.Se)
end

function OpenAPI.validate_property(::Type{ SalientPoleMachine }, name::Symbol, val)











    if name === Symbol("Se")
        OpenAPI.validate_param(name, "SalientPoleMachine", :maxItems, val, 2)
        OpenAPI.validate_param(name, "SalientPoleMachine", :minItems, val, 2)
    end
end
