# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ST8C
In these excitation systems, voltage (and also current in compounded systems) is transformed to an appropriate level. Rectifiers, either controlled or non-controlled, provide the necessary direct current for the generator field. Parameters of IEEE Std 421.5 Type ST8C Excitacion System. ST8C in PSSE and PSLF

    ST8C(;
        id=nothing,
        OEL_Flag=nothing,
        UEL_Flag=nothing,
        SCL_Flag=nothing,
        SW1_Flag=nothing,
        Tr=nothing,
        K_pr=nothing,
        K_ir=nothing,
        Vpi_lim=nothing,
        K_pa=nothing,
        K_ia=nothing,
        Va_lim=nothing,
        K_a=nothing,
        T_a=nothing,
        Vr_lim=nothing,
        K_f=nothing,
        T_f=nothing,
        K_c1=nothing,
        K_p=nothing,
        K_i1=nothing,
        X_l=nothing,
        theta_p=nothing,
        VB1_max=nothing,
        K_c2=nothing,
        K_i2=nothing,
        VB2_max=nothing,
        V_ref=1.0,
        Ifd_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - OEL_Flag::Int64 : OEL Flag for ST8C: &lt;2: Summation at voltage error, 2: OEL takeover at gate
    - UEL_Flag::Int64 : UEL Flag for ST8C: &lt;2: Summation at voltage error, 2: UEL takeover at gate
    - SCL_Flag::Int64 : SCL Flag for ST8C: &lt;2: Summation at voltage error, 2: SCL takeover at UEL and OEL gates
    - SW1_Flag::Int64 : SW1 Flag for power source selector for ST8C: &lt;2: Source from generator terminal voltage, 2: Independent power source
    - Tr::Float64 : Regulator input filter time constant
    - K_pr::Float64 : Regulator proportional gain
    - K_ir::Float64 : Regulator integral gain
    - Vpi_lim::MinMax
    - K_pa::Float64 : Field current regulator proportional gain
    - K_ia::Float64 : Field current regulator integral gain
    - Va_lim::MinMax
    - K_a::Float64 : Field current regulator proportional gain
    - T_a::Float64 : Controlled rectifier bridge equivalent time constant
    - Vr_lim::MinMax
    - K_f::Float64 : Exciter field current feedback gain
    - T_f::Float64 : Field current feedback time constant
    - K_c1::Float64 : Rectifier loading factor proportional to commutating reactance
    - K_p::Float64 : Potential circuit (voltage) gain coefficient
    - K_i1::Float64 : Potential circuit (current) gain coefficient
    - X_l::Float64 : Reactance associated with potential source
    - theta_p::Float64 : Potential circuit phase angle (degrees)
    - VB1_max::Float64 : Maximum available exciter voltage
    - K_c2::Float64 : Rectifier loading factor proportional to commutating reactance
    - K_i2::Float64 : Potential circuit (current) gain coefficient
    - VB2_max::Float64 : Maximum available exciter voltage
    - V_ref::Float64 : Reference voltage set-point
    - Ifd_ref::Float64 : Reference field current set-point
"""
Base.@kwdef mutable struct ST8C <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    OEL_Flag::Union{Nothing, Int64} = nothing
    UEL_Flag::Union{Nothing, Int64} = nothing
    SCL_Flag::Union{Nothing, Int64} = nothing
    SW1_Flag::Union{Nothing, Int64} = nothing
    Tr::Union{Nothing, Float64} = nothing
    K_pr::Union{Nothing, Float64} = nothing
    K_ir::Union{Nothing, Float64} = nothing
    Vpi_lim = nothing # spec type: Union{ Nothing, MinMax }
    K_pa::Union{Nothing, Float64} = nothing
    K_ia::Union{Nothing, Float64} = nothing
    Va_lim = nothing # spec type: Union{ Nothing, MinMax }
    K_a::Union{Nothing, Float64} = nothing
    T_a::Union{Nothing, Float64} = nothing
    Vr_lim = nothing # spec type: Union{ Nothing, MinMax }
    K_f::Union{Nothing, Float64} = nothing
    T_f::Union{Nothing, Float64} = nothing
    K_c1::Union{Nothing, Float64} = nothing
    K_p::Union{Nothing, Float64} = nothing
    K_i1::Union{Nothing, Float64} = nothing
    X_l::Union{Nothing, Float64} = nothing
    theta_p::Union{Nothing, Float64} = nothing
    VB1_max::Union{Nothing, Float64} = nothing
    K_c2::Union{Nothing, Float64} = nothing
    K_i2::Union{Nothing, Float64} = nothing
    VB2_max::Union{Nothing, Float64} = nothing
    V_ref::Union{Nothing, Float64} = 1.0
    Ifd_ref::Union{Nothing, Float64} = 1.0

    function ST8C(id, OEL_Flag, UEL_Flag, SCL_Flag, SW1_Flag, Tr, K_pr, K_ir, Vpi_lim, K_pa, K_ia, Va_lim, K_a, T_a, Vr_lim, K_f, T_f, K_c1, K_p, K_i1, X_l, theta_p, VB1_max, K_c2, K_i2, VB2_max, V_ref, Ifd_ref, )
        o = new(id, OEL_Flag, UEL_Flag, SCL_Flag, SW1_Flag, Tr, K_pr, K_ir, Vpi_lim, K_pa, K_ia, Va_lim, K_a, T_a, Vr_lim, K_f, T_f, K_c1, K_p, K_i1, X_l, theta_p, VB1_max, K_c2, K_i2, VB2_max, V_ref, Ifd_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ST8C

const _property_types_ST8C = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("OEL_Flag")=>"Int64", Symbol("UEL_Flag")=>"Int64", Symbol("SCL_Flag")=>"Int64", Symbol("SW1_Flag")=>"Int64", Symbol("Tr")=>"Float64", Symbol("K_pr")=>"Float64", Symbol("K_ir")=>"Float64", Symbol("Vpi_lim")=>"MinMax", Symbol("K_pa")=>"Float64", Symbol("K_ia")=>"Float64", Symbol("Va_lim")=>"MinMax", Symbol("K_a")=>"Float64", Symbol("T_a")=>"Float64", Symbol("Vr_lim")=>"MinMax", Symbol("K_f")=>"Float64", Symbol("T_f")=>"Float64", Symbol("K_c1")=>"Float64", Symbol("K_p")=>"Float64", Symbol("K_i1")=>"Float64", Symbol("X_l")=>"Float64", Symbol("theta_p")=>"Float64", Symbol("VB1_max")=>"Float64", Symbol("K_c2")=>"Float64", Symbol("K_i2")=>"Float64", Symbol("VB2_max")=>"Float64", Symbol("V_ref")=>"Float64", Symbol("Ifd_ref")=>"Float64", )
OpenAPI.property_type(::Type{ ST8C }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ST8C[name]))}

function OpenAPI.check_required(o::ST8C)
    o.id === nothing && (return false)
    o.OEL_Flag === nothing && (return false)
    o.UEL_Flag === nothing && (return false)
    o.SCL_Flag === nothing && (return false)
    o.SW1_Flag === nothing && (return false)
    o.Tr === nothing && (return false)
    o.K_pr === nothing && (return false)
    o.K_ir === nothing && (return false)
    o.Vpi_lim === nothing && (return false)
    o.K_pa === nothing && (return false)
    o.K_ia === nothing && (return false)
    o.Va_lim === nothing && (return false)
    o.K_a === nothing && (return false)
    o.T_a === nothing && (return false)
    o.Vr_lim === nothing && (return false)
    o.K_f === nothing && (return false)
    o.T_f === nothing && (return false)
    o.K_c1 === nothing && (return false)
    o.K_p === nothing && (return false)
    o.K_i1 === nothing && (return false)
    o.X_l === nothing && (return false)
    o.theta_p === nothing && (return false)
    o.VB1_max === nothing && (return false)
    o.K_c2 === nothing && (return false)
    o.K_i2 === nothing && (return false)
    o.VB2_max === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ST8C)
    OpenAPI.validate_property(ST8C, Symbol("id"), o.id)
    OpenAPI.validate_property(ST8C, Symbol("OEL_Flag"), o.OEL_Flag)
    OpenAPI.validate_property(ST8C, Symbol("UEL_Flag"), o.UEL_Flag)
    OpenAPI.validate_property(ST8C, Symbol("SCL_Flag"), o.SCL_Flag)
    OpenAPI.validate_property(ST8C, Symbol("SW1_Flag"), o.SW1_Flag)
    OpenAPI.validate_property(ST8C, Symbol("Tr"), o.Tr)
    OpenAPI.validate_property(ST8C, Symbol("K_pr"), o.K_pr)
    OpenAPI.validate_property(ST8C, Symbol("K_ir"), o.K_ir)
    OpenAPI.validate_property(ST8C, Symbol("Vpi_lim"), o.Vpi_lim)
    OpenAPI.validate_property(ST8C, Symbol("K_pa"), o.K_pa)
    OpenAPI.validate_property(ST8C, Symbol("K_ia"), o.K_ia)
    OpenAPI.validate_property(ST8C, Symbol("Va_lim"), o.Va_lim)
    OpenAPI.validate_property(ST8C, Symbol("K_a"), o.K_a)
    OpenAPI.validate_property(ST8C, Symbol("T_a"), o.T_a)
    OpenAPI.validate_property(ST8C, Symbol("Vr_lim"), o.Vr_lim)
    OpenAPI.validate_property(ST8C, Symbol("K_f"), o.K_f)
    OpenAPI.validate_property(ST8C, Symbol("T_f"), o.T_f)
    OpenAPI.validate_property(ST8C, Symbol("K_c1"), o.K_c1)
    OpenAPI.validate_property(ST8C, Symbol("K_p"), o.K_p)
    OpenAPI.validate_property(ST8C, Symbol("K_i1"), o.K_i1)
    OpenAPI.validate_property(ST8C, Symbol("X_l"), o.X_l)
    OpenAPI.validate_property(ST8C, Symbol("theta_p"), o.theta_p)
    OpenAPI.validate_property(ST8C, Symbol("VB1_max"), o.VB1_max)
    OpenAPI.validate_property(ST8C, Symbol("K_c2"), o.K_c2)
    OpenAPI.validate_property(ST8C, Symbol("K_i2"), o.K_i2)
    OpenAPI.validate_property(ST8C, Symbol("VB2_max"), o.VB2_max)
    OpenAPI.validate_property(ST8C, Symbol("V_ref"), o.V_ref)
    OpenAPI.validate_property(ST8C, Symbol("Ifd_ref"), o.Ifd_ref)
end

function OpenAPI.validate_property(::Type{ ST8C }, name::Symbol, val)




























end
