# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DEGOV1
Parameters Woodward Diesel Governor Model. DEGOV1 in PSSE

    DEGOV1(;
        id=nothing,
        droop_flag=nothing,
        T1=nothing,
        T2=nothing,
        T3=nothing,
        K=nothing,
        T4=nothing,
        T5=nothing,
        T6=nothing,
        Td=nothing,
        T_lim=nothing,
        R=nothing,
        Te=nothing,
        P_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - droop_flag::Int64 : Droop control Flag. 0 for throttle feedback and 1 for electric power feedback
    - T1::Float64 : Governor mechanism time constant
    - T2::Float64 : Turbine power time constant
    - T3::Float64 : Turbine exhaust temperature time constant
    - K::Float64 : Governor gain for actuator
    - T4::Float64 : Governor lead time constant
    - T5::Float64 : Governor lag time constant
    - T6::Float64 : Actuator time constant
    - Td::Float64 : Engine time delay
    - T_lim::Vector{Float64} : Operational control limits on actuator (Tmin, Tmax)
    - R::Float64 : Steady state droop parameter
    - Te::Float64 : Power transducer time constant
    - P_ref::Float64 : Reference power set-point
"""
Base.@kwdef mutable struct DEGOV1 <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    droop_flag::Union{Nothing, Int64} = nothing
    T1::Union{Nothing, Float64} = nothing
    T2::Union{Nothing, Float64} = nothing
    T3::Union{Nothing, Float64} = nothing
    K::Union{Nothing, Float64} = nothing
    T4::Union{Nothing, Float64} = nothing
    T5::Union{Nothing, Float64} = nothing
    T6::Union{Nothing, Float64} = nothing
    Td::Union{Nothing, Float64} = nothing
    T_lim::Union{Nothing, Vector{Float64}} = nothing
    R::Union{Nothing, Float64} = nothing
    Te::Union{Nothing, Float64} = nothing
    P_ref::Union{Nothing, Float64} = 1.0

    function DEGOV1(id, droop_flag, T1, T2, T3, K, T4, T5, T6, Td, T_lim, R, Te, P_ref, )
        o = new(id, droop_flag, T1, T2, T3, K, T4, T5, T6, Td, T_lim, R, Te, P_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DEGOV1

const _property_types_DEGOV1 = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("droop_flag")=>"Int64", Symbol("T1")=>"Float64", Symbol("T2")=>"Float64", Symbol("T3")=>"Float64", Symbol("K")=>"Float64", Symbol("T4")=>"Float64", Symbol("T5")=>"Float64", Symbol("T6")=>"Float64", Symbol("Td")=>"Float64", Symbol("T_lim")=>"Vector{Float64}", Symbol("R")=>"Float64", Symbol("Te")=>"Float64", Symbol("P_ref")=>"Float64", )
OpenAPI.property_type(::Type{ DEGOV1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DEGOV1[name]))}

function OpenAPI.check_required(o::DEGOV1)
    o.id === nothing && (return false)
    o.T1 === nothing && (return false)
    o.T2 === nothing && (return false)
    o.T3 === nothing && (return false)
    o.K === nothing && (return false)
    o.T4 === nothing && (return false)
    o.T5 === nothing && (return false)
    o.T6 === nothing && (return false)
    o.Td === nothing && (return false)
    o.T_lim === nothing && (return false)
    o.R === nothing && (return false)
    o.Te === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DEGOV1)
    OpenAPI.validate_property(DEGOV1, Symbol("id"), o.id)
    OpenAPI.validate_property(DEGOV1, Symbol("droop_flag"), o.droop_flag)
    OpenAPI.validate_property(DEGOV1, Symbol("T1"), o.T1)
    OpenAPI.validate_property(DEGOV1, Symbol("T2"), o.T2)
    OpenAPI.validate_property(DEGOV1, Symbol("T3"), o.T3)
    OpenAPI.validate_property(DEGOV1, Symbol("K"), o.K)
    OpenAPI.validate_property(DEGOV1, Symbol("T4"), o.T4)
    OpenAPI.validate_property(DEGOV1, Symbol("T5"), o.T5)
    OpenAPI.validate_property(DEGOV1, Symbol("T6"), o.T6)
    OpenAPI.validate_property(DEGOV1, Symbol("Td"), o.Td)
    OpenAPI.validate_property(DEGOV1, Symbol("T_lim"), o.T_lim)
    OpenAPI.validate_property(DEGOV1, Symbol("R"), o.R)
    OpenAPI.validate_property(DEGOV1, Symbol("Te"), o.Te)
    OpenAPI.validate_property(DEGOV1, Symbol("P_ref"), o.P_ref)
end

function OpenAPI.validate_property(::Type{ DEGOV1 }, name::Symbol, val)











    if name === Symbol("T_lim")
        OpenAPI.validate_param(name, "DEGOV1", :maxItems, val, 2)
        OpenAPI.validate_param(name, "DEGOV1", :minItems, val, 2)
    end



end
