# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""STAB1
Speed-sensitive stabilizing model

    STAB1(;
        id=nothing,
        KT=nothing,
        T=nothing,
        T1T3=nothing,
        T3=nothing,
        T2T4=nothing,
        T4=nothing,
        H_lim=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - KT::Float64 : K/T for washout filter
    - T::Float64 : Time constant for washout filter
    - T1T3::Float64 : Time constant division T1/T3
    - T3::Float64 : Time constant
    - T2T4::Float64 : Time constant division T2/T4
    - T4::Float64 : Time constant
    - H_lim::Float64 : PSS output limit
"""
Base.@kwdef mutable struct STAB1 <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    KT::Union{Nothing, Float64} = nothing
    T::Union{Nothing, Float64} = nothing
    T1T3::Union{Nothing, Float64} = nothing
    T3::Union{Nothing, Float64} = nothing
    T2T4::Union{Nothing, Float64} = nothing
    T4::Union{Nothing, Float64} = nothing
    H_lim::Union{Nothing, Float64} = nothing

    function STAB1(id, KT, T, T1T3, T3, T2T4, T4, H_lim, )
        o = new(id, KT, T, T1T3, T3, T2T4, T4, H_lim, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type STAB1

const _property_types_STAB1 = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("KT")=>"Float64", Symbol("T")=>"Float64", Symbol("T1T3")=>"Float64", Symbol("T3")=>"Float64", Symbol("T2T4")=>"Float64", Symbol("T4")=>"Float64", Symbol("H_lim")=>"Float64", )
OpenAPI.property_type(::Type{ STAB1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_STAB1[name]))}

function OpenAPI.check_required(o::STAB1)
    o.id === nothing && (return false)
    o.KT === nothing && (return false)
    o.T === nothing && (return false)
    o.T1T3 === nothing && (return false)
    o.T3 === nothing && (return false)
    o.T2T4 === nothing && (return false)
    o.T4 === nothing && (return false)
    o.H_lim === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::STAB1)
    OpenAPI.validate_property(STAB1, Symbol("id"), o.id)
    OpenAPI.validate_property(STAB1, Symbol("KT"), o.KT)
    OpenAPI.validate_property(STAB1, Symbol("T"), o.T)
    OpenAPI.validate_property(STAB1, Symbol("T1T3"), o.T1T3)
    OpenAPI.validate_property(STAB1, Symbol("T3"), o.T3)
    OpenAPI.validate_property(STAB1, Symbol("T2T4"), o.T2T4)
    OpenAPI.validate_property(STAB1, Symbol("T4"), o.T4)
    OpenAPI.validate_property(STAB1, Symbol("H_lim"), o.H_lim)
end

function OpenAPI.validate_property(::Type{ STAB1 }, name::Symbol, val)








end
