# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AndersonFouadMachine
Parameters of 6-states synchronous machine: Anderson-Fouad model

    AndersonFouadMachine(;
        id=nothing,
        R=nothing,
        Xd=nothing,
        Xq=nothing,
        Xd_p=nothing,
        Xq_p=nothing,
        Xd_pp=nothing,
        Xq_pp=nothing,
        Td0_p=nothing,
        Tq0_p=nothing,
        Td0_pp=nothing,
        Tq0_pp=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - R::Float64 : Resistance after EMF
    - Xd::Float64 : Reactance after EMF in d-axis
    - Xq::Float64 : Reactance after EMF in q-axis
    - Xd_p::Float64 : Transient reactance after EMF in d-axis
    - Xq_p::Float64 : Transient reactance after EMF in q-axis
    - Xd_pp::Float64 : Sub-Transient reactance after EMF in d-axis
    - Xq_pp::Float64 : Sub-Transient reactance after EMF in q-axis
    - Td0_p::Float64 : Time constant of transient d-axis voltage
    - Tq0_p::Float64 : Time constant of transient q-axis voltage
    - Td0_pp::Float64 : Time constant of sub-transient d-axis voltage
    - Tq0_pp::Float64 : Time constant of sub-transient q-axis voltage
"""
Base.@kwdef mutable struct AndersonFouadMachine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    Xd::Union{Nothing, Float64} = nothing
    Xq::Union{Nothing, Float64} = nothing
    Xd_p::Union{Nothing, Float64} = nothing
    Xq_p::Union{Nothing, Float64} = nothing
    Xd_pp::Union{Nothing, Float64} = nothing
    Xq_pp::Union{Nothing, Float64} = nothing
    Td0_p::Union{Nothing, Float64} = nothing
    Tq0_p::Union{Nothing, Float64} = nothing
    Td0_pp::Union{Nothing, Float64} = nothing
    Tq0_pp::Union{Nothing, Float64} = nothing

    function AndersonFouadMachine(id, R, Xd, Xq, Xd_p, Xq_p, Xd_pp, Xq_pp, Td0_p, Tq0_p, Td0_pp, Tq0_pp, )
        o = new(id, R, Xd, Xq, Xd_p, Xq_p, Xd_pp, Xq_pp, Td0_p, Tq0_p, Td0_pp, Tq0_pp, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AndersonFouadMachine

const _property_types_AndersonFouadMachine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("Xd")=>"Float64", Symbol("Xq")=>"Float64", Symbol("Xd_p")=>"Float64", Symbol("Xq_p")=>"Float64", Symbol("Xd_pp")=>"Float64", Symbol("Xq_pp")=>"Float64", Symbol("Td0_p")=>"Float64", Symbol("Tq0_p")=>"Float64", Symbol("Td0_pp")=>"Float64", Symbol("Tq0_pp")=>"Float64", )
OpenAPI.property_type(::Type{ AndersonFouadMachine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AndersonFouadMachine[name]))}

function OpenAPI.check_required(o::AndersonFouadMachine)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.Xd === nothing && (return false)
    o.Xq === nothing && (return false)
    o.Xd_p === nothing && (return false)
    o.Xq_p === nothing && (return false)
    o.Xd_pp === nothing && (return false)
    o.Xq_pp === nothing && (return false)
    o.Td0_p === nothing && (return false)
    o.Tq0_p === nothing && (return false)
    o.Td0_pp === nothing && (return false)
    o.Tq0_pp === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AndersonFouadMachine)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("id"), o.id)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("R"), o.R)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xd"), o.Xd)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xq"), o.Xq)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xd_p"), o.Xd_p)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xq_p"), o.Xq_p)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xd_pp"), o.Xd_pp)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Xq_pp"), o.Xq_pp)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Td0_p"), o.Td0_p)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Tq0_p"), o.Tq0_p)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Td0_pp"), o.Td0_pp)
    OpenAPI.validate_property(AndersonFouadMachine, Symbol("Tq0_pp"), o.Tq0_pp)
end

function OpenAPI.validate_property(::Type{ AndersonFouadMachine }, name::Symbol, val)












end
