# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PSS2A
IEEE dual-input stabilizer model

    PSS2A(;
        id=nothing,
        input_code_1=nothing,
        remote_bus_control_1=nothing,
        input_code_2=nothing,
        remote_bus_control_2=nothing,
        M_rtf=nothing,
        N_rtf=nothing,
        Tw1=nothing,
        Tw2=nothing,
        T6=nothing,
        Tw3=nothing,
        Tw4=nothing,
        T7=nothing,
        Ks2=nothing,
        Ks3=nothing,
        T8=nothing,
        T9=nothing,
        Ks1=nothing,
        T1=nothing,
        T2=nothing,
        T3=nothing,
        T4=nothing,
        Vst_lim=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - input_code_1::Int64 : First input code for stabilizer
    - remote_bus_control_1::Int64 : First input remote bus identification number for control. 0 identifies the local bus connected to this component
    - input_code_2::Int64 : Second input code for stabilizer
    - remote_bus_control_2::Int64 : Second input remote bus identification number for control. 0 identifies the local bus connected to this component
    - M_rtf::Int64 : M parameter for ramp tracking filter
    - N_rtf::Int64 : N parameter for ramp tracking filter
    - Tw1::Float64 : Time constant for first washout filter for first input
    - Tw2::Float64 : Time constant for second washout filter for first input
    - T6::Float64 : Time constant for low-pass filter for first input
    - Tw3::Float64 : Time constant for first washout filter for second input
    - Tw4::Float64 : Time constant for second washout filter for second input
    - T7::Float64 : Time constant for low-pass filter for second input
    - Ks2::Float64 : Gain for low-pass filter for second input
    - Ks3::Float64 : Gain for second input
    - T8::Float64 : Time constant for ramp tracking filter
    - T9::Float64 : Time constant for ramp tracking filter
    - Ks1::Float64 : Gain before lead-lag blocks
    - T1::Float64 : Time constant for first lead-lag block
    - T2::Float64 : Time constant for first lead-lag block
    - T3::Float64 : Time constant for second lead-lag block
    - T4::Float64 : Time constant for second lead-lag block
    - Vst_lim::Vector{Float64} : PSS output limits (Vst_min, Vst_max)
"""
Base.@kwdef mutable struct PSS2A <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    input_code_1::Union{Nothing, Int64} = nothing
    remote_bus_control_1::Union{Nothing, Int64} = nothing
    input_code_2::Union{Nothing, Int64} = nothing
    remote_bus_control_2::Union{Nothing, Int64} = nothing
    M_rtf::Union{Nothing, Int64} = nothing
    N_rtf::Union{Nothing, Int64} = nothing
    Tw1::Union{Nothing, Float64} = nothing
    Tw2::Union{Nothing, Float64} = nothing
    T6::Union{Nothing, Float64} = nothing
    Tw3::Union{Nothing, Float64} = nothing
    Tw4::Union{Nothing, Float64} = nothing
    T7::Union{Nothing, Float64} = nothing
    Ks2::Union{Nothing, Float64} = nothing
    Ks3::Union{Nothing, Float64} = nothing
    T8::Union{Nothing, Float64} = nothing
    T9::Union{Nothing, Float64} = nothing
    Ks1::Union{Nothing, Float64} = nothing
    T1::Union{Nothing, Float64} = nothing
    T2::Union{Nothing, Float64} = nothing
    T3::Union{Nothing, Float64} = nothing
    T4::Union{Nothing, Float64} = nothing
    Vst_lim::Union{Nothing, Vector{Float64}} = nothing

    function PSS2A(id, input_code_1, remote_bus_control_1, input_code_2, remote_bus_control_2, M_rtf, N_rtf, Tw1, Tw2, T6, Tw3, Tw4, T7, Ks2, Ks3, T8, T9, Ks1, T1, T2, T3, T4, Vst_lim, )
        o = new(id, input_code_1, remote_bus_control_1, input_code_2, remote_bus_control_2, M_rtf, N_rtf, Tw1, Tw2, T6, Tw3, Tw4, T7, Ks2, Ks3, T8, T9, Ks1, T1, T2, T3, T4, Vst_lim, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PSS2A

const _property_types_PSS2A = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("input_code_1")=>"Int64", Symbol("remote_bus_control_1")=>"Int64", Symbol("input_code_2")=>"Int64", Symbol("remote_bus_control_2")=>"Int64", Symbol("M_rtf")=>"Int64", Symbol("N_rtf")=>"Int64", Symbol("Tw1")=>"Float64", Symbol("Tw2")=>"Float64", Symbol("T6")=>"Float64", Symbol("Tw3")=>"Float64", Symbol("Tw4")=>"Float64", Symbol("T7")=>"Float64", Symbol("Ks2")=>"Float64", Symbol("Ks3")=>"Float64", Symbol("T8")=>"Float64", Symbol("T9")=>"Float64", Symbol("Ks1")=>"Float64", Symbol("T1")=>"Float64", Symbol("T2")=>"Float64", Symbol("T3")=>"Float64", Symbol("T4")=>"Float64", Symbol("Vst_lim")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ PSS2A }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PSS2A[name]))}

function OpenAPI.check_required(o::PSS2A)
    o.id === nothing && (return false)
    o.input_code_1 === nothing && (return false)
    o.remote_bus_control_1 === nothing && (return false)
    o.input_code_2 === nothing && (return false)
    o.remote_bus_control_2 === nothing && (return false)
    o.M_rtf === nothing && (return false)
    o.N_rtf === nothing && (return false)
    o.Tw1 === nothing && (return false)
    o.Tw2 === nothing && (return false)
    o.T6 === nothing && (return false)
    o.Tw3 === nothing && (return false)
    o.Tw4 === nothing && (return false)
    o.T7 === nothing && (return false)
    o.Ks2 === nothing && (return false)
    o.Ks3 === nothing && (return false)
    o.T8 === nothing && (return false)
    o.T9 === nothing && (return false)
    o.Ks1 === nothing && (return false)
    o.T1 === nothing && (return false)
    o.T2 === nothing && (return false)
    o.T3 === nothing && (return false)
    o.T4 === nothing && (return false)
    o.Vst_lim === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PSS2A)
    OpenAPI.validate_property(PSS2A, Symbol("id"), o.id)
    OpenAPI.validate_property(PSS2A, Symbol("input_code_1"), o.input_code_1)
    OpenAPI.validate_property(PSS2A, Symbol("remote_bus_control_1"), o.remote_bus_control_1)
    OpenAPI.validate_property(PSS2A, Symbol("input_code_2"), o.input_code_2)
    OpenAPI.validate_property(PSS2A, Symbol("remote_bus_control_2"), o.remote_bus_control_2)
    OpenAPI.validate_property(PSS2A, Symbol("M_rtf"), o.M_rtf)
    OpenAPI.validate_property(PSS2A, Symbol("N_rtf"), o.N_rtf)
    OpenAPI.validate_property(PSS2A, Symbol("Tw1"), o.Tw1)
    OpenAPI.validate_property(PSS2A, Symbol("Tw2"), o.Tw2)
    OpenAPI.validate_property(PSS2A, Symbol("T6"), o.T6)
    OpenAPI.validate_property(PSS2A, Symbol("Tw3"), o.Tw3)
    OpenAPI.validate_property(PSS2A, Symbol("Tw4"), o.Tw4)
    OpenAPI.validate_property(PSS2A, Symbol("T7"), o.T7)
    OpenAPI.validate_property(PSS2A, Symbol("Ks2"), o.Ks2)
    OpenAPI.validate_property(PSS2A, Symbol("Ks3"), o.Ks3)
    OpenAPI.validate_property(PSS2A, Symbol("T8"), o.T8)
    OpenAPI.validate_property(PSS2A, Symbol("T9"), o.T9)
    OpenAPI.validate_property(PSS2A, Symbol("Ks1"), o.Ks1)
    OpenAPI.validate_property(PSS2A, Symbol("T1"), o.T1)
    OpenAPI.validate_property(PSS2A, Symbol("T2"), o.T2)
    OpenAPI.validate_property(PSS2A, Symbol("T3"), o.T3)
    OpenAPI.validate_property(PSS2A, Symbol("T4"), o.T4)
    OpenAPI.validate_property(PSS2A, Symbol("Vst_lim"), o.Vst_lim)
end

function OpenAPI.validate_property(::Type{ PSS2A }, name::Symbol, val)























    if name === Symbol("Vst_lim")
        OpenAPI.validate_param(name, "PSS2A", :maxItems, val, 2)
        OpenAPI.validate_param(name, "PSS2A", :minItems, val, 2)
    end
end
