# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BaseMachine
Parameters of a Classic Machine: GENCLS in PSSE and PSLF

    BaseMachine(;
        id=nothing,
        R=nothing,
        Xd_p=nothing,
        eq_p=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - R::Float64 : Resistance after EMF
    - Xd_p::Float64 : Reactance after EMF
    - eq_p::Float64 : Fixed EMF behind the impedance
"""
Base.@kwdef mutable struct BaseMachine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    Xd_p::Union{Nothing, Float64} = nothing
    eq_p::Union{Nothing, Float64} = nothing

    function BaseMachine(id, R, Xd_p, eq_p, )
        o = new(id, R, Xd_p, eq_p, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BaseMachine

const _property_types_BaseMachine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("Xd_p")=>"Float64", Symbol("eq_p")=>"Float64", )
OpenAPI.property_type(::Type{ BaseMachine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BaseMachine[name]))}

function OpenAPI.check_required(o::BaseMachine)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.Xd_p === nothing && (return false)
    o.eq_p === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BaseMachine)
    OpenAPI.validate_property(BaseMachine, Symbol("id"), o.id)
    OpenAPI.validate_property(BaseMachine, Symbol("R"), o.R)
    OpenAPI.validate_property(BaseMachine, Symbol("Xd_p"), o.Xd_p)
    OpenAPI.validate_property(BaseMachine, Symbol("eq_p"), o.eq_p)
end

function OpenAPI.validate_property(::Type{ BaseMachine }, name::Symbol, val)




end
