# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PSSFixed
Parameters of a PSS that returns a fixed voltage to add to the reference for the AVR

    PSSFixed(;
        id=nothing,
        V_pss=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - V_pss::Float64 : Fixed voltage stabilization signal
"""
Base.@kwdef mutable struct PSSFixed <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    V_pss::Union{Nothing, Float64} = nothing

    function PSSFixed(id, V_pss, )
        o = new(id, V_pss, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PSSFixed

const _property_types_PSSFixed = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("V_pss")=>"Float64", )
OpenAPI.property_type(::Type{ PSSFixed }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PSSFixed[name]))}

function OpenAPI.check_required(o::PSSFixed)
    o.id === nothing && (return false)
    o.V_pss === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PSSFixed)
    OpenAPI.validate_property(PSSFixed, Symbol("id"), o.id)
    OpenAPI.validate_property(PSSFixed, Symbol("V_pss"), o.V_pss)
end

function OpenAPI.validate_property(::Type{ PSSFixed }, name::Symbol, val)


end
