# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SCRX
This exciter is based on an IEEE type SCRX solid state exciter. The output field voltage is varied by a control system to maintain the system voltage at Vref. Please note that this exciter model has no initialization capabilities - this means that it will respond to whatever inputs it receives regardless of the state of the machine model

    SCRX(;
        id=nothing,
        Ta_Tb=nothing,
        Tb=nothing,
        K=nothing,
        Te=nothing,
        Efd_lim=nothing,
        switch=nothing,
        rc_rfd=nothing,
        V_ref=1.0,
    )

    - id::Int64 : Unique integer identifier for this component
    - Ta_Tb::Float64 : Lead input constant ratio
    - Tb::Float64 : Lag input constant
    - K::Float64 : Regulator gain
    - Te::Float64 : Regulator time constant
    - Efd_lim::MinMax
    - switch::Int64 : Switch
    - rc_rfd::Float64 : Field current capability. Set &#x3D; 0 for negative current capability. Typical value 10
    - V_ref::Float64 : Reference voltage set-point
"""
Base.@kwdef mutable struct SCRX <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    Ta_Tb::Union{Nothing, Float64} = nothing
    Tb::Union{Nothing, Float64} = nothing
    K::Union{Nothing, Float64} = nothing
    Te::Union{Nothing, Float64} = nothing
    Efd_lim = nothing # spec type: Union{ Nothing, MinMax }
    switch::Union{Nothing, Int64} = nothing
    rc_rfd::Union{Nothing, Float64} = nothing
    V_ref::Union{Nothing, Float64} = 1.0

    function SCRX(id, Ta_Tb, Tb, K, Te, Efd_lim, switch, rc_rfd, V_ref, )
        o = new(id, Ta_Tb, Tb, K, Te, Efd_lim, switch, rc_rfd, V_ref, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SCRX

const _property_types_SCRX = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("Ta_Tb")=>"Float64", Symbol("Tb")=>"Float64", Symbol("K")=>"Float64", Symbol("Te")=>"Float64", Symbol("Efd_lim")=>"MinMax", Symbol("switch")=>"Int64", Symbol("rc_rfd")=>"Float64", Symbol("V_ref")=>"Float64", )
OpenAPI.property_type(::Type{ SCRX }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SCRX[name]))}

function OpenAPI.check_required(o::SCRX)
    o.id === nothing && (return false)
    o.Ta_Tb === nothing && (return false)
    o.Tb === nothing && (return false)
    o.K === nothing && (return false)
    o.Te === nothing && (return false)
    o.Efd_lim === nothing && (return false)
    o.switch === nothing && (return false)
    o.rc_rfd === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SCRX)
    OpenAPI.validate_property(SCRX, Symbol("id"), o.id)
    OpenAPI.validate_property(SCRX, Symbol("Ta_Tb"), o.Ta_Tb)
    OpenAPI.validate_property(SCRX, Symbol("Tb"), o.Tb)
    OpenAPI.validate_property(SCRX, Symbol("K"), o.K)
    OpenAPI.validate_property(SCRX, Symbol("Te"), o.Te)
    OpenAPI.validate_property(SCRX, Symbol("Efd_lim"), o.Efd_lim)
    OpenAPI.validate_property(SCRX, Symbol("switch"), o.switch)
    OpenAPI.validate_property(SCRX, Symbol("rc_rfd"), o.rc_rfd)
    OpenAPI.validate_property(SCRX, Symbol("V_ref"), o.V_ref)
end

function OpenAPI.validate_property(::Type{ SCRX }, name::Symbol, val)









end
