# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FiveMassShaft
Parameters of 5 mass-spring shaft model. It contains a High-Pressure (HP) steam turbine, Intermediate-Pressure (IP) steam turbine, Low-Pressure (LP) steam turbine, the Rotor and an Exciter (EX) mover

    FiveMassShaft(;
        id=nothing,
        H=nothing,
        H_hp=nothing,
        H_ip=nothing,
        H_lp=nothing,
        H_ex=nothing,
        D=nothing,
        D_hp=nothing,
        D_ip=nothing,
        D_lp=nothing,
        D_ex=nothing,
        D_12=nothing,
        D_23=nothing,
        D_34=nothing,
        D_45=nothing,
        K_hp=nothing,
        K_ip=nothing,
        K_lp=nothing,
        K_ex=nothing,
    )

    - id::Int64 : Unique integer identifier for this component
    - H::Float64 : Rotor inertia constant in MWs/MVA
    - H_hp::Float64 : High pressure turbine inertia constant in MWs/MVA
    - H_ip::Float64 : Intermediate pressure turbine inertia constant in MWs/MVA
    - H_lp::Float64 : Low pressure turbine inertia constant in MWs/MVA
    - H_ex::Float64 : Exciter inertia constant in MWs/MVA
    - D::Float64 : Rotor natural damping
    - D_hp::Float64 : High pressure turbine natural damping
    - D_ip::Float64 : Intermediate pressure turbine natural damping
    - D_lp::Float64 : Low pressure turbine natural damping
    - D_ex::Float64 : Exciter natural damping
    - D_12::Float64 : High-intermediate pressure turbine damping
    - D_23::Float64 : Intermediate-low pressure turbine damping
    - D_34::Float64 : Low pressure turbine-rotor damping
    - D_45::Float64 : Rotor-exciter damping
    - K_hp::Float64 : High pressure turbine angle coefficient
    - K_ip::Float64 : Intermediate pressure turbine angle coefficient
    - K_lp::Float64 : Low pressure turbine angle coefficient
    - K_ex::Float64 : Exciter angle coefficient
"""
Base.@kwdef mutable struct FiveMassShaft <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    H::Union{Nothing, Float64} = nothing
    H_hp::Union{Nothing, Float64} = nothing
    H_ip::Union{Nothing, Float64} = nothing
    H_lp::Union{Nothing, Float64} = nothing
    H_ex::Union{Nothing, Float64} = nothing
    D::Union{Nothing, Float64} = nothing
    D_hp::Union{Nothing, Float64} = nothing
    D_ip::Union{Nothing, Float64} = nothing
    D_lp::Union{Nothing, Float64} = nothing
    D_ex::Union{Nothing, Float64} = nothing
    D_12::Union{Nothing, Float64} = nothing
    D_23::Union{Nothing, Float64} = nothing
    D_34::Union{Nothing, Float64} = nothing
    D_45::Union{Nothing, Float64} = nothing
    K_hp::Union{Nothing, Float64} = nothing
    K_ip::Union{Nothing, Float64} = nothing
    K_lp::Union{Nothing, Float64} = nothing
    K_ex::Union{Nothing, Float64} = nothing

    function FiveMassShaft(id, H, H_hp, H_ip, H_lp, H_ex, D, D_hp, D_ip, D_lp, D_ex, D_12, D_23, D_34, D_45, K_hp, K_ip, K_lp, K_ex, )
        o = new(id, H, H_hp, H_ip, H_lp, H_ex, D, D_hp, D_ip, D_lp, D_ex, D_12, D_23, D_34, D_45, K_hp, K_ip, K_lp, K_ex, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FiveMassShaft

const _property_types_FiveMassShaft = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("H")=>"Float64", Symbol("H_hp")=>"Float64", Symbol("H_ip")=>"Float64", Symbol("H_lp")=>"Float64", Symbol("H_ex")=>"Float64", Symbol("D")=>"Float64", Symbol("D_hp")=>"Float64", Symbol("D_ip")=>"Float64", Symbol("D_lp")=>"Float64", Symbol("D_ex")=>"Float64", Symbol("D_12")=>"Float64", Symbol("D_23")=>"Float64", Symbol("D_34")=>"Float64", Symbol("D_45")=>"Float64", Symbol("K_hp")=>"Float64", Symbol("K_ip")=>"Float64", Symbol("K_lp")=>"Float64", Symbol("K_ex")=>"Float64", )
OpenAPI.property_type(::Type{ FiveMassShaft }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FiveMassShaft[name]))}

function OpenAPI.check_required(o::FiveMassShaft)
    o.id === nothing && (return false)
    o.H === nothing && (return false)
    o.H_hp === nothing && (return false)
    o.H_ip === nothing && (return false)
    o.H_lp === nothing && (return false)
    o.H_ex === nothing && (return false)
    o.D === nothing && (return false)
    o.D_hp === nothing && (return false)
    o.D_ip === nothing && (return false)
    o.D_lp === nothing && (return false)
    o.D_ex === nothing && (return false)
    o.D_12 === nothing && (return false)
    o.D_23 === nothing && (return false)
    o.D_34 === nothing && (return false)
    o.D_45 === nothing && (return false)
    o.K_hp === nothing && (return false)
    o.K_ip === nothing && (return false)
    o.K_lp === nothing && (return false)
    o.K_ex === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::FiveMassShaft)
    OpenAPI.validate_property(FiveMassShaft, Symbol("id"), o.id)
    OpenAPI.validate_property(FiveMassShaft, Symbol("H"), o.H)
    OpenAPI.validate_property(FiveMassShaft, Symbol("H_hp"), o.H_hp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("H_ip"), o.H_ip)
    OpenAPI.validate_property(FiveMassShaft, Symbol("H_lp"), o.H_lp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("H_ex"), o.H_ex)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D"), o.D)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_hp"), o.D_hp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_ip"), o.D_ip)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_lp"), o.D_lp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_ex"), o.D_ex)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_12"), o.D_12)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_23"), o.D_23)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_34"), o.D_34)
    OpenAPI.validate_property(FiveMassShaft, Symbol("D_45"), o.D_45)
    OpenAPI.validate_property(FiveMassShaft, Symbol("K_hp"), o.K_hp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("K_ip"), o.K_ip)
    OpenAPI.validate_property(FiveMassShaft, Symbol("K_lp"), o.K_lp)
    OpenAPI.validate_property(FiveMassShaft, Symbol("K_ex"), o.K_ex)
end

function OpenAPI.validate_property(::Type{ FiveMassShaft }, name::Symbol, val)



















end
