# The exact per-package "is this a document component type" name sets, frozen from the
# pre-1.0 (openapi-generator) `register.jl` files before the native-generator migration.
#
# The native generator gives every schema the same `struct` shape (no `<: OpenAPI.APIModel`
# marker distinguishing a document component from a small value type like `MinMax`), so that
# selection can no longer be derived from struct-declaration syntax the way
# `emit_registry.jl`'s old `model_types_in` did. Carrying the frozen name set forward instead
# of re-deriving a new heuristic keeps `SystemDocument`'s registry membership identical across
# the migration.
# `StorageCostStartUpOneOf` (an internal oneOf-variant wrapper for `StorageCost.start_up`,
# never a top-level document component) is dropped from the frozen "core" set below: the
# native generator names synthesized union variants differently (`StorageCostStartUp2`), and
# nothing in document.jl looks this name up by string, so there is nothing to rename it to.
const REGISTERED_NAMES = Dict{String, Vector{String}}(
    "infrastructure-core" => [
        "ComplexNumber",
        "DataSource",
        "FromTo",
        "FromToToFrom",
        "FunctionData",
        "GeographicInfo",
        "InOut",
        "LinearFunctionData",
        "MinMax",
        "PiecewiseLinearData",
        "PiecewiseStepData",
        "QuadraticFunctionData",
        "SupplementalAttributeAssociation",
        "TimeSeriesLinearFunctionData",
        "TimeSeriesPiecewiseLinearData",
        "TimeSeriesPiecewiseStepData",
        "TimeSeriesQuadraticFunctionData",
        "UpDown",
        "XYCoords",
    ],
    "timeseries" => [
        "Deterministic",
        "DeterministicSingleTimeSeries",
        "NonSequentialTimeSeries",
        "Probabilistic",
        "Scenarios",
        "SingleTimeSeries",
        "TimeSeriesAssociation",
        "TimeSeriesFeatureValue",
    ],
    "core" => [
        "AverageRateCurve",
        "CostCurve",
        "DbdPnts",
        "FdbdPnts",
        "FuelCurve",
        "GenericOperationCost",
        "HydroGenerationCost",
        "HydroReservoirCost",
        "HydroStorageGenerationCost",
        "ImportExportCost",
        "ImportExportTimeSeriesCost",
        "IncrementalCurve",
        "IncrementalCurveFunctionData",
        "InputOutputCurve",
        "InputOutputCurveFunctionData",
        "LoadCost",
        "MarketBidCost",
        "MarketBidTimeSeriesCost",
        "ProductionVariableCostCurve",
        "RenewableGenerationCost",
        "StartUpShutDown",
        "StartUpStages",
        "StorageCost",
        "StorageCostStartUp",
        "ThermalGenerationCost",
        "ThermalGenerationCostStartUp",
        "TimeSeriesAverageRateCurve",
        "TimeSeriesIncrementalCurve",
        "TimeSeriesInputOutputCurve",
        "TurbinePump",
        "TwoTerminalLoss",
        "ValueCurve",
    ],
    "operations" => [
        "ACBus",
        "AGC",
        "Arc",
        "Area",
        "AreaInterchange",
        "BilateralTransaction",
        "CombinedCycleAssociation",
        "CombinedCycleBlock",
        "CombinedCycleFractional",
        "DCBus",
        "DiscreteControlledACBranch",
        "EmissionsData",
        "EnergyReservoirStorage",
        "EnergyReservoirStorageOperationCost",
        "ExponentialLoad",
        "FACTSControlDevice",
        "FixedAdmittance",
        "FixedForcedOutage",
        "GenericArcImpedance",
        "GeometricDistributionForcedOutage",
        "GroupReserve",
        "HybridSystem",
        "HydroDispatch",
        "HydroDispatchOperationCost",
        "HydroPowerPlant",
        "HydroPumpTurbine",
        "HydroReservoir",
        "HydroReservoirOperationCost",
        "HydroTurbine",
        "ImpedanceCorrectionData",
        "InterconnectingConverter",
        "InterruptiblePowerLoad",
        "InterruptiblePowerLoadOperationCost",
        "InterruptibleStandardLoad",
        "Line",
        "LoadZone",
        "MonitoredLine",
        "MotorLoad",
        "OfflineReserve",
        "OnlineReserve",
        "PlannedOutage",
        "PlantAssociation",
        "PointToPointBid",
        "PointToPointBidSpreadBid",
        "PowerLoad",
        "RenewableDispatch",
        "RenewableDispatchOperationCost",
        "RenewableNonDispatch",
        "RenewablePowerPlant",
        "ServiceAssociation",
        "ShiftablePowerLoad",
        "Source",
        "SourceOperationCost",
        "StandardLoad",
        "Substation",
        "SwitchedAdmittance",
        "SynchronousCondenser",
        "TModelHVDCLine",
        "ThermalMultiStart",
        "ThermalMultiStartOperationCost",
        "ThermalPowerPlant",
        "ThermalStandard",
        "ThermalStandardOperationCost",
        "ThreeWindingTransformer",
        "TradingHub",
        "TradingHubAssociation",
        "TransformerCircuit",
        "TransmissionInterface",
        "TwoTerminalGenericHVDCLine",
        "TwoTerminalLCCLine",
        "TwoTerminalVSCLine",
        "TwoWindingTransformer",
        "VirtualParticipant",
        "VirtualParticipantOperationCost",
    ],
    "investments" => [
        "AggregateRetirementPotential",
        "AggregateRetrofitPotential",
        "AggregateTransportTechnology",
        "CapacityReserveMargin",
        "CarbonCaps",
        "CarbonTax",
        "ColocatedSupplyStorageTechnology",
        "DemandRequirement",
        "DemandSideTechnology",
        "EnergyShareRequirements",
        "ExistingDevices",
        "HourlyMatching",
        "MaximumCapacityRequirements",
        "MinimumCapacityRequirements",
        "NodalACTransportTechnology",
        "NodalHVDCTransportTechnology",
        "Node",
        "PortfolioFinancialData",
        "RetirementPotential",
        "RetrofitPotential",
        "StorageTechnology",
        "SupplyTechnology",
        "TechnologyFinancialData",
        "TopologyMapping",
        "Zone",
    ],
    "dynamics" => [
        "ActiveRenewableControllerAB",
        "RECurrentControlB",
        "ReactiveRenewableControllerAB",
        "RenewableEnergyConverterTypeA",
        "RoundRotorMachine",
        "SEXS",
        "SteamTurbineGov1",
    ],
)
