# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PiecewiseStepData
Data for a step function, constant on each segment, defined by the x coordinates of the segment endpoints and one y value per segment. The y values are per-segment rates, not absolute values; use &#x60;PiecewiseLinearData&#x60; when the data gives a value at each point. &#x60;x_coords&#x60; ascends and holds at least two entries, and &#x60;y_coords&#x60; holds exactly one fewer.

    PiecewiseStepData(;
        function_type="PIECEWISE_STEP",
        x_coords=nothing,
        y_coords=nothing,
    )

    - function_type::String
    - x_coords::Vector{Float64}
    - y_coords::Vector{Float64}
"""
Base.@kwdef mutable struct PiecewiseStepData <: OpenAPI.APIModel
    function_type::Union{Nothing, String} = "PIECEWISE_STEP"
    x_coords::Union{Nothing, Vector{Float64}} = nothing
    y_coords::Union{Nothing, Vector{Float64}} = nothing

    function PiecewiseStepData(function_type, x_coords, y_coords, )
        o = new(function_type, x_coords, y_coords, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PiecewiseStepData

const _property_types_PiecewiseStepData = Dict{Symbol,Type}(Symbol("function_type")=>Union{Nothing, String}, Symbol("x_coords")=>Union{Nothing, Vector{Float64}}, Symbol("y_coords")=>Union{Nothing, Vector{Float64}}, )
OpenAPI.property_type(::Type{ PiecewiseStepData }, name::Symbol) = _property_types_PiecewiseStepData[name]

function OpenAPI.check_required(o::PiecewiseStepData)
    o.function_type === nothing && (return false)
    o.x_coords === nothing && (return false)
    o.y_coords === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PiecewiseStepData)
    OpenAPI.validate_property(PiecewiseStepData, Symbol("function_type"), o.function_type)
    OpenAPI.validate_property(PiecewiseStepData, Symbol("x_coords"), o.x_coords)
    OpenAPI.validate_property(PiecewiseStepData, Symbol("y_coords"), o.y_coords)
end

function OpenAPI.validate_property(::Type{ PiecewiseStepData }, name::Symbol, val)

    if name === Symbol("function_type")
        OpenAPI.validate_param(name, "PiecewiseStepData", :enum, val, ["PIECEWISE_STEP"])
    end



end
